import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _mn_common import E, ROWS, set_region
set_region('americas')

# ---------------- CANADA ----------------
E("new-france","New France","polity",1534,1763,False,"Canada","French colonial empire in North America from Acadia and Quebec to Louisiana, ceded to Britain and Spain in 1763.",["Nouvelle-France"])
E("cartier-voyages","Jacques Cartier's Voyages","event",1534,1542,False,"Canada","Three French voyages that claimed the St Lawrence for France and named Canada.",[])
E("founding-of-quebec-city","Founding of Quebec City","event",1608,1608,False,"New France","Samuel de Champlain established the habitation at Quebec, the permanent base of New France.",[])
E("hudsons-bay-company","Hudson's Bay Company","polity",1670,None,True,"Canada","Royal-chartered fur-trade company that governed Rupert's Land until selling it to Canada in 1870.",["HBC"])
E("beaver-wars","Beaver Wars","event",1609,1701,False,"North America","Long Iroquois-French-Algonquian conflicts over the fur trade, ended by the Great Peace of Montreal.",["Iroquois Wars"])
E("acadian-expulsion","Expulsion of the Acadians","event",1755,1764,False,"Canada","British deportation of some 10,000 French-speaking Acadians from the Maritimes.",["Grand Derangement"])
E("seven-years-war-north-america","Conquest of Canada","event",1754,1763,False,"Canada","French and Indian War campaigns culminating at the Plains of Abraham in 1759 and the Treaty of Paris.",["French and Indian War","Battle of the Plains of Abraham"])
E("province-of-quebec-british","Province of Quebec (British)","polity",1763,1791,False,"Canada","British colony where the Quebec Act of 1774 guaranteed French civil law and Catholic rights.",["Quebec Act"])
E("upper-and-lower-canada","Upper and Lower Canada","polity",1791,1841,False,"Canada","Two colonies created by the Constitutional Act, each with an elected assembly, joined after the 1837 rebellions.",[])
E("war-of-1812-canada","War of 1812 in Canada","event",1812,1815,False,"Canada","American invasions repelled by British regulars, Canadian militia and Indigenous allies under Tecumseh and Brock.",[])
E("rebellions-of-1837","Rebellions of 1837-38","event",1837,1838,False,"Canada","Patriote and Upper Canadian revolts for responsible government, suppressed but leading to the Durham Report.",["Lower Canada Rebellion","Patriotes"])
E("province-of-canada","Province of Canada","polity",1841,1867,False,"Canada","United colony of Canada East and West that won responsible government in 1848.",["United Canada","Act of Union"])
E("canadian-confederation","Canadian Confederation","event",1867,1867,False,"Canada","British North America Act of 1 July 1867 united Canada, Nova Scotia and New Brunswick as a federal dominion.",["British North America Act","Dominion of Canada"])
E("dominion-of-canada","Canada","polity",1867,None,True,"Canada","Federal dominion of 1867 that grew to ten provinces and three territories and became fully sovereign by stages.",["Dominion of Canada"])
E("red-river-resistance","Red River Resistance","event",1869,1870,False,"Canada","Louis Riel's Metis provisional government, which led to Manitoba's creation as a province.",["Red River Rebellion"])
E("manitoba-joins-canada","Manitoba Joins Canada","event",1870,1870,False,"Canada","Manitoba entered Confederation as the fifth province after the Red River Resistance.",[])
E("british-columbia-joins-canada","British Columbia Joins Canada","event",1871,1871,False,"Canada","BC entered Confederation on the promise of a transcontinental railway.",[])
E("pei-joins-canada","Prince Edward Island Joins Canada","event",1873,1873,False,"Canada","PEI entered Confederation in 1873, burdened by railway debt.",[])
E("canadian-pacific-railway","Completion of the Canadian Pacific Railway","event",1885,1885,False,"Canada","Last spike at Craigellachie linked Canada by rail, built largely by Chinese labourers.",["CPR"])
E("north-west-rebellion","North-West Rebellion","event",1885,1885,False,"Canada","Metis and Cree resistance led by Riel and Big Bear, defeated and followed by Riel's execution.",["North-West Resistance"])
E("alberta-saskatchewan-created","Creation of Alberta and Saskatchewan","event",1905,1905,False,"Canada","Two new prairie provinces carved from the North-West Territories.",[])
E("canada-first-world-war","Canada in the First World War","event",1914,1918,False,"Canada","More than 600,000 served; Vimy Ridge and the conscription crisis shaped national identity.",["Vimy Ridge"])
E("statute-of-westminster","Statute of Westminster","event",1931,1931,False,"Canada and the Commonwealth","British act recognising the legislative independence of the dominions.",[])
E("newfoundland-joins-canada","Newfoundland Joins Canada","event",1949,1949,False,"Canada","Newfoundland became Canada's tenth province after two close referendums.",[])
E("quiet-revolution","Quiet Revolution","period",1960,1970,False,"Quebec, Canada","Rapid secularisation and state-building in Quebec that transformed its politics and fuelled sovereigntism.",["Revolution tranquille"])
E("october-crisis","October Crisis","event",1970,1970,False,"Canada","FLQ kidnappings and the murder of Pierre Laporte led Trudeau to invoke the War Measures Act.",[])
E("quebec-referendum-1980","Quebec Referendum of 1980","event",1980,1980,False,"Canada","Sovereignty-association rejected by 60 percent of Quebec voters.",[])
E("constitution-act-1982","Constitution Act, 1982","event",1982,1982,False,"Canada","Patriation of the constitution with the Charter of Rights and Freedoms, without Quebec's consent.",["Patriation","Charter of Rights"])
E("quebec-referendum-1995","Quebec Referendum of 1995","event",1995,1995,False,"Canada","Sovereignty narrowly defeated by 50.6 to 49.4 percent.",[])
E("nunavut-created","Creation of Nunavut","event",1999,1999,False,"Canada","New Inuit-majority territory established from the eastern Northwest Territories.",[])
E("canadian-trc","Truth and Reconciliation Commission of Canada","event",2008,2015,False,"Canada","Inquiry into residential schools that documented cultural genocide against Indigenous peoples.",["TRC"])
E("canadian-residential-schools","Canadian Indian Residential School System","polity",1883,1996,False,"Canada","Church-run, state-funded schools that forcibly assimilated Indigenous children, with thousands of deaths.",[])
E("pm-john-a-macdonald","Premiership of John A. Macdonald","reign",1867,1891,False,"Canada","First prime minister (1867-73, 1878-91): Confederation, the CPR, the National Policy and the Riel executions.",[])
E("pm-alexander-mackenzie","Premiership of Alexander Mackenzie","reign",1873,1878,False,"Canada","Liberal prime minister who created the Supreme Court and the secret ballot.",[])
E("pm-john-abbott","Premiership of John Abbott","reign",1891,1892,False,"Canada","Conservative caretaker prime minister after Macdonald's death.",[])
E("pm-john-thompson","Premiership of John Thompson","reign",1892,1894,False,"Canada","Prime minister who codified the Criminal Code and died in office at Windsor Castle.",[])
E("pm-mackenzie-bowell","Premiership of Mackenzie Bowell","reign",1894,1896,False,"Canada","Prime minister brought down by cabinet revolt over the Manitoba schools question.",[])
E("pm-charles-tupper","Premiership of Charles Tupper","reign",1896,1896,False,"Canada","Shortest-serving Canadian prime minister, in office 69 days.",[])
E("pm-wilfrid-laurier","Premiership of Wilfrid Laurier","reign",1896,1911,False,"Canada","First francophone prime minister: immigration boom, two new provinces and compromise on imperial questions.",[])
E("pm-robert-borden","Premiership of Robert Borden","reign",1911,1920,False,"Canada","Wartime prime minister: conscription crisis, Union government and a separate Canadian seat at Versailles.",[])
E("pm-arthur-meighen","Premiership of Arthur Meighen","reign",1920,1926,False,"Canada","Conservative prime minister in 1920-21 and briefly in 1926 during the King-Byng affair.",[])
E("pm-mackenzie-king","Premiership of William Lyon Mackenzie King","reign",1921,1948,False,"Canada","Longest-serving prime minister in the Commonwealth: Depression, wartime leadership and the welfare state's start.",[])
E("pm-rb-bennett","Premiership of R. B. Bennett","reign",1930,1935,False,"Canada","Depression-era Conservative prime minister who created the Bank of Canada and the CBC's predecessor.",[])
E("pm-louis-st-laurent","Premiership of Louis St-Laurent","reign",1948,1957,False,"Canada","'Uncle Louis' oversaw NATO membership, Newfoundland's entry and the St Lawrence Seaway.",[])
E("pm-john-diefenbaker","Premiership of John Diefenbaker","reign",1957,1963,False,"Canada","Prairie Conservative: the Bill of Rights, Indigenous voting rights and the Avro Arrow cancellation.",[])
E("pm-lester-pearson","Premiership of Lester Pearson","reign",1963,1968,False,"Canada","Nobel peace laureate whose minority governments created medicare, the maple leaf flag and the Canada Pension Plan.",[])
E("pm-pierre-trudeau","Premiership of Pierre Trudeau","reign",1968,1984,False,"Canada","Prime minister 1968-79 and 1980-84: bilingualism, multiculturalism, the October Crisis and patriation with the Charter.",[])
E("pm-joe-clark","Premiership of Joe Clark","reign",1979,1980,False,"Canada","Nine-month Progressive Conservative minority government defeated on its budget.",[])
E("pm-john-turner","Premiership of John Turner","reign",1984,1984,False,"Canada","Liberal prime minister for 79 days before a landslide defeat.",[])
E("pm-brian-mulroney","Premiership of Brian Mulroney","reign",1984,1993,False,"Canada","Free trade with the United States, the GST, failed Meech Lake and Charlottetown accords, and anti-apartheid diplomacy.",[])
E("pm-kim-campbell","Premiership of Kim Campbell","reign",1993,1993,False,"Canada","Canada's first woman prime minister, in office for about four months.",[])
E("pm-jean-chretien","Premiership of Jean Chretien","reign",1993,2003,False,"Canada","Deficit elimination, the 1995 referendum and the Clarity Act, and refusal to join the Iraq war.",[])
E("pm-paul-martin","Premiership of Paul Martin","reign",2003,2006,False,"Canada","Prime minister who legalised same-sex marriage nationally and faced the sponsorship scandal.",[])
E("pm-stephen-harper","Premiership of Stephen Harper","reign",2006,2015,False,"Canada","Conservative prime minister through the 2008 crisis, the residential schools apology and Afghan combat operations.",[])
E("pm-justin-trudeau","Premiership of Justin Trudeau","reign",2015,2025,False,"Canada","Liberal prime minister: cannabis legalisation, carbon pricing, USMCA and the COVID-19 response.",[])
E("pm-mark-carney","Premiership of Mark Carney","reign",2025,None,True,"Canada","Former central banker who became Liberal leader and prime minister in 2025.",[],"medium")

# ---------------- MEXICO ----------------
E("viceroyalty-of-new-spain","Viceroyalty of New Spain","polity",1535,1821,False,"Mexico","Spanish viceroyalty ruling Mexico, Central America, the Caribbean and the Philippines from Mexico City.",["Nueva Espana"])
E("spanish-conquest-of-mexico","Spanish Conquest of the Aztec Empire","event",1519,1521,False,"Mexico","Cortes and Indigenous allies destroyed Tenochtitlan, beginning Spanish rule in Mesoamerica.",["Conquest of Mexico"])
E("mexican-war-of-independence","Mexican War of Independence","event",1810,1821,False,"Mexico","Eleven-year struggle begun by Hidalgo's Grito de Dolores and completed by Iturbide's Plan of Iguala.",["Grito de Dolores"])
E("first-mexican-empire","First Mexican Empire","polity",1821,1823,False,"Mexico","Agustin de Iturbide's brief empire, which included Central America.",[])
E("first-mexican-republic","First Mexican Republic","polity",1824,1835,False,"Mexico","Federal republic under the 1824 constitution, riven by centralist-federalist conflict.",[])
E("santa-anna-era","Era of Santa Anna","period",1833,1855,False,"Mexico","Antonio Lopez de Santa Anna held the presidency eleven times amid the loss of Texas and the war with the United States.",[])
E("texas-revolution","Texas Revolution","event",1835,1836,False,"Mexico","Anglo-Texan and Tejano revolt that won independence after the Alamo and San Jacinto.",[])
E("mexican-american-war","Mexican-American War","event",1846,1848,False,"Mexico","War that cost Mexico half its territory under the Treaty of Guadalupe Hidalgo.",["Intervencion estadounidense"])
E("la-reforma","La Reforma","period",1855,1876,False,"Mexico","Liberal reforms under Juarez that curbed church and army privilege and produced the 1857 constitution.",[])
E("reform-war","War of the Reform","event",1857,1861,False,"Mexico","Civil war between liberals and conservatives won by Juarez's liberals.",["Three Years War"])
E("second-mexican-empire","Second Mexican Empire","polity",1864,1867,False,"Mexico","French-imposed empire of Maximilian of Habsburg, which collapsed when France withdrew; he was executed at Queretaro.",["Maximilian's empire"])
E("juarez-presidency","Presidency of Benito Juarez","reign",1858,1872,False,"Mexico","Zapotec liberal who led resistance to the French intervention and restored the republic.",[])
E("porfiriato","Porfiriato","reign",1876,1911,False,"Mexico","Porfirio Diaz's 35-year rule: railways, foreign investment and repression, ended by the Revolution.",["Porfirio Diaz"])
E("mexican-revolution","Mexican Revolution","event",1910,1920,False,"Mexico","Decade of civil war involving Madero, Villa, Zapata, Carranza and Obregon, costing perhaps a million lives.",["Revolucion Mexicana"])
E("mexican-constitution-1917","Mexican Constitution of 1917","event",1917,1917,False,"Mexico","Landmark constitution establishing land reform, labour rights and state ownership of subsoil resources.",[])
E("cristero-war","Cristero War","event",1926,1929,False,"Mexico","Catholic rural rebellion against anticlerical enforcement, settled by negotiated modus vivendi.",["La Cristiada"])
E("pri-rule","Rule of the Institutional Revolutionary Party","reign",1929,2000,False,"Mexico","Single dominant party governed Mexico for 71 years under a rotating presidential system.",["PRI","PNR","PRM"])
E("cardenas-presidency","Presidency of Lazaro Cardenas","reign",1934,1940,False,"Mexico","Land redistribution, support for Spanish republicans and the 1938 nationalisation of oil as Pemex.",[])
E("mexican-oil-expropriation","Mexican Oil Expropriation","event",1938,1938,False,"Mexico","Cardenas nationalised foreign oil companies and created Pemex, a founding act of economic sovereignty.",[])
E("tlatelolco-massacre","Tlatelolco Massacre","event",1968,1968,False,"Mexico","Army killing of student protesters in Mexico City days before the Olympics.",[])
E("mexican-peso-crisis","Mexican Peso Crisis","event",1994,1995,False,"Mexico","Currency collapse and US-led bailout known as the Tequila Crisis.",["Tequila Crisis"])
E("zapatista-uprising","Zapatista Uprising","event",1994,1994,False,"Mexico","EZLN indigenous rebellion in Chiapas launched as NAFTA took effect.",["EZLN"])
E("mexican-democratic-transition","Mexican Democratic Transition","event",2000,2000,False,"Mexico","Vicente Fox's victory ended 71 years of PRI presidential rule.",[])
E("mexican-drug-war","Mexican Drug War","event",2006,None,True,"Mexico","Militarised campaign against cartels launched by Felipe Calderon, with well over 300,000 dead.",[])
E("united-mexican-states","United Mexican States","polity",1824,None,True,"Mexico","Federal republic of 31 states and a capital, Latin America's second-largest economy.",["Mexico","Estados Unidos Mexicanos"])
E("presidency-amlo","Presidency of Andres Manuel Lopez Obrador","reign",2018,2024,False,"Mexico","Leftist president who built Morena's dominance and expanded social programmes and military infrastructure roles.",["AMLO"])
E("presidency-sheinbaum","Presidency of Claudia Sheinbaum","reign",2024,None,True,"Mexico","Mexico's first woman president, elected in 2024 as AMLO's successor.",[])

# ---------------- BRAZIL ----------------
E("colonial-brazil","Colonial Brazil","polity",1500,1815,False,"Brazil","Portuguese colony built on sugar, gold and enslaved African labour, with its capital at Salvador then Rio.",["Brasil Colonia"])
E("cabral-landing","Portuguese Landing in Brazil","event",1500,1500,False,"Brazil","Pedro Alvares Cabral reached the Brazilian coast in April 1500, claiming it for Portugal.",[])
E("dutch-brazil","Dutch Brazil","polity",1630,1654,False,"Brazil","Dutch West India Company colony in Pernambuco under Johan Maurits, expelled by Luso-Brazilian forces.",["New Holland"])
E("quilombo-palmares","Quilombo dos Palmares","polity",1605,1694,False,"Brazil","Large maroon polity of escaped enslaved people in Alagoas, destroyed after decades of resistance under Zumbi.",["Palmares"])
E("brazilian-gold-rush","Minas Gerais Gold Rush","event",1695,1760,False,"Brazil","Gold and diamond boom that shifted Brazil's centre south and funded Portuguese and British commerce.",[])
E("transfer-of-portuguese-court","Transfer of the Portuguese Court to Brazil","event",1808,1808,False,"Brazil and Portugal","The royal family fled Napoleon to Rio, opening Brazilian ports and elevating the colony.",[])
E("united-kingdom-portugal-brazil","United Kingdom of Portugal, Brazil and the Algarves","polity",1815,1822,False,"Brazil and Portugal","Transatlantic kingdom in which Brazil was legally equal to Portugal.",[])
E("brazilian-independence","Brazilian Independence","event",1822,1822,False,"Brazil","Pedro I's Grito do Ipiranga on 7 September 1822 declared independence, achieved with little bloodshed.",["Grito do Ipiranga"])
E("empire-of-brazil","Empire of Brazil","polity",1822,1889,False,"Brazil","Constitutional monarchy of the Americas under Pedro I and Pedro II, which abolished slavery and fell to a coup.",["Imperio do Brasil"])
E("reign-pedro-i-brazil","Reign of Pedro I of Brazil","reign",1822,1831,False,"Empire of Brazil","Founder of the empire who granted the 1824 constitution and abdicated to claim the Portuguese throne.",[])
E("reign-pedro-ii-brazil","Reign of Pedro II of Brazil","reign",1831,1889,False,"Empire of Brazil","Long, stable reign of a scholar-emperor: the Paraguayan War, coffee expansion, abolition and deposition.",[])
E("paraguayan-war","Paraguayan War","event",1864,1870,False,"South America","Triple Alliance of Brazil, Argentina and Uruguay devastated Paraguay, killing a large share of its population.",["War of the Triple Alliance"])
E("brazilian-golden-law","Golden Law","event",1888,1888,False,"Brazil","Abolition of slavery in Brazil, the last country in the Americas to end it.",["Lei Aurea"])
E("brazilian-first-republic","First Brazilian Republic","polity",1889,1930,False,"Brazil","Oligarchic 'coffee with milk' republic of Sao Paulo and Minas elites, ended by Vargas's revolution.",["Old Republic","Republica Velha"])
E("vargas-era","Vargas Era","reign",1930,1945,False,"Brazil","Getulio Vargas ruled by revolution then dictatorship, creating labour laws, industry and the Estado Novo.",["Getulio Vargas"])
E("estado-novo-brazil","Estado Novo (Brazil)","polity",1937,1945,False,"Brazil","Vargas's corporatist dictatorship, which nonetheless joined the Allies in 1942.",[])
E("brazilian-second-republic","Brazilian Second Republic","polity",1946,1964,False,"Brazil","Democratic period of developmentalism, the building of Brasilia and mounting political crisis.",[])
E("founding-of-brasilia","Founding of Brasilia","event",1960,1960,False,"Brazil","Kubitschek's modernist capital inaugurated in the interior, designed by Costa and Niemeyer.",[])
E("brazilian-military-dictatorship","Brazilian Military Dictatorship","polity",1964,1985,False,"Brazil","Twenty-one years of army rule with censorship, torture and the 'economic miracle', ending in a gradual opening.",["Regime militar"])
E("brazilian-new-republic","Federative Republic of Brazil","polity",1985,None,True,"Brazil","Democratic Brazil under the 1988 constitution, with the Real Plan, commodity boom and impeachment crises.",["Brazil","Nova Republica"])
E("plano-real","Plano Real","event",1994,1994,False,"Brazil","Currency stabilisation plan that ended hyperinflation and introduced the real.",[])
E("lula-presidency","Presidencies of Luiz Inacio Lula da Silva","reign",2003,None,True,"Brazil","Trade-unionist president 2003-2010 and again from 2023: Bolsa Familia, poverty reduction and diplomatic prominence.",["Lula"])
E("rousseff-impeachment","Impeachment of Dilma Rousseff","event",2016,2016,False,"Brazil","Brazil's first woman president removed amid recession and the Lava Jato corruption investigation.",["Operation Car Wash"])
E("bolsonaro-presidency","Presidency of Jair Bolsonaro","reign",2019,2022,False,"Brazil","Right-wing populist presidency marked by Amazon deforestation, COVID-19 denial and the 2023 Brasilia riot.",[])

# ---------------- SPANISH AMERICA & INDEPENDENCE ----------------
E("viceroyalty-of-peru","Viceroyalty of Peru","polity",1542,1824,False,"South America","Spanish viceroyalty centred on Lima that governed most of South America and the Potosi silver economy.",["Virreinato del Peru"])
E("viceroyalty-of-new-granada","Viceroyalty of New Granada","polity",1717,1819,False,"South America","Spanish viceroyalty covering Colombia, Venezuela, Ecuador and Panama, based at Bogota.",["Nueva Granada"])
E("viceroyalty-rio-de-la-plata","Viceroyalty of the Rio de la Plata","polity",1776,1814,False,"South America","Late Spanish viceroyalty based in Buenos Aires covering Argentina, Uruguay, Paraguay and Bolivia.",[])
E("potosi-silver-mining","Potosi Silver Complex","era",1545,1800,False,"Bolivia","Cerro Rico mines worked under the mita labour draft supplied much of the world's silver and financed Spain.",["Cerro Rico"])
E("bourbon-reforms","Bourbon Reforms","era",1750,1808,False,"Spanish America","Administrative, fiscal and military reforms that increased extraction and provoked creole resentment and revolt.",[])
E("tupac-amaru-ii-rebellion","Rebellion of Tupac Amaru II","event",1780,1783,False,"Peru","Largest Andean uprising against Spanish rule, brutally suppressed after threatening Cusco.",[])
E("spanish-american-wars-of-independence","Spanish American Wars of Independence","era",1808,1833,False,"Latin America","Continental struggle that ended Spanish rule in the mainland Americas and created some fifteen republics.",["Latin American wars of independence"])
E("simon-bolivar-campaigns","Campaigns of Simon Bolivar","era",1813,1830,False,"Latin America","The Liberator's campaigns from Venezuela over the Andes to Boyaca, Carabobo, Junin and Ayacucho.",["Simon Bolivar","El Libertador"])
E("san-martin-campaigns","Campaigns of Jose de San Martin","era",1814,1822,False,"Latin America","Crossing of the Andes, liberation of Chile at Chacabuco and Maipu, and the proclamation of Peru's independence.",["Jose de San Martin"])
E("battle-of-ayacucho","Battle of Ayacucho","event",1824,1824,False,"Peru","Sucre's victory that destroyed the last royalist army and sealed South American independence.",[])
E("gran-colombia","Gran Colombia","polity",1819,1831,False,"South America","Bolivar's union of Colombia, Venezuela, Ecuador and Panama, dissolved by regional rivalries.",["Great Colombia"])
E("congress-of-panama","Congress of Panama","event",1826,1826,False,"Latin America","Bolivar's attempt at a league of American republics, an ancestor of Pan-Americanism.",[])
E("united-provinces-central-america","Federal Republic of Central America","polity",1823,1841,False,"Central America","Union of Guatemala, El Salvador, Honduras, Nicaragua and Costa Rica that fragmented into five states.",["United Provinces of Central America"])
E("united-provinces-rio-de-la-plata","United Provinces of the Rio de la Plata","polity",1810,1831,False,"Argentina","Post-revolutionary confederation that declared independence at Tucuman in 1816 amid unitarian-federalist civil war.",[])
E("may-revolution","May Revolution","event",1810,1810,False,"Argentina","Buenos Aires cabildo abierto deposed the viceroy, beginning Argentine self-government.",["Revolucion de Mayo"])
E("argentine-independence-1816","Argentine Declaration of Independence","event",1816,1816,False,"Argentina","Congress of Tucuman declared independence from Spain on 9 July 1816.",[])
E("rosas-regime","Rule of Juan Manuel de Rosas","reign",1829,1852,False,"Argentina","Federalist caudillo who dominated the Argentine Confederation until defeat at Caseros.",[])
E("argentine-republic","Argentine Republic","polity",1853,None,True,"Argentina","Federal republic constituted in 1853, transformed by mass European immigration and the grain and beef export boom.",["Argentina"])
E("argentine-conquest-of-the-desert","Conquest of the Desert","event",1878,1885,False,"Argentina","Military campaigns that seized Indigenous Patagonian lands and opened them to settlement.",["Campana del Desierto"])
E("peronism","Peronism","era",1946,None,True,"Argentina","Mass movement founded by Juan and Eva Peron combining labour rights, nationalism and personalist leadership.",["Justicialism","Juan Peron"])
E("argentine-dirty-war","Argentine Dirty War","event",1976,1983,False,"Argentina","Military junta's campaign of disappearances that killed up to 30,000 people.",["National Reorganization Process","Proceso"])
E("falklands-war","Falklands War","event",1982,1982,False,"Argentina and South Atlantic","Argentine invasion of the Falklands defeated by Britain, precipitating the junta's collapse.",["Guerra de las Malvinas"])
E("argentine-2001-crisis","Argentine Economic Crisis of 2001","event",2001,2002,False,"Argentina","Default, corralito bank freeze and five presidents in two weeks.",[])
E("captaincy-general-of-chile","Captaincy General of Chile","polity",1541,1818,False,"Chile","Spanish colony hemmed in by Mapuche resistance beyond the Bio-Bio river.",[])
E("chilean-war-of-independence","Chilean War of Independence","event",1810,1826,False,"Chile","Patria Vieja, reconquest and final liberation by San Martin and O'Higgins at Chacabuco and Maipu.",[])
E("republic-of-chile","Republic of Chile","polity",1818,None,True,"Chile","South American republic stabilised by Portales's 1833 constitution, later shaped by nitrates, copper and the Pinochet era.",["Chile"])
E("war-of-the-pacific","War of the Pacific","event",1879,1883,False,"South America","Chile defeated Peru and Bolivia, taking nitrate provinces and leaving Bolivia landlocked.",["Saltpeter War"])
E("occupation-of-araucania","Occupation of Araucania","event",1861,1883,False,"Chile","Chilean military conquest of Mapuche territory south of the Bio-Bio.",[])
E("allende-presidency","Presidency of Salvador Allende","reign",1970,1973,False,"Chile","First elected Marxist president, who nationalised copper and was overthrown in the 11 September 1973 coup.",[])
E("pinochet-dictatorship","Pinochet Dictatorship","polity",1973,1990,False,"Chile","Military regime with over 3,000 killed and tens of thousands tortured, alongside radical free-market reform.",["Augusto Pinochet"])
E("republic-of-peru","Republic of Peru","polity",1821,None,True,"Peru","Andean republic independent from 1821, shaped by guano and nitrate booms, military rule and the Shining Path conflict.",["Peru"])
E("shining-path-conflict","Shining Path Insurgency","event",1980,2000,False,"Peru","Maoist insurgency and state counterinsurgency that killed about 70,000 people.",["Sendero Luminoso"])
E("fujimori-regime","Fujimori Government","reign",1990,2000,False,"Peru","Alberto Fujimori defeated hyperinflation and Sendero but ruled by self-coup and corruption.",[])
E("republic-of-colombia","Republic of Colombia","polity",1831,None,True,"Colombia","Andean-Caribbean republic, successor to New Granada, marked by two-party civil wars and a long internal conflict.",["Colombia","New Granada"])
E("thousand-days-war","Thousand Days' War","event",1899,1902,False,"Colombia","Liberal-Conservative civil war that killed some 100,000 and preceded Panama's secession.",[])
E("la-violencia","La Violencia","event",1948,1958,False,"Colombia","Partisan civil conflict triggered by Gaitan's assassination and the Bogotazo, killing about 200,000.",["Bogotazo"])
E("colombian-armed-conflict","Colombian Armed Conflict","event",1964,None,True,"Colombia","Long war among FARC, ELN, paramilitaries, cartels and the state, partly ended by the 2016 peace accord.",["FARC conflict"])
E("colombian-peace-agreement","Colombian Peace Agreement","event",2016,2016,False,"Colombia","Havana accord that demobilised the FARC and won Santos the Nobel Peace Prize.",[])
E("republic-of-venezuela","Republic of Venezuela","polity",1830,None,True,"Venezuela","Caribbean-Andean republic that left Gran Colombia in 1830, later transformed by oil and by Chavismo.",["Venezuela"])
E("venezuelan-declaration-1811","Venezuelan Declaration of Independence","event",1811,1811,False,"Venezuela","First Venezuelan republic declared independence on 5 July 1811; it soon fell, beginning years of war.",[])
E("gomez-dictatorship","Dictatorship of Juan Vicente Gomez","reign",1908,1935,False,"Venezuela","Long personal rule during which oil made Venezuela a major exporter.",[])
E("venezuelan-punto-fijo","Punto Fijo Democracy","period",1958,1998,False,"Venezuela","Forty years of two-party democracy funded by oil, collapsing after the 1989 Caracazo riots.",[])
E("chavez-presidency","Presidency of Hugo Chavez","reign",1999,2013,False,"Venezuela","Bolivarian Revolution: new constitution, oil-funded social missions and confrontation with the United States.",["Chavismo"])
E("maduro-presidency","Presidency of Nicolas Maduro","reign",2013,None,True,"Venezuela","Rule marked by economic collapse, hyperinflation, disputed elections and the emigration of millions.",[])
E("republic-of-bolivia","Plurinational State of Bolivia","polity",1825,None,True,"Bolivia","Andean republic named for Bolivar, which lost its coast and Chaco lands and elected its first Indigenous president in 2005.",["Bolivia"])
E("chaco-war","Chaco War","event",1932,1935,False,"South America","Bolivia-Paraguay war over the Gran Chaco, won largely by Paraguay at great cost to both.",[])
E("bolivian-national-revolution","Bolivian National Revolution","event",1952,1952,False,"Bolivia","MNR revolution that nationalised tin, enfranchised Indigenous people and redistributed land.",[])
E("morales-presidency","Presidency of Evo Morales","reign",2006,2019,False,"Bolivia","First Indigenous president: gas nationalisation, a plurinational constitution, and resignation amid disputed re-election.",[])
E("republic-of-ecuador","Republic of Ecuador","polity",1830,None,True,"Ecuador","Andean-Pacific republic that left Gran Colombia in 1830; oil-exporting and dollarised since 2000.",["Ecuador"])
E("republic-of-paraguay","Republic of Paraguay","polity",1811,None,True,"Paraguay","Landlocked republic independent from 1811, devastated in the Triple Alliance war and ruled by Stroessner for 35 years.",["Paraguay"])
E("stroessner-regime","Stroessner Dictatorship","reign",1954,1989,False,"Paraguay","Alfredo Stroessner's anticommunist regime, the longest in 20th-century South America.",[])
E("oriental-republic-of-uruguay","Oriental Republic of Uruguay","polity",1828,None,True,"Uruguay","Buffer republic created by British mediation between Brazil and Argentina, later a pioneering welfare democracy.",["Uruguay","Banda Oriental"])
E("uruguayan-dictatorship","Uruguayan Military Dictatorship","polity",1973,1985,False,"Uruguay","Civil-military regime that imprisoned and tortured on a mass scale after the Tupamaro insurgency.",[])
E("republic-of-guyana","Republic of Guyana","polity",1966,None,True,"Guyana","Former British Guiana, independent in 1966 and transformed by offshore oil since 2019.",["Guyana","British Guiana"])
E("republic-of-suriname","Republic of Suriname","polity",1975,None,True,"Suriname","Former Dutch Guiana, independent in 1975, with large emigration to the Netherlands.",["Suriname","Dutch Guiana"])
E("french-guiana","French Guiana","polity",1664,None,True,"France in the Americas","French territory and now overseas department, once a penal colony and now home to the Kourou spaceport.",["Guyane"])

# ---------------- CARIBBEAN & CENTRAL AMERICA ----------------
E("saint-domingue","Saint-Domingue","polity",1659,1804,False,"Haiti","France's richest colony, producing sugar and coffee with enslaved labour on a vast scale, destroyed by revolution.",[])
E("haitian-revolution","Haitian Revolution","event",1791,1804,False,"Haiti","Only successful large-scale slave revolt, which defeated French, Spanish and British forces and created Haiti.",[])
E("toussaint-louverture","Leadership of Toussaint Louverture","reign",1794,1802,False,"Haiti","Former slave who became governor of Saint-Domingue, abolished slavery and died in French captivity.",["Toussaint L'Ouverture"])
E("haitian-independence","Haitian Declaration of Independence","event",1804,1804,False,"Haiti","Dessalines proclaimed independence on 1 January 1804, the first Black republic and second American republic.",[])
E("republic-of-haiti","Republic of Haiti","polity",1804,None,True,"Haiti","Independent since 1804, burdened by the French indemnity, US occupation, dictatorship and repeated state collapse.",["Haiti","Ayiti"])
E("us-occupation-of-haiti","United States Occupation of Haiti","period",1915,1934,False,"Haiti","Nineteen-year American military rule that rewrote Haitian law and finances.",[])
E("duvalier-regime","Duvalier Regime","reign",1957,1986,False,"Haiti","Francois 'Papa Doc' and Jean-Claude 'Baby Doc' Duvalier ruled with the Tontons Macoutes for 29 years.",[])
E("haiti-earthquake-2010","2010 Haiti Earthquake","event",2010,2010,False,"Haiti","Magnitude 7.0 quake near Port-au-Prince that killed well over 100,000 people.",[])
E("dominican-republic","Dominican Republic","polity",1844,None,True,"Dominican Republic","Independent from Haiti in 1844, later occupied by the United States and ruled by Trujillo for three decades.",["Santo Domingo"])
E("trujillo-regime","Trujillo Dictatorship","reign",1930,1961,False,"Dominican Republic","Rafael Trujillo's cult-of-personality regime, responsible for the 1937 Parsley Massacre of Haitians.",[])
E("spanish-cuba","Spanish Cuba","polity",1511,1898,False,"Cuba","Spain's sugar and tobacco colony and last major American possession, lost in 1898.",[])
E("cuban-ten-years-war","Ten Years' War","event",1868,1878,False,"Cuba","First Cuban war of independence, ending in the Pact of Zanjon without independence.",[])
E("cuban-war-of-independence","Cuban War of Independence","event",1895,1898,False,"Cuba","Marti- and Maceo-led revolt that drew in the United States and ended Spanish rule.",[])
E("republic-of-cuba","Republic of Cuba","polity",1902,None,True,"Cuba","Cuban republic from 1902, under the Platt Amendment, then Batista, then communist rule since 1959.",["Cuba"])
E("batista-regime","Batista Regime","reign",1952,1958,False,"Cuba","Fulgencio Batista's corrupt dictatorship, overthrown by the 26th of July Movement.",[])
E("cuban-revolution","Cuban Revolution","event",1953,1959,False,"Cuba","Castro and Guevara's guerrilla campaign that took Havana on 1 January 1959.",[])
E("fidel-castro-rule","Rule of Fidel Castro","reign",1959,2008,False,"Cuba","Nearly half a century leading communist Cuba through nationalisation, Soviet alliance and US embargo.",["Fidel Castro"])
E("bay-of-pigs","Bay of Pigs Invasion","event",1961,1961,False,"Cuba","Failed CIA-backed exile landing at Playa Giron.",["Playa Giron"])
E("cuban-missile-crisis","Cuban Missile Crisis","event",1962,1962,False,"Cuba and the Cold War","Thirteen-day superpower confrontation over Soviet missiles in Cuba, the closest approach to nuclear war.",[])
E("cuban-special-period","Special Period","period",1991,2000,False,"Cuba","Severe economic crisis after Soviet subsidies ended, forcing rationing and limited market openings.",["Periodo Especial"])
E("raul-castro-rule","Presidency of Raul Castro","reign",2008,2018,False,"Cuba","Cautious economic liberalisation and the 2015 restoration of relations with the United States.",[])
E("puerto-rico-commonwealth","Commonwealth of Puerto Rico","polity",1898,None,True,"Puerto Rico","Spanish colony ceded to the United States in 1898, an unincorporated territory with commonwealth status since 1952.",["Puerto Rico","Borinquen"])
E("jamaica","Jamaica","polity",1962,None,True,"Jamaica","Former Spanish then British sugar colony, independent within the Commonwealth since 1962.",[])
E("haitian-british-jamaica","British Jamaica","polity",1655,1962,False,"Jamaica","English conquest of 1655 created a plantation colony with maroon wars and the 1865 Morant Bay rebellion.",[])
E("trinidad-and-tobago","Trinidad and Tobago","polity",1962,None,True,"Trinidad and Tobago","Oil- and gas-rich Caribbean state independent in 1962 and a republic since 1976.",[])
E("republic-of-panama","Republic of Panama","polity",1903,None,True,"Panama","Seceded from Colombia with US backing in 1903; the canal returned to Panamanian control in 1999.",["Panama"])
E("panama-canal","Panama Canal","event",1904,1914,False,"Panama","American-built interoceanic canal opened in 1914 after the failure of the French attempt.",[])
E("us-invasion-of-panama","United States Invasion of Panama","event",1989,1990,False,"Panama","Operation Just Cause removed Manuel Noriega from power.",[])
E("republic-of-costa-rica","Republic of Costa Rica","polity",1838,None,True,"Costa Rica","Central American republic that abolished its army in 1949 and became the region's most stable democracy.",["Costa Rica"])
E("republic-of-nicaragua","Republic of Nicaragua","polity",1838,None,True,"Nicaragua","Central American republic shaped by US intervention, the Somoza dynasty and Sandinista rule.",["Nicaragua"])
E("somoza-dynasty","Somoza Dynasty","reign",1936,1979,False,"Nicaragua","Family dictatorship backed by the National Guard and the United States, overthrown by the Sandinistas.",[])
E("sandinista-revolution","Sandinista Revolution","event",1979,1979,False,"Nicaragua","FSLN insurrection that toppled Somoza and led to a decade of revolution and Contra war.",["FSLN"])
E("contra-war","Contra War","event",1981,1990,False,"Nicaragua","US-backed counter-revolutionary insurgency against the Sandinista government, tied to the Iran-Contra affair.",[])
E("republic-of-el-salvador","Republic of El Salvador","polity",1841,None,True,"El Salvador","Central American republic marked by the 1932 Matanza, a brutal civil war and postwar gang violence.",["El Salvador"])
E("salvadoran-civil-war","Salvadoran Civil War","event",1979,1992,False,"El Salvador","Twelve-year war between the US-backed government and the FMLN that killed some 75,000 people.",[])
E("republic-of-guatemala","Republic of Guatemala","polity",1839,None,True,"Guatemala","Central American republic of the 1944 October Revolution, the 1954 coup and a genocidal civil war.",["Guatemala"])
E("guatemalan-coup-1954","Guatemalan Coup of 1954","event",1954,1954,False,"Guatemala","CIA-organised overthrow of Jacobo Arbenz after his land reform threatened United Fruit.",["Operation PBSuccess"])
E("guatemalan-civil-war","Guatemalan Civil War","event",1960,1996,False,"Guatemala","Thirty-six-year conflict with about 200,000 dead, including genocide against Maya communities.",[])
E("republic-of-honduras","Republic of Honduras","polity",1838,None,True,"Honduras","Central American republic long dominated by banana companies and by military politics.",["Honduras"])
E("belize","Belize","polity",1981,None,True,"Belize","Former British Honduras, independent in 1981, the only English-speaking state in Central America.",["British Honduras"])
E("bahamas","Commonwealth of The Bahamas","polity",1973,None,True,"The Bahamas","Archipelagic state independent from Britain in 1973.",["Bahamas"])
E("barbados","Barbados","polity",1966,None,True,"Barbados","Independent since 1966 and a republic since 2021, once a model English sugar colony.",[])
E("caricom","Caribbean Community","polity",1973,None,True,"Caribbean","Regional integration organisation founded by the Treaty of Chaguaramas.",["CARICOM"])
E("caribbean-slavery-abolition","Abolition of Slavery in the Caribbean","era",1793,1886,False,"Caribbean","Successive emancipations from Haiti and the British colonies to Cuba, ending Atlantic plantation slavery.",[])
E("atlantic-slave-trade","Atlantic Slave Trade","era",1500,1867,False,"Atlantic world","Forced transport of roughly 12.5 million Africans to the Americas, the foundation of the plantation economies.",["transatlantic slave trade"],"high","global")
E("columbian-exchange","Columbian Exchange","era",1492,1800,False,"Atlantic world","Transfer of crops, animals, people and diseases between hemispheres that reshaped world population and diets.",[],"high","global")
E("american-indigenous-demographic-collapse","Indigenous Demographic Collapse in the Americas","era",1492,1650,False,"The Americas","Epidemics, war and forced labour killed a large majority of the pre-contact Indigenous population.",["Great Dying"])
