import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _mn_common import E, ROWS, set_region
set_region('south-asia')

# ---------------- SOUTH ASIA ----------------
E("mughal-empire","Mughal Empire","polity",1526,1857,False,"India","Timurid Muslim empire that ruled most of South Asia at its height and declined into a British-protected shell.",["Mughals","Mogul Empire"])
E("reign-babur","Reign of Babur","reign",1526,1530,False,"Mughal Empire","Founder of the Mughal Empire, victorious at Panipat over the Delhi Sultanate.",[])
E("reign-akbar","Reign of Akbar","reign",1556,1605,False,"Mughal Empire","Expanded and consolidated the empire, integrated Rajputs and pursued religious pluralism and the din-i ilahi.",["Akbar the Great"])
E("reign-jahangir","Reign of Jahangir","reign",1605,1627,False,"Mughal Empire","Reign of court painting, Nur Jahan's influence and the first English embassy.",[])
E("reign-shah-jahan","Reign of Shah Jahan","reign",1628,1658,False,"Mughal Empire","Builder of the Taj Mahal and Shahjahanabad, deposed by his son Aurangzeb.",[])
E("reign-aurangzeb","Reign of Aurangzeb","reign",1658,1707,False,"Mughal Empire","Expanded the empire to its greatest extent while exhausting it in the Deccan wars.",["Alamgir"])
E("maratha-empire","Maratha Empire","polity",1674,1818,False,"India","Hindu power founded by Shivaji that displaced the Mughals across much of India before defeat by the British.",["Maratha Confederacy"])
E("shivaji-reign","Reign of Shivaji","reign",1674,1680,False,"Maratha Empire","Founder-king who built a Maratha state through guerrilla war against the Mughals and Bijapur.",[])
E("third-battle-of-panipat","Third Battle of Panipat","event",1761,1761,False,"India","Afghan victory over the Marathas that crippled the leading Indian power and eased British expansion.",[])
E("sikh-empire","Sikh Empire","polity",1799,1849,False,"Punjab","Ranjit Singh's Punjab state, which annexed Kashmir and Peshawar and fell in the Anglo-Sikh Wars.",["Khalsa Raj"])
E("kingdom-of-mysore","Kingdom of Mysore","polity",1565,1947,False,"India","South Indian state whose rulers Haidar Ali and Tipu Sultan fought four wars against the British.",["Tipu Sultan"])
E("east-india-company-rule","East India Company Rule in India","polity",1757,1858,False,"India","Company government from Plassey to the Crown takeover, extended by conquest, subsidiary alliances and revenue farming.",["Company Raj","EIC"])
E("battle-of-plassey","Battle of Plassey","event",1757,1757,False,"India","Clive's victory in Bengal that began British territorial power in India.",[])
E("bengal-famine-1770","Great Bengal Famine of 1770","event",1769,1770,False,"India","Famine under early Company rule that killed several million Bengalis.",[])
E("anglo-mysore-wars","Anglo-Mysore Wars","event",1767,1799,False,"India","Four wars ending with the death of Tipu Sultan at Seringapatam.",[])
E("anglo-maratha-wars","Anglo-Maratha Wars","event",1775,1818,False,"India","Three wars that destroyed Maratha power and made the Company paramount in India.",[])
E("indian-rebellion-1857","Indian Rebellion of 1857","event",1857,1858,False,"India","Mass revolt of sepoys and princes that ended Company rule and the Mughal dynasty.",["Sepoy Mutiny","First War of Independence"])
E("british-raj","British Raj","polity",1858,1947,False,"South Asia","Crown rule over India, Burma and adjacent territories, with railways, famines, nationalism and partition.",["British India","Indian Empire"])
E("indian-national-congress-founding","Founding of the Indian National Congress","event",1885,1885,False,"India","First all-India nationalist organisation, later the vehicle of the independence movement.",["INC"])
E("bengal-partition-1905","Partition of Bengal (1905)","event",1905,1911,False,"India","Curzon's division of Bengal, reversed after the swadeshi agitation it provoked.",[])
E("all-india-muslim-league","All-India Muslim League","polity",1906,1947,False,"South Asia","Party founded in Dhaka that under Jinnah demanded and won Pakistan.",["Muslim League"])
E("jallianwala-bagh-massacre","Jallianwala Bagh Massacre","event",1919,1919,False,"India","British troops fired on a crowd in Amritsar, killing hundreds and radicalising Indian opinion.",["Amritsar massacre"])
E("non-cooperation-movement","Non-Cooperation Movement","event",1920,1922,False,"India","Gandhi's first mass satyagraha, boycotting British schools, courts and goods.",[])
E("salt-march","Salt March","event",1930,1930,False,"India","Gandhi's 385-kilometre march to Dandi against the salt tax, launching civil disobedience.",["Dandi March"])
E("quit-india-movement","Quit India Movement","event",1942,1942,False,"India","Congress demand for immediate independence, met by mass arrests and repression.",[])
E("bengal-famine-1943","Bengal Famine of 1943","event",1943,1944,False,"India","Wartime famine that killed some three million people in Bengal.",[])
E("partition-of-india","Partition of India","event",1947,1947,False,"South Asia","Division into India and Pakistan on 15 August 1947, with up to two million deaths and 15 million displaced.",["Independence and Partition"])
E("dominion-of-india","Dominion of India","polity",1947,1950,False,"India","Independent India under the crown until the republican constitution took effect.",[])
E("republic-of-india","Republic of India","polity",1950,None,True,"India","World's largest democracy, a federal republic under the 1950 constitution and the most populous country since 2023.",["India","Bharat"])
E("indian-constitution-1950","Indian Constitution","event",1950,1950,False,"India","Ambedkar-led constitution effective 26 January 1950, abolishing untouchability and creating a secular federal republic.",[])
E("nehru-premiership","Premiership of Jawaharlal Nehru","reign",1947,1964,False,"India","Founding prime minister: planning, non-alignment, states reorganisation and the 1962 war with China.",[])
E("indian-integration-of-princely-states","Integration of the Princely States","event",1947,1949,False,"India","Accession of over 500 princely states, including Hyderabad's forcible annexation.",["Operation Polo"])
E("first-kashmir-war","First Kashmir War","event",1947,1948,False,"India and Pakistan","War over Kashmir after the maharaja's accession to India, ending with the ceasefire line.",[])
E("sino-indian-war","Sino-Indian War","event",1962,1962,False,"India and China","Chinese victory in the Himalayan border war that shattered Nehru's China policy.",[])
E("indo-pakistani-war-1965","Indo-Pakistani War of 1965","event",1965,1965,False,"India and Pakistan","Second war over Kashmir, ended by the Soviet-brokered Tashkent Declaration.",[])
E("indira-gandhi-premiership","Premiership of Indira Gandhi","reign",1966,1984,False,"India","Prime minister 1966-77 and 1980-84: bank nationalisation, the 1971 war, the Emergency and her assassination.",[])
E("indian-emergency","The Emergency","period",1975,1977,False,"India","Twenty-one months of suspended civil liberties, press censorship and forced sterilisation under Indira Gandhi.",[])
E("operation-blue-star","Operation Blue Star","event",1984,1984,False,"India","Army assault on the Golden Temple against Sikh militants, followed by Indira Gandhi's assassination and anti-Sikh pogroms.",[])
E("indian-economic-liberalisation","Indian Economic Liberalisation","event",1991,1991,False,"India","Balance-of-payments crisis reforms under Rao and Manmohan Singh that opened the economy.",[])
E("indian-nuclear-tests","Indian and Pakistani Nuclear Tests","event",1998,1998,False,"South Asia","Pokhran-II and Chagai tests made both states declared nuclear powers.",["Pokhran-II"])
E("kargil-war","Kargil War","event",1999,1999,False,"India and Pakistan","High-altitude conflict after Pakistani infiltration into Indian-held Kashmir.",[])
E("modi-premiership","Premiership of Narendra Modi","reign",2014,None,True,"India","BJP prime minister: demonetisation, GST, abrogation of Article 370 and Hindu-nationalist consolidation.",[])
E("dominion-of-pakistan","Dominion of Pakistan","polity",1947,1956,False,"Pakistan","Independent Pakistan under the crown, founded by Jinnah as a homeland for South Asian Muslims.",[])
E("islamic-republic-of-pakistan","Islamic Republic of Pakistan","polity",1956,None,True,"Pakistan","Republic since 1956, alternating between civilian and military rule, nuclear-armed since 1998.",["Pakistan"])
E("jinnah-leadership","Leadership of Muhammad Ali Jinnah","reign",1947,1948,False,"Pakistan","Quaid-i-Azam and founder of Pakistan, its first governor-general.",[])
E("ayub-khan-rule","Rule of Ayub Khan","reign",1958,1969,False,"Pakistan","First military ruler: the Decade of Development, the 1965 war and Islamabad's construction.",[])
E("zulfikar-bhutto-rule","Government of Zulfikar Ali Bhutto","reign",1971,1977,False,"Pakistan","Populist leader who wrote the 1973 constitution and began the nuclear programme; overthrown and hanged.",[])
E("zia-ul-haq-rule","Rule of Zia-ul-Haq","reign",1977,1988,False,"Pakistan","Islamising military dictatorship that backed the Afghan mujahideen; died in an air crash.",[])
E("benazir-bhutto-premierships","Premierships of Benazir Bhutto","reign",1988,1996,False,"Pakistan","First woman to lead a Muslim-majority state, twice prime minister; assassinated in 2007.",[])
E("musharraf-rule","Rule of Pervez Musharraf","reign",1999,2008,False,"Pakistan","Coup leader who allied with the US after 9/11 and resigned amid the lawyers' movement.",[])
E("bangladesh-liberation-war","Bangladesh Liberation War","event",1971,1971,False,"Bangladesh","East Pakistan's war of independence with Indian intervention, accompanied by genocide against Bengalis.",["Indo-Pakistani War of 1971"])
E("peoples-republic-of-bangladesh","People's Republic of Bangladesh","polity",1971,None,True,"Bangladesh","Independent since 1971, one of the world's most densely populated states and a garment-export power.",["Bangladesh","East Bengal"])
E("mujib-rule","Leadership of Sheikh Mujibur Rahman","reign",1971,1975,False,"Bangladesh","Founding leader assassinated with most of his family in a 1975 coup.",["Bangabandhu"])
E("hasina-premierships","Premierships of Sheikh Hasina","reign",1996,2024,False,"Bangladesh","Prime minister 1996-2001 and 2009-24, whose long rule ended in a student uprising and her flight in 2024.",[])
E("bangladesh-uprising-2024","Bangladeshi Uprising of 2024","event",2024,2024,False,"Bangladesh","Student-led protests over job quotas that toppled Sheikh Hasina's government.",[],"medium")
E("british-ceylon","British Ceylon","polity",1815,1948,False,"Sri Lanka","Crown colony after the fall of Kandy, with plantation tea and Tamil labour migration.",[])
E("dominion-of-ceylon","Dominion of Ceylon and Sri Lanka","polity",1948,None,True,"Sri Lanka","Independent in 1948, renamed Sri Lanka as a republic in 1972 after decades of communal tension.",["Sri Lanka","Ceylon"])
E("sri-lankan-civil-war","Sri Lankan Civil War","event",1983,2009,False,"Sri Lanka","Twenty-six-year war between the state and the Tamil Tigers ending in the LTTE's destruction.",["LTTE conflict"])
E("kingdom-of-nepal","Kingdom of Nepal","polity",1768,2008,False,"Nepal","Shah dynasty state unified by Prithvi Narayan Shah, long dominated by the Rana premiers.",["Gorkha Kingdom"])
E("rana-dynasty","Rana Regime","polity",1846,1951,False,"Nepal","Hereditary prime ministers who reduced the Shah kings to figureheads for a century.",[])
E("nepalese-civil-war","Nepalese Civil War","event",1996,2006,False,"Nepal","Maoist insurgency that killed some 17,000 and led to the monarchy's abolition.",["People's War"])
E("federal-republic-of-nepal","Federal Democratic Republic of Nepal","polity",2008,None,True,"Nepal","Republic declared in 2008 after the Maoist war and the 2001 royal massacre.",["Nepal"])
E("kingdom-of-bhutan","Kingdom of Bhutan","polity",1907,None,True,"Bhutan","Himalayan Wangchuck monarchy, constitutional since 2008 and known for Gross National Happiness.",["Bhutan","Druk Yul"])
E("republic-of-maldives","Republic of Maldives","polity",1965,None,True,"Maldives","Indian Ocean island state independent from Britain in 1965, a republic from 1968.",["Maldives"])
E("durrani-empire","Durrani Empire","polity",1747,1823,False,"Afghanistan","Ahmad Shah Durrani's empire stretching from Mashhad to Delhi, the foundation of modern Afghanistan.",["Afghan Empire"])
E("anglo-afghan-wars","Anglo-Afghan Wars","event",1839,1919,False,"Afghanistan","Three British wars that failed to control Afghanistan, which won full independence in 1919.",[])
E("kingdom-of-afghanistan","Kingdom of Afghanistan","polity",1926,1973,False,"Afghanistan","Monarchy under Amanullah, Nadir Shah and Zahir Shah, ended by Daoud's republican coup.",[])
E("saur-revolution","Saur Revolution","event",1978,1978,False,"Afghanistan","Communist coup that installed the PDPA and triggered rural revolt and Soviet intervention.",[])
E("soviet-afghan-war","Soviet-Afghan War","event",1979,1989,False,"Afghanistan","Nine-year Soviet occupation opposed by US- and Pakistan-backed mujahideen, ending in withdrawal.",[])
E("afghan-civil-war-1990s","Afghan Civil War of the 1990s","event",1992,2001,False,"Afghanistan","Factional war after Najibullah's fall, won largely by the Taliban from 1996.",[])
E("taliban-emirate-first","Islamic Emirate of Afghanistan (first period)","polity",1996,2001,False,"Afghanistan","Taliban rule imposing strict shari'a and sheltering al-Qaeda, ended by US-led intervention.",[])
E("us-war-in-afghanistan","United States War in Afghanistan","event",2001,2021,False,"Afghanistan","Twenty-year NATO-led war after 9/11, ending in Taliban restoration and Western withdrawal.",["Operation Enduring Freedom"])
E("islamic-republic-of-afghanistan","Islamic Republic of Afghanistan","polity",2004,2021,False,"Afghanistan","Western-backed republic under Karzai and Ghani that collapsed as US forces left.",[])
E("taliban-emirate-second","Islamic Emirate of Afghanistan (restored)","polity",2021,None,True,"Afghanistan","Taliban government since August 2021, unrecognised and enforcing severe restrictions on women.",["Taliban Afghanistan"])

# ---------------- SOUTHEAST ASIA ----------------
set_region('southeast-asia')
E("le-dynasty-late","Later Le Dynasty and Trinh-Nguyen Division","period",1533,1788,False,"Vietnam","Nominal Le kings with real power split between the Trinh lords in the north and the Nguyen in the south.",["Trinh-Nguyen war"])
E("tay-son-dynasty","Tay Son Dynasty","polity",1778,1802,False,"Vietnam","Peasant-led regime that unified Vietnam briefly and repelled a Qing invasion.",[])
E("nguyen-dynasty","Nguyen Dynasty","polity",1802,1945,False,"Vietnam","Last Vietnamese imperial dynasty, based at Hue, reduced to figureheads under French rule.",[])
E("french-indochina","French Indochina","polity",1887,1954,False,"Southeast Asia","French federation of Cochinchina, Annam, Tonkin, Cambodia and Laos, exploited for rice, rubber and taxes.",["Indochine francaise"])
E("french-conquest-of-vietnam","French Conquest of Vietnam","event",1858,1885,False,"Vietnam","Campaigns from Saigon to Tonkin that made Vietnam a French colony and protectorates.",[])
E("japanese-occupation-indochina","Japanese Occupation of Indochina","period",1940,1945,False,"Southeast Asia","Japanese control alongside Vichy French administration, ending in the 1945 coup and Vietnamese famine.",[])
E("august-revolution-vietnam","Vietnamese August Revolution","event",1945,1945,False,"Vietnam","Viet Minh seizure of power and Ho Chi Minh's declaration of the Democratic Republic of Vietnam.",[])
E("first-indochina-war","First Indochina War","event",1946,1954,False,"Southeast Asia","Viet Minh war against France that ended with Dien Bien Phu and the Geneva Accords.",[])
E("battle-of-dien-bien-phu","Battle of Dien Bien Phu","event",1954,1954,False,"Vietnam","Viet Minh victory over the French garrison that ended French rule in Indochina.",[])
E("geneva-accords-1954","Geneva Accords","event",1954,1954,False,"Southeast Asia","Agreements partitioning Vietnam at the 17th parallel and recognising Laotian and Cambodian independence.",[])
E("north-vietnam","Democratic Republic of Vietnam","polity",1945,1976,False,"Vietnam","Communist northern state under Ho Chi Minh, which won the war and unified the country in 1976.",["North Vietnam"])
E("south-vietnam","Republic of Vietnam","polity",1955,1975,False,"Vietnam","Anti-communist southern state under Diem then Thieu, which collapsed with the fall of Saigon.",["South Vietnam"])
E("ho-chi-minh-leadership","Leadership of Ho Chi Minh","reign",1945,1969,False,"Vietnam","Founder of Vietnamese communism and president of North Vietnam until his death.",[])
E("vietnam-war","Vietnam War","event",1955,1975,False,"Southeast Asia","War between North and South Vietnam with massive American involvement, ending in communist victory.",["Second Indochina War","American War"])
E("tet-offensive","Tet Offensive","event",1968,1968,False,"Vietnam","Coordinated communist attacks that failed militarily but broke American public support for the war.",[])
E("fall-of-saigon","Fall of Saigon","event",1975,1975,False,"Vietnam","North Vietnamese capture of Saigon on 30 April 1975 ended the war.",[])
E("socialist-republic-of-vietnam","Socialist Republic of Vietnam","polity",1976,None,True,"Vietnam","Unified communist state since 1976, market-reforming since doi moi in 1986.",["Vietnam"])
E("doi-moi","Doi Moi","era",1986,None,True,"Vietnam","Market-oriented reforms that transformed Vietnam into a fast-growing export economy.",["Vietnamese economic renovation"])
E("kingdom-of-cambodia-french","French Protectorate of Cambodia","polity",1863,1953,False,"Cambodia","Norodom's kingdom under French protection within Indochina.",[])
E("kingdom-of-cambodia-1953","Kingdom of Cambodia (1953-1970)","polity",1953,1970,False,"Cambodia","Sihanouk's independent, neutralist kingdom, ended by Lon Nol's coup.",[])
E("khmer-republic","Khmer Republic","polity",1970,1975,False,"Cambodia","US-aligned republic under Lon Nol, defeated by the Khmer Rouge.",[])
E("khmer-rouge-regime","Democratic Kampuchea","polity",1975,1979,False,"Cambodia","Khmer Rouge regime under Pol Pot that emptied the cities and killed some 1.7 to 2 million people.",["Khmer Rouge","Pol Pot regime"])
E("cambodian-genocide","Cambodian Genocide","event",1975,1979,False,"Cambodia","Mass killing, starvation and forced labour under the Khmer Rouge, about a quarter of the population.",["Killing Fields"])
E("vietnamese-occupation-cambodia","Vietnamese Intervention in Cambodia","event",1978,1989,False,"Cambodia","Vietnamese invasion that ousted the Khmer Rouge and installed the People's Republic of Kampuchea.",[])
E("untac","UN Transitional Authority in Cambodia","polity",1992,1993,False,"Cambodia","UN administration that organised elections and restored the monarchy.",["UNTAC"])
E("kingdom-of-cambodia-modern","Kingdom of Cambodia","polity",1993,None,True,"Cambodia","Restored constitutional monarchy, dominated politically by Hun Sen and his family since 1985.",["Cambodia"])
E("kingdom-of-laos","Kingdom of Laos","polity",1953,1975,False,"Laos","Independent kingdom torn by civil war and the Vietnam War's spillover bombing.",[])
E("lao-pdr","Lao People's Democratic Republic","polity",1975,None,True,"Laos","Communist state proclaimed after the Pathet Lao victory, the world's most heavily bombed country per capita.",["Laos"])
E("laotian-civil-war","Laotian Civil War","event",1959,1975,False,"Laos","Pathet Lao and North Vietnamese struggle against royalists, with a massive covert US air campaign.",["Secret War"])
E("toungoo-dynasty","Toungoo Dynasty","polity",1510,1752,False,"Myanmar","Burmese dynasty that briefly built Southeast Asia's largest empire under Bayinnaung.",[])
E("konbaung-dynasty","Konbaung Dynasty","polity",1752,1885,False,"Myanmar","Last Burmese dynasty, which invaded Siam and Assam and lost three wars to Britain.",[])
E("anglo-burmese-wars","Anglo-Burmese Wars","event",1824,1885,False,"Myanmar","Three wars ending in the annexation of all Burma to British India.",[])
E("british-burma","British Burma","polity",1824,1948,False,"Myanmar","Province of British India until 1937 and then a separate colony, occupied by Japan in 1942-45.",[])
E("union-of-burma","Union of Burma and Myanmar","polity",1948,None,True,"Myanmar","Independent from Britain in 1948, under military rule for most of its history and renamed Myanmar in 1989.",["Myanmar","Burma"])
E("ne-win-regime","Rule of Ne Win","reign",1962,1988,False,"Myanmar","Coup leader whose Burmese Way to Socialism isolated and impoverished the country.",[])
E("burmese-1988-uprising","Burmese Uprising of 1988","event",1988,1988,False,"Myanmar","Nationwide pro-democracy protests crushed by the army, which then formed the SLORC junta.",["8888 Uprising"])
E("aung-san-suu-kyi-era","Political Career of Aung San Suu Kyi","reign",1988,2021,False,"Myanmar","Nobel laureate held under house arrest for 15 years, later state counsellor and detained again in 2021.",[])
E("rohingya-crisis","Rohingya Crisis","event",2016,None,True,"Myanmar","Military campaigns that drove over 700,000 Rohingya into Bangladesh, alleged as genocide.",[])
E("myanmar-coup-2021","Myanmar Coup of 2021","event",2021,None,True,"Myanmar","Military seizure of power that sparked nationwide armed resistance and civil war.",[])
E("ayutthaya-kingdom-late","Late Ayutthaya Kingdom","period",1500,1767,False,"Thailand","Siamese kingdom of great wealth and cosmopolitan trade, destroyed by the Burmese in 1767.",["Siam"])
E("thonburi-kingdom","Thonburi Kingdom","polity",1767,1782,False,"Thailand","Taksin's brief reunification of Siam after the fall of Ayutthaya.",[])
E("chakri-dynasty","Chakri Dynasty","polity",1782,None,True,"Thailand","Bangkok dynasty that preserved Siamese independence through the colonial era and still reigns.",["Rattanakosin"])
E("reign-mongkut","Reign of Mongkut","reign",1851,1868,False,"Thailand","Rama IV opened Siam to Western trade and diplomacy while preserving sovereignty.",["Rama IV"])
E("reign-chulalongkorn","Reign of Chulalongkorn","reign",1868,1910,False,"Thailand","Rama V abolished slavery, modernised administration and ceded border lands to keep Siam independent.",["Rama V"])
E("siamese-revolution-1932","Siamese Revolution of 1932","event",1932,1932,False,"Thailand","Bloodless coup that ended absolute monarchy and created a constitutional system dominated by the military.",[])
E("kingdom-of-thailand","Kingdom of Thailand","polity",1932,None,True,"Thailand","Constitutional monarchy renamed Thailand in 1939, with a modern history of frequent military coups.",["Thailand","Siam"])
E("reign-bhumibol","Reign of Bhumibol Adulyadej","reign",1946,2016,False,"Thailand","Rama IX reigned seventy years, becoming a unifying symbol through repeated coups.",["Rama IX"])
E("reign-vajiralongkorn","Reign of Vajiralongkorn","reign",2016,None,True,"Thailand","Rama X, king since 2016, whose reign has seen youth protests over royal reform.",["Rama X"])
E("malacca-sultanate-fall","Portuguese Conquest of Malacca","event",1511,1511,False,"Malaysia","Albuquerque's capture of Malacca gave Portugal control of a key Asian trade chokepoint.",[])
E("straits-settlements","Straits Settlements","polity",1826,1946,False,"Malaysia and Singapore","British colony of Penang, Malacca and Singapore, the hub of colonial commerce in the region.",[])
E("british-malaya","British Malaya","polity",1874,1957,False,"Malaysia","Federated and unfederated Malay states under British protection, built on tin and rubber.",[])
E("malayan-emergency","Malayan Emergency","event",1948,1960,False,"Malaysia","British counterinsurgency against the Malayan Communist Party using resettlement and 'new villages'.",[])
E("federation-of-malaya","Federation of Malaya","polity",1957,1963,False,"Malaysia","Independent Malaya from 31 August 1957 under Tunku Abdul Rahman.",["Merdeka"])
E("malaysia","Malaysia","polity",1963,None,True,"Malaysia","Federation formed in 1963 with Sabah, Sarawak and briefly Singapore; a rotating elective monarchy.",[])
E("singapore-separation","Separation of Singapore from Malaysia","event",1965,1965,False,"Singapore","Singapore was expelled from the federation and became an independent republic on 9 August 1965.",[])
E("republic-of-singapore","Republic of Singapore","polity",1965,None,True,"Singapore","City-state that grew from an entrepot to a global financial hub under Lee Kuan Yew's People's Action Party.",["Singapore"])
E("lee-kuan-yew-premiership","Premiership of Lee Kuan Yew","reign",1959,1990,False,"Singapore","Founding prime minister for 31 years who built a developmental, one-party-dominant state.",[])
E("brunei","Brunei Darussalam","polity",1984,None,True,"Brunei","Oil-rich Malay Islamic sultanate fully independent from Britain in 1984.",["Brunei"])
E("dutch-east-indies","Dutch East Indies","polity",1800,1949,False,"Indonesia","Dutch colonial state built on the VOC's ruins, exploiting sugar, coffee, oil and the cultivation system.",["Nederlands-Indie"])
E("java-war","Java War","event",1825,1830,False,"Indonesia","Diponegoro's revolt against Dutch rule, ending in his exile and the cultivation system.",[])
E("aceh-war","Aceh War","event",1873,1904,False,"Indonesia","Long Dutch war to subdue the Aceh sultanate, one of the colonial era's most costly campaigns.",[])
E("indonesian-national-awakening","Indonesian National Awakening","era",1908,1945,False,"Indonesia","Rise of nationalist organisations from Budi Utomo to Sukarno's PNI and the 1928 Youth Pledge.",[])
E("japanese-occupation-indonesia","Japanese Occupation of the Dutch East Indies","period",1942,1945,False,"Indonesia","Three years of Japanese rule that destroyed Dutch authority and armed Indonesian nationalists.",[])
E("indonesian-national-revolution","Indonesian National Revolution","event",1945,1949,False,"Indonesia","Four-year struggle after the 17 August 1945 proclamation that forced Dutch recognition of independence.",[])
E("republic-of-indonesia","Republic of Indonesia","polity",1945,None,True,"Indonesia","World's largest archipelagic state and largest Muslim-majority country, independent since 1945.",["Indonesia"])
E("sukarno-presidency","Presidency of Sukarno","reign",1945,1967,False,"Indonesia","Founding president: Pancasila, Bandung Conference, Guided Democracy and confrontation with Malaysia.",[])
E("bandung-conference","Bandung Conference","event",1955,1955,False,"Asia and Africa","First large Asian-African conference, a founding moment of Third World solidarity and non-alignment.",[])
E("indonesian-killings-1965","Indonesian Mass Killings of 1965-66","event",1965,1966,False,"Indonesia","Army-led massacre of at least half a million alleged communists after a failed coup.",["30 September Movement"])
E("suharto-new-order","New Order","polity",1967,1998,False,"Indonesia","Suharto's authoritarian developmental regime, ended by the Asian financial crisis and mass protest.",["Suharto"])
E("indonesian-reformasi","Reformasi","era",1998,None,True,"Indonesia","Democratisation after Suharto's fall, with decentralisation and direct presidential elections.",[])
E("east-timor-indonesian-occupation","Indonesian Occupation of East Timor","period",1975,1999,False,"East Timor","Invasion and annexation after Portuguese withdrawal, with perhaps 100,000 to 200,000 deaths.",[])
E("timor-leste","Democratic Republic of Timor-Leste","polity",2002,None,True,"East Timor","Independent in 2002 after a UN-run referendum and transitional administration.",["East Timor","Timor-Leste"])
E("spanish-philippines","Spanish Philippines","polity",1565,1898,False,"Philippines","Three centuries of Spanish rule administered from Mexico, with the Manila galleon trade and Catholic conversion.",["Las Islas Filipinas"])
E("magellan-expedition-philippines","Magellan's Arrival in the Philippines","event",1521,1521,False,"Philippines","First European contact and Magellan's death at Mactan during the first circumnavigation.",[])
E("philippine-revolution","Philippine Revolution","event",1896,1898,False,"Philippines","Katipunan revolt under Bonifacio and Aguinaldo that ended Spanish rule.",[])
E("first-philippine-republic","First Philippine Republic","polity",1899,1901,False,"Philippines","Aguinaldo's Malolos republic, suppressed in the Philippine-American War.",["Malolos Republic"])
E("philippine-american-war","Philippine-American War","event",1899,1902,False,"Philippines","American conquest of the islands, with an estimated 200,000 or more Filipino civilian deaths.",[])
E("american-philippines","American Colonial Philippines","polity",1898,1946,False,"Philippines","US colonial rule with public schooling and English, moving to Commonwealth status in 1935.",["Insular Government"])
E("commonwealth-of-the-philippines","Commonwealth of the Philippines","polity",1935,1946,False,"Philippines","Transitional self-government under Manuel Quezon, interrupted by Japanese occupation.",[])
E("philippine-independence-1946","Philippine Independence","event",1946,1946,False,"Philippines","The United States granted independence on 4 July 1946.",[])
E("republic-of-the-philippines","Republic of the Philippines","polity",1946,None,True,"Philippines","Southeast Asian republic independent since 1946, with the Marcos dictatorship and People Power in its history.",["Philippines","Pilipinas"])
E("marcos-regime","Marcos Regime","reign",1965,1986,False,"Philippines","Ferdinand Marcos ruled 21 years, including 14 under martial law with plunder and repression.",["martial law Philippines"])
E("people-power-revolution","People Power Revolution","event",1986,1986,False,"Philippines","Four days of mass non-violent protest that ousted Marcos and installed Corazon Aquino.",["EDSA Revolution"])
E("duterte-presidency","Presidency of Rodrigo Duterte","reign",2016,2022,False,"Philippines","Presidency defined by a lethal anti-drug campaign and pivot toward China.",[])
E("asean","Association of Southeast Asian Nations","polity",1967,None,True,"Southeast Asia","Regional organisation founded in Bangkok, now ten member states pursuing economic and security cooperation.",["ASEAN"])
