import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _mn_common import E, ROWS, set_region
set_region('oceania')

# ---------------- AUSTRALIA ----------------
E("dutch-exploration-of-australia","Dutch Exploration of New Holland","era",1606,1700,False,"Australia","Dutch navigators charted much of the Australian coast without settling, naming it New Holland.",["New Holland"])
E("cook-voyage-1770","Cook's Voyage to the East Coast of Australia","event",1770,1770,False,"Australia","James Cook charted the east coast and claimed it for Britain at Possession Island.",[])
E("first-fleet","First Fleet","event",1788,1788,False,"Australia","Arrival of eleven ships at Sydney Cove on 26 January 1788 founded the penal colony of New South Wales.",[])
E("colony-of-new-south-wales","Colony of New South Wales","polity",1788,1901,False,"Australia","First British colony in Australia, originally a penal settlement covering most of the continent.",[])
E("australian-convict-transportation","Convict Transportation to Australia","era",1788,1868,False,"Australia","About 162,000 convicts were transported to Australian colonies over eighty years.",[])
E("australian-frontier-wars","Australian Frontier Wars","era",1788,1934,False,"Australia","Sustained violent dispossession of Aboriginal peoples across the continent, with massacres and mass mortality.",["frontier conflict"])
E("colony-of-tasmania","Colony of Tasmania","polity",1825,1901,False,"Australia","Van Diemen's Land separated from New South Wales, notorious for convict settlements and the Black War.",["Van Diemen's Land"])
E("colony-of-western-australia","Colony of Western Australia","polity",1829,1901,False,"Australia","Swan River settlement that later accepted convicts and boomed with 1890s goldfields.",[])
E("colony-of-south-australia","Colony of South Australia","polity",1836,1901,False,"Australia","Free-settler colony founded on Wakefield's systematic colonisation principles.",[])
E("colony-of-victoria","Colony of Victoria","polity",1851,1901,False,"Australia","Separated from New South Wales in 1851 and transformed within a decade by the gold rush.",[])
E("colony-of-queensland","Colony of Queensland","polity",1859,1901,False,"Australia","Northern colony separated in 1859, built on pastoralism, sugar and Pacific Islander labour.",[])
E("australian-gold-rushes","Australian Gold Rushes","era",1851,1870,False,"Australia","Victorian and New South Wales gold discoveries that tripled the population and reshaped politics.",[])
E("eureka-stockade","Eureka Stockade","event",1854,1854,False,"Australia","Miners' revolt at Ballarat over licence fees, later mythologised as a birth of Australian democracy.",[])
E("australian-federation","Federation of Australia","event",1901,1901,False,"Australia","Six colonies united as the Commonwealth of Australia on 1 January 1901.",[])
E("commonwealth-of-australia","Commonwealth of Australia","polity",1901,None,True,"Australia","Federal parliamentary monarchy of six states and territories, created by federation in 1901.",["Australia"])
E("white-australia-policy","White Australia Policy","polity",1901,1973,False,"Australia","Immigration Restriction Act and successors that excluded non-European migrants for seven decades.",["Immigration Restriction Act"])
E("anzac-gallipoli","ANZAC Landing at Gallipoli","event",1915,1915,False,"Australia and New Zealand","Landing of 25 April 1915 that became the founding national legend of both countries.",["Anzac Day"])
E("australian-stolen-generations","Stolen Generations","era",1905,1970,False,"Australia","Policies of removing Aboriginal and Torres Strait Islander children from their families.",[])
E("bombing-of-darwin","Bombing of Darwin","event",1942,1942,False,"Australia","Japanese air raids on northern Australia that shifted strategic reliance from Britain to the United States.",[])
E("australian-postwar-immigration","Australian Postwar Immigration Programme","era",1945,1975,False,"Australia","Mass European then global immigration that transformed Australia into a multicultural society.",[])
E("menzies-premiership","Premiership of Robert Menzies","reign",1949,1966,False,"Australia","Australia's longest-serving prime minister, presiding over postwar growth, ANZUS and the Cold War alignment.",[])
E("australian-referendum-1967","Australian Referendum of 1967","event",1967,1967,False,"Australia","Over 90 percent voted to allow federal laws for Aboriginal people and their inclusion in the census.",[])
E("whitlam-dismissal","Dismissal of the Whitlam Government","event",1975,1975,False,"Australia","Governor-General Kerr dismissed Prime Minister Gough Whitlam, Australia's gravest constitutional crisis.",[])
E("mabo-decision","Mabo Decision","event",1992,1992,False,"Australia","High Court ruling recognising native title and rejecting the doctrine of terra nullius.",["native title"])
E("australian-republic-referendum","Australian Republic Referendum","event",1999,1999,False,"Australia","Voters rejected replacing the monarchy with a parliamentary-appointed president.",[])
E("australian-apology-2008","Apology to the Stolen Generations","event",2008,2008,False,"Australia","Prime Minister Kevin Rudd's formal parliamentary apology to Indigenous Australians.",[])
E("australian-voice-referendum","Indigenous Voice Referendum","event",2023,2023,False,"Australia","Proposal for an Indigenous advisory body in the constitution, rejected by voters.",[],"medium")

# ---------------- NEW ZEALAND & PACIFIC ----------------
E("cook-new-zealand-1769","Cook's Circumnavigation of New Zealand","event",1769,1770,False,"New Zealand","Cook charted both main islands, opening sustained European contact with Maori.",[])
E("musket-wars","Musket Wars","event",1807,1842,False,"New Zealand","Inter-iwi wars transformed by trade muskets, causing large casualties and migrations before colonisation.",[])
E("treaty-of-waitangi","Treaty of Waitangi","event",1840,1840,False,"New Zealand","Agreement between the Crown and Maori chiefs, with differing English and Maori texts, New Zealand's founding document.",["Te Tiriti o Waitangi"])
E("colony-of-new-zealand","Colony of New Zealand","polity",1841,1907,False,"New Zealand","British colony that gained self-government in 1852 and fought the New Zealand Wars over land.",[])
E("new-zealand-wars","New Zealand Wars","event",1845,1872,False,"New Zealand","Conflicts between the Crown, settlers and Maori over sovereignty and land, followed by large confiscations.",["Land Wars","Maori Wars"])
E("new-zealand-womens-suffrage","New Zealand Women's Suffrage","event",1893,1893,False,"New Zealand","First self-governing country to grant women the parliamentary vote.",[])
E("dominion-of-new-zealand","Dominion of New Zealand","polity",1907,None,True,"New Zealand","Self-governing dominion from 1907, fully sovereign under the 1947 adoption of the Statute of Westminster.",["New Zealand","Aotearoa"])
E("waitangi-tribunal","Waitangi Tribunal","polity",1975,None,True,"New Zealand","Body established to investigate Crown breaches of the Treaty of Waitangi and recommend redress.",[])
E("new-zealand-nuclear-free","New Zealand Nuclear-Free Policy","event",1984,1987,False,"New Zealand","Ban on nuclear-armed and nuclear-powered ships that suspended New Zealand's ANZUS obligations.",[])
E("kingdom-of-hawaii","Kingdom of Hawaii","polity",1795,1893,False,"Hawaii","Kingdom unified by Kamehameha I, overthrown by American settlers in 1893 and annexed in 1898.",["Hawaiian Kingdom"])
E("kingdom-of-tonga","Kingdom of Tonga","polity",1845,None,True,"Tonga","Only Pacific monarchy never formally colonised, a British protected state from 1900 to 1970.",["Tonga"])
E("colony-of-fiji","Colony of Fiji","polity",1874,1970,False,"Fiji","British colony whose sugar plantations imported indentured Indian labour, reshaping its society.",[])
E("republic-of-fiji","Republic of Fiji","polity",1970,None,True,"Fiji","Independent in 1970 and a republic since 1987, with four coups over ethnic and political disputes.",["Fiji"])
E("western-samoa-independence","Independence of Samoa","event",1962,1962,False,"Samoa","First Pacific island state to gain independence, from New Zealand trusteeship.",["Western Samoa"])
E("independent-state-of-samoa","Independent State of Samoa","polity",1962,None,True,"Samoa","Polynesian state independent since 1962, with a fa'amatai chiefly political system.",["Samoa"])
E("nauru","Republic of Nauru","polity",1968,None,True,"Nauru","Tiny phosphate island state independent in 1968, later dependent on offshore processing agreements.",[])
E("papua-new-guinea","Independent State of Papua New Guinea","polity",1975,None,True,"Papua New Guinea","Independent from Australian administration in 1975, the most linguistically diverse country on earth.",["PNG"])
E("bougainville-conflict","Bougainville Conflict","event",1988,1998,False,"Papua New Guinea","Secessionist war over the Panguna mine, ended by peace accords and a 2019 independence referendum.",[])
E("solomon-islands","Solomon Islands","polity",1978,None,True,"Solomon Islands","Melanesian state independent from Britain in 1978, with ethnic conflict and a regional intervention from 2003.",[])
E("tuvalu","Tuvalu","polity",1978,None,True,"Tuvalu","Polynesian atoll state independent in 1978, among the most exposed to sea-level rise.",[])
E("kiribati","Republic of Kiribati","polity",1979,None,True,"Kiribati","Micronesian atoll republic independent from Britain in 1979.",["Gilbert Islands"])
E("vanuatu","Republic of Vanuatu","polity",1980,None,True,"Vanuatu","Independent in 1980 from the Anglo-French New Hebrides condominium.",["New Hebrides"])
E("marshall-islands","Republic of the Marshall Islands","polity",1986,None,True,"Marshall Islands","Freely associated state since 1986, site of US nuclear testing at Bikini and Enewetak.",[])
E("federated-states-of-micronesia","Federated States of Micronesia","polity",1986,None,True,"Micronesia","Four-state federation in free association with the United States since 1986.",["FSM"])
E("palau","Republic of Palau","polity",1994,None,True,"Palau","Last part of the Pacific trust territory to become independent, in free association with the US.",[])
E("pacific-nuclear-testing","Nuclear Testing in the Pacific","era",1946,1996,False,"Oceania","American, British and French tests at Bikini, Christmas Island, Maralinga and Mururoa with lasting contamination.",[])
E("french-polynesia","French Polynesia","polity",1842,None,True,"France in Oceania","French overseas collectivity of 121 islands, site of nuclear testing at Mururoa.",["Tahiti"])
E("new-caledonia","New Caledonia","polity",1853,None,True,"France in Oceania","French territory with a large Kanak population and repeated independence referendums under the Noumea Accord.",["Kanaky"])
E("pacific-islands-forum","Pacific Islands Forum","polity",1971,None,True,"Oceania","Regional political grouping of Pacific states, prominent in climate diplomacy.",["South Pacific Forum"])
E("pacific-decolonisation","Pacific Decolonisation","era",1962,1994,False,"Oceania","Successive independences from Samoa in 1962 to Palau in 1994, leaving some territories under metropolitan rule.",[])

# ---------------- GLOBAL ----------------
set_region('global')
E("age-of-discovery","Age of Discovery","era",1418,1600,False,"Global","European maritime expansion that linked the hemispheres, founding seaborne empires and global trade routes.",["Age of Exploration"])
E("early-modern-period","Early Modern Period","era",1500,1800,False,"Global","Era of gunpowder empires, printing, global commerce, scientific revolution and Atlantic slavery.",[])
E("scientific-revolution","Scientific Revolution","era",1543,1700,False,"Global","From Copernicus to Newton, the emergence of experimental science and mathematical natural philosophy.",[])
E("global-silver-trade","Global Silver Trade","era",1545,1800,False,"Global","American silver flowing via Europe and Manila to China, the first genuinely global commodity circuit.",["Manila galleon"])
E("little-ice-age-crisis","Seventeenth-Century Crisis","era",1600,1700,False,"Global","Cooling climate, harvest failure, war and rebellion from Europe to China in a century of upheaval.",["General Crisis"])
E("enlightenment","The Enlightenment","era",1685,1815,False,"Global","Movement of reason, rights and reform whose ideas shaped revolutions and modern constitutions.",["Age of Reason"])
E("industrial-revolution","Industrial Revolution","era",1760,1840,False,"Global","Mechanised production, steam power and factories that transformed economy, society and population growth.",[])
E("second-industrial-revolution","Second Industrial Revolution","era",1870,1914,False,"Global","Steel, chemicals, electricity, telegraphy and mass production that created the modern industrial economy.",[])
E("age-of-revolutions","Age of Revolutions","era",1774,1849,False,"Global","Atlantic and European revolutions that spread republicanism, nationalism and abolition.",[])
E("napoleonic-wars","Napoleonic Wars","event",1803,1815,False,"Global","Global conflict between Napoleonic France and shifting coalitions, fought from Iberia to Russia and at sea.",[])
E("battle-of-trafalgar","Battle of Trafalgar","event",1805,1805,False,"Napoleonic Wars","Nelson's victory that secured British naval supremacy for a century.",[])
E("battle-of-waterloo","Battle of Waterloo","event",1815,1815,False,"Napoleonic Wars","Allied victory in Belgium that ended Napoleon's rule and the Napoleonic Wars.",[])
E("continental-system","Continental System","polity",1806,1814,False,"Napoleonic Europe","Napoleon's blockade of British trade, which damaged European economies and provoked the Peninsular and Russian wars.",[])
E("congress-of-vienna","Congress of Vienna","event",1814,1815,False,"Europe","Great-power settlement that redrew Europe's map, restored monarchies and created a balance of power lasting decades.",[],"high","europe")
E("concert-of-europe","Concert of Europe","era",1815,1914,False,"Europe","System of great-power consultation and congresses that limited general European war for a century.",[],"high","europe")
E("revolutions-of-1848","Revolutions of 1848","event",1848,1849,False,"Europe","Liberal and nationalist uprisings across France, the German states, Italy, Austria and Hungary, mostly defeated.",["Springtime of Nations","Year of Revolutions"],"high","europe")
E("abolition-of-slavery-global","Global Abolition of Slavery","era",1794,1888,False,"Global","Successive abolitions from revolutionary France and Britain to Brazil that ended legal chattel slavery in the Atlantic world.",[])
E("new-imperialism","New Imperialism","era",1870,1914,False,"Global","Intense European, American and Japanese colonial expansion into Africa, Asia and the Pacific.",[])
E("first-globalisation","First Age of Globalisation","era",1870,1914,False,"Global","Steamships, telegraphs, gold standard and mass migration that integrated the world economy before 1914.",[])
E("first-world-war","First World War","event",1914,1918,False,"Global","Industrial war among Europe's empires and their allies that killed some 17 million and destroyed four empires.",["Great War","WWI"])
E("western-front","Western Front of the First World War","event",1914,1918,False,"First World War","Four years of trench stalemate in France and Belgium, with battles such as Verdun, the Somme and Passchendaele.",[])
E("spanish-flu-pandemic","Spanish Flu Pandemic","event",1918,1920,False,"Global","Influenza pandemic that infected a third of humanity and killed an estimated 50 million people.",["1918 influenza pandemic"])
E("paris-peace-conference","Paris Peace Conference and Treaty of Versailles","event",1919,1920,False,"Global","Settlement that redrew Europe and the Middle East, imposed reparations on Germany and created the League and mandates.",["Treaty of Versailles"])
E("league-of-nations","League of Nations","polity",1920,1946,False,"Global","First general international organisation for collective security, weakened by absences and its failures in the 1930s.",[])
E("mandate-system","League of Nations Mandate System","polity",1920,1946,False,"Global","Administration of former German and Ottoman territories by the victors as trusteeships in name.",[])
E("interwar-period","Interwar Period","era",1918,1939,False,"Global","Two decades of fragile peace: reparations, boom, depression, fascism and the collapse of collective security.",[])
E("great-depression","Great Depression","event",1929,1939,False,"Global","Worldwide slump after the 1929 crash, with mass unemployment, deflation, protectionism and political radicalisation.",["Wall Street Crash"])
E("rise-of-fascism","Rise of Fascism","era",1919,1939,False,"Global","Spread of fascist and authoritarian movements in Italy, Germany, Spain, Japan and beyond between the wars.",[])
E("second-world-war","Second World War","event",1939,1945,False,"Global","Global war between the Axis and the Allies that killed 70-85 million people and remade the world order.",["WWII"])
E("operation-barbarossa","Operation Barbarossa","event",1941,1941,False,"Second World War","German invasion of the Soviet Union, the largest land offensive in history and the war's decisive theatre.",[])
E("battle-of-stalingrad","Battle of Stalingrad","event",1942,1943,False,"Second World War","Soviet encirclement and destruction of a German army, the turning point on the Eastern Front.",[])
E("d-day-normandy","Normandy Landings","event",1944,1944,False,"Second World War","Allied invasion of northwest Europe on 6 June 1944 that opened the western front against Germany.",["D-Day"])
E("holocaust","The Holocaust","event",1941,1945,False,"Global","Nazi genocide of about six million Jews, alongside the murder of Roma, disabled people and others.",["Shoah","Final Solution"])
E("wannsee-conference","Wannsee Conference","event",1942,1942,False,"The Holocaust","Meeting of German officials to coordinate the deportation and murder of Europe's Jews.",[])
E("auschwitz","Auschwitz-Birkenau","polity",1940,1945,False,"The Holocaust","Largest Nazi concentration and extermination camp, where about 1.1 million people were murdered.",[])
E("genocide-convention","Genocide Convention","event",1948,1948,False,"Global","UN convention defining and criminalising genocide, drafted after the Holocaust.",[])
E("universal-declaration-human-rights","Universal Declaration of Human Rights","event",1948,1948,False,"Global","UN General Assembly declaration setting out a common standard of rights for all peoples.",["UDHR"])
E("bretton-woods-system","Bretton Woods System","polity",1944,1971,False,"Global","Postwar monetary order of fixed exchange rates and dollar-gold convertibility, with the IMF and World Bank.",[])
E("imf","International Monetary Fund","polity",1945,None,True,"Global","Institution created at Bretton Woods to lend to countries in balance-of-payments difficulty.",["IMF"])
E("world-bank","World Bank","polity",1944,None,True,"Global","Development lender founded at Bretton Woods, originally for postwar reconstruction.",["IBRD"])
E("united-nations","United Nations","polity",1945,None,True,"Global","Universal international organisation founded in San Francisco in 1945, with 193 member states.",["UN"])
E("un-security-council","United Nations Security Council","polity",1945,None,True,"United Nations","Fifteen-member body with five permanent vetoes, responsible for international peace and security.",["UNSC"])
E("cold-war","Cold War","era",1947,1991,False,"Global","Global rivalry between the United States and the Soviet Union, fought by proxy, arms race and ideology.",[])
E("iron-curtain","Iron Curtain","era",1945,1991,False,"Europe","Division of Europe between Soviet-dominated east and Western-aligned west, symbolised by Churchill's 1946 speech.",[],"high","europe")
E("truman-doctrine","Truman Doctrine","event",1947,1947,False,"Cold War","American commitment to contain communism, beginning with aid to Greece and Turkey.",["containment"])
E("marshall-plan","Marshall Plan","event",1948,1952,False,"Global","American aid programme of about 13 billion dollars that rebuilt Western European economies and tied them together.",["European Recovery Program"])
E("comecon","Comecon","polity",1949,1991,False,"Cold War","Soviet-led economic organisation coordinating the planned economies of the Eastern bloc.",["CMEA"])
E("nato","North Atlantic Treaty Organization","polity",1949,None,True,"Global","Transatlantic military alliance founded in 1949 on collective defence under Article 5, now 32 members.",["NATO"])
E("warsaw-pact","Warsaw Pact","polity",1955,1991,False,"Cold War","Soviet-led military alliance of Eastern bloc states, dissolved in 1991.",["Warsaw Treaty Organization"])
E("nuclear-arms-race","Nuclear Arms Race","era",1945,1991,False,"Global","Superpower build-up from the first atomic bombs to tens of thousands of warheads, with deterrence and arms control.",["mutually assured destruction"])
E("non-proliferation-treaty","Nuclear Non-Proliferation Treaty","event",1968,None,True,"Global","Treaty limiting the spread of nuclear weapons while recognising five nuclear-weapon states.",["NPT"])
E("decolonisation","Decolonisation","era",1945,1997,False,"Global","Dissolution of the European empires and the emergence of scores of new states across Asia, Africa and the Pacific.",[])
E("non-aligned-movement","Non-Aligned Movement","polity",1961,None,True,"Global","Grouping of states refusing Cold War alignment, founded at Belgrade after the Bandung Conference.",["NAM"])
E("third-world-concept","Third World and Global South","era",1952,None,True,"Global","Category for states outside the Western and Soviet blocs, later reframed as the Global South.",[])
E("green-revolution","Green Revolution","era",1950,1980,False,"Global","High-yield crop varieties, fertiliser and irrigation that greatly increased food production in Asia and Latin America.",[])
E("space-race","Space Race","era",1955,1975,False,"Global","Soviet-American competition from Sputnik and Gagarin to Apollo 11 and the Apollo-Soyuz docking.",[])
E("sputnik","Launch of Sputnik 1","event",1957,1957,False,"Space Race","First artificial satellite, launched by the USSR on 4 October 1957, opening the space age.",[])
E("gagarin-flight","First Human Spaceflight","event",1961,1961,False,"Space Race","Yuri Gagarin orbited the Earth on 12 April 1961 aboard Vostok 1.",["Yuri Gagarin"])
E("apollo-11","Apollo 11 Moon Landing","event",1969,1969,False,"Space Race","First crewed lunar landing, on 20 July 1969, the culmination of the space race.",[])
E("detente","Detente","period",1969,1979,False,"Cold War","Easing of superpower tension with SALT, the Helsinki Accords and expanded trade, ended by Afghanistan.",[])
E("helsinki-accords","Helsinki Final Act","event",1975,1975,False,"Europe","Agreement recognising postwar borders while committing signatories to human rights, empowering dissidents.",["Helsinki Accords"],"high","europe")
E("second-cold-war","Second Cold War","period",1979,1985,False,"Cold War","Renewed confrontation after Afghanistan, with missile deployments, SDI and heightened nuclear risk.",[])
E("revolutions-of-1989","Revolutions of 1989","event",1989,1989,False,"Europe","Peaceful collapse of communist regimes across Eastern Europe, from Poland to Romania.",["Autumn of Nations"],"high","europe")
E("fall-of-the-berlin-wall","Fall of the Berlin Wall","event",1989,1989,False,"Europe","Opening of the Wall on 9 November 1989, the emblematic end of Cold War Europe.",[],"high","europe")
E("end-of-the-cold-war","End of the Cold War","event",1989,1991,False,"Global","Collapse of the Eastern bloc and dissolution of the USSR, leaving the United States as sole superpower.",[])
E("european-coal-and-steel-community","European Coal and Steel Community","polity",1952,2002,False,"Europe","Six-nation pooling of coal and steel, the first step of European integration.",["ECSC","Schuman Plan"],"high","europe")
E("treaty-of-rome","Treaty of Rome","event",1957,1957,False,"Europe","Founding treaty of the European Economic Community and Euratom, creating a common market.",[],"high","europe")
E("european-economic-community","European Economic Community","polity",1958,1993,False,"Europe","Common market of six then twelve states that became the European Union at Maastricht.",["EEC","Common Market"],"high","europe")
E("schengen-agreement","Schengen Agreement","event",1985,1995,False,"Europe","Agreement abolishing internal border checks, implemented in 1995 and now covering most of the EU.",[],"high","europe")
E("maastricht-treaty","Maastricht Treaty","event",1992,1993,False,"Europe","Treaty creating the European Union, EU citizenship and the path to monetary union.",[],"high","europe")
E("european-union","European Union","polity",1993,None,True,"Europe","Union of 27 states with a single market, common currency for most members and supranational institutions.",["EU"],"high","europe")
E("euro-introduction","Introduction of the Euro","event",1999,2002,False,"Europe","Single currency launched for accounting in 1999 and as cash in 2002, now used by 20 states.",["euro"],"high","europe")
E("eu-enlargement-2004","EU Enlargement of 2004","event",2004,2004,False,"Europe","Ten mostly post-communist states joined the European Union, the largest single enlargement.",[],"high","europe")
E("eurozone-crisis","Eurozone Debt Crisis","event",2009,2015,False,"Europe","Sovereign-debt crisis in Greece, Ireland, Portugal, Spain and Cyprus that tested monetary union.",[],"high","europe")
E("european-migrant-crisis","European Migrant Crisis","event",2015,2016,False,"Europe","Arrival of over a million asylum seekers, mainly from Syria, straining EU cohesion and border policy.",[],"high","europe")
E("brexit","Brexit","event",2016,2020,False,"Europe","Referendum and withdrawal that made the United Kingdom the first state to leave the European Union.",[],"high","europe")
E("council-of-europe","Council of Europe","polity",1949,None,True,"Europe","Pan-European human rights body that created the European Convention and its court.",["European Court of Human Rights"],"high","europe")
E("osce","Organization for Security and Co-operation in Europe","polity",1975,None,True,"Europe","Security and human-rights organisation growing out of the Helsinki process.",["OSCE","CSCE"],"high","europe")
E("gatt","General Agreement on Tariffs and Trade","polity",1947,1995,False,"Global","Postwar framework of trade negotiation rounds that lowered tariffs worldwide, replaced by the WTO.",["GATT"])
E("world-trade-organization","World Trade Organization","polity",1995,None,True,"Global","Organisation governing world trade rules and disputes, founded in 1995 from GATT.",["WTO"])
E("globalisation","Contemporary Globalisation","era",1980,None,True,"Global","Deepening integration of trade, finance, production and information, with container shipping and the internet.",["globalization"])
E("information-revolution","Information Revolution","era",1971,None,True,"Global","Microprocessors, personal computing, the internet and mobile networks that reorganised economy and society.",["digital revolution"])
E("world-wide-web","World Wide Web","event",1989,1991,False,"Global","Berners-Lee's invention at CERN that made the internet a mass medium.",["internet"])
E("brics","BRICS","polity",2009,None,True,"Global","Grouping of major emerging economies, originally Brazil, Russia, India, China and South Africa, later expanded.",[])
E("september-11-attacks","September 11 Attacks","event",2001,2001,False,"Global","Al-Qaeda hijackings that killed nearly 3,000 people and triggered two decades of Western intervention.",["9/11"])
E("war-on-terror","War on Terror","era",2001,2021,False,"Global","US-led campaigns after 9/11 in Afghanistan, Iraq and beyond, with drone warfare and expanded surveillance.",[])
E("global-financial-crisis-2008","Global Financial Crisis of 2008","event",2007,2009,False,"Global","Collapse of the US mortgage market and Lehman Brothers triggered the deepest recession since the 1930s.",["2008 financial crisis","Great Recession"])
E("great-recession","Great Recession","event",2008,2012,False,"Global","Worldwide downturn after the financial crisis, with bank rescues, austerity and lasting political effects.",[])
E("kyoto-protocol","Kyoto Protocol","event",1997,2005,False,"Global","First binding treaty on greenhouse-gas emissions, in force from 2005 without US ratification.",[])
E("paris-agreement","Paris Agreement","event",2015,None,True,"Global","Universal climate accord committing states to limit warming well below two degrees Celsius.",[])
E("anthropogenic-climate-change","Anthropogenic Climate Change","era",1800,None,True,"Global","Industrial-era warming from greenhouse gases, now a central issue of international politics.",["global warming"])
E("covid-19-pandemic","COVID-19 Pandemic","event",2020,2023,False,"Global","SARS-CoV-2 pandemic that killed millions, closed borders and economies, and produced vaccines within a year.",["coronavirus pandemic"])
E("who","World Health Organization","polity",1948,None,True,"Global","UN agency for international health, which coordinated smallpox eradication and pandemic responses.",["WHO"])
E("smallpox-eradication","Eradication of Smallpox","event",1959,1980,False,"Global","WHO campaign that eliminated smallpox, the only human disease so far eradicated.",[])
E("hiv-aids-pandemic","HIV/AIDS Pandemic","event",1981,None,True,"Global","Global epidemic that has killed tens of millions, transformed by antiretroviral therapy from the late 1990s.",["AIDS"])
E("world-population-growth","Modern Population Explosion","era",1800,None,True,"Global","Growth from about one billion people in 1800 to over eight billion, driven by falling mortality.",["demographic transition"])
E("great-migrations-modern","Age of Mass Migration","era",1840,1940,False,"Global","Roughly 55 million Europeans and millions of Asians migrated across oceans, reshaping settler societies.",[])
E("international-criminal-court","International Criminal Court","polity",2002,None,True,"Global","Permanent court for genocide, war crimes and crimes against humanity, created by the Rome Statute.",["ICC"])
E("universal-suffrage-movement","Spread of Universal Suffrage","era",1893,1994,False,"Global","Extension of the vote to women and excluded groups, from New Zealand in 1893 to South Africa in 1994.",["women's suffrage"])
E("artificial-intelligence-era","Rise of Artificial Intelligence","era",2012,None,True,"Global","Deep learning and large language models that moved AI into mainstream economic and political consequence.",[],"medium")
