import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _mn_common import E, ROWS, set_region
set_region('africa')

# ---------------- COLONIAL FRAMEWORK ----------------
E("scramble-for-africa","Scramble for Africa","era",1881,1914,False,"Africa","European powers partitioned almost the whole continent in three decades of conquest and treaty-making.",["Partition of Africa"])
E("berlin-conference","Berlin Conference","event",1884,1885,False,"Africa","Fourteen powers set rules for African colonisation and recognised Leopold II's Congo Free State.",["Congo Conference"])
E("british-empire-in-africa","British Colonial Africa","polity",1795,1980,False,"Africa","British colonies and protectorates from the Cape to Egypt, decolonised mainly between 1956 and 1980.",[])
E("french-colonial-africa","French Colonial Africa","polity",1830,1962,False,"Africa","French West and Equatorial Africa plus the Maghreb, mostly independent in 1960 and Algeria in 1962.",["Afrique francaise"])
E("german-colonial-africa","German Colonial Africa","polity",1884,1919,False,"Africa","Togo, Kamerun, South West Africa and East Africa, lost as mandates after the First World War.",[])
E("italian-colonial-africa","Italian Colonial Africa","polity",1890,1943,False,"Africa","Eritrea, Somalia, Libya and briefly Ethiopia, lost during the Second World War.",[])
E("belgian-colonial-africa","Belgian Colonial Africa","polity",1908,1962,False,"Africa","Belgian Congo plus Ruanda-Urundi, decolonised abruptly in 1960-62.",[])
E("portuguese-colonial-africa","Portuguese Colonial Africa","polity",1500,1975,False,"Africa","Angola, Mozambique, Guinea-Bissau, Cape Verde and Sao Tome, held until the Carnation Revolution.",[])
E("decolonisation-of-africa","Decolonisation of Africa","era",1951,1994,False,"Africa","Independence of more than fifty states, from Libya in 1951 to South Africa's democratic transition in 1994.",[])
E("year-of-africa","Year of Africa","event",1960,1960,False,"Africa","Seventeen African countries became independent in 1960, transforming the United Nations.",[])
E("organisation-of-african-unity","Organisation of African Unity","polity",1963,2002,False,"Africa","Pan-African body founded in Addis Ababa that upheld colonial borders and backed liberation movements.",["OAU"])
E("african-union","African Union","polity",2002,None,True,"Africa","Continental organisation succeeding the OAU, with a Peace and Security Council and free-trade area.",["AU"])
E("pan-africanism","Pan-Africanism","era",1900,None,True,"Africa and diaspora","Movement for African unity and diaspora solidarity from the early congresses to Nkrumah and the AU.",[])
E("trans-saharan-and-indian-ocean-slave-trades","Indian Ocean and Trans-Saharan Slave Trades","era",1500,1900,False,"Africa","Long-running slave trades across the Sahara and Indian Ocean, ended by gradual abolition and colonial rule.",[])

# ---------------- NORTH AFRICA ----------------
E("ottoman-egypt","Ottoman Egypt","polity",1517,1867,False,"Egypt","Ottoman province governed by Mamluk-Ottoman elites, briefly occupied by Napoleon in 1798.",[])
E("french-invasion-of-egypt","French Invasion of Egypt","event",1798,1801,False,"Egypt","Napoleon's campaign that shattered Mamluk power, produced the Description de l'Egypte and ended in British-Ottoman victory.",[])
E("muhammad-ali-reign","Rule of Muhammad Ali of Egypt","reign",1805,1848,False,"Egypt","Albanian-Ottoman officer who massacred the Mamluks and built a modern army, industry and cotton economy.",["Mehmed Ali"])
E("khedivate-of-egypt","Khedivate of Egypt","polity",1867,1914,False,"Egypt","Autonomous Ottoman khedivate that built the Suez Canal, went bankrupt and fell under British control.",[])
E("suez-canal-opening","Opening of the Suez Canal","event",1869,1869,False,"Egypt","Waterway linking the Mediterranean and Red Sea, transforming global trade and Egypt's strategic value.",[])
E("british-occupation-of-egypt","British Occupation of Egypt","period",1882,1956,False,"Egypt","Occupation after the Urabi revolt, formalised as a protectorate in 1914 and ended by the 1956 evacuation.",[])
E("kingdom-of-egypt","Kingdom of Egypt","polity",1922,1953,False,"Egypt","Nominally independent monarchy under Fuad I and Farouk, dominated by Britain and ended by revolution.",[])
E("egyptian-revolution-1952","Egyptian Revolution of 1952","event",1952,1952,False,"Egypt","Free Officers' coup that deposed Farouk and brought Nasser to power.",[])
E("republic-of-egypt","Arab Republic of Egypt","polity",1953,None,True,"Egypt","Republic since 1953: Nasserism, wars with Israel, Sadat's peace, Mubarak's rule and the 2011 revolution.",["Egypt"])
E("nasser-rule","Rule of Gamal Abdel Nasser","reign",1954,1970,False,"Egypt","Pan-Arab leader who nationalised the canal, built the Aswan High Dam and lost the 1967 war.",["Nasserism"])
E("aswan-high-dam","Aswan High Dam","event",1960,1970,False,"Egypt","Soviet-aided dam that controlled the Nile flood, created Lake Nasser and displaced Nubian communities.",[])
E("sadat-rule","Presidency of Anwar Sadat","reign",1970,1981,False,"Egypt","Launched the 1973 war, expelled Soviet advisers, made peace with Israel and was assassinated in 1981.",[])
E("mubarak-rule","Presidency of Hosni Mubarak","reign",1981,2011,False,"Egypt","Thirty years of authoritarian stability, ended by the Tahrir Square uprising.",[])
E("egyptian-revolution-2011","Egyptian Revolution of 2011","event",2011,2011,False,"Egypt","Eighteen days of protest centred on Tahrir Square that forced Mubarak's resignation.",[])
E("sisi-rule","Presidency of Abdel Fattah el-Sisi","reign",2014,None,True,"Egypt","Army chief who led the 2013 coup and has ruled since 2014 with severe restrictions on dissent.",[])
E("regency-of-algiers","Regency of Algiers","polity",1516,1830,False,"Algeria","Ottoman-aligned corsair state on the Barbary coast, conquered by France in 1830.",["Ottoman Algeria"])
E("french-conquest-of-algeria","French Conquest of Algeria","event",1830,1903,False,"Algeria","Long, violent conquest and settlement, resisted by Abd al-Qadir and Kabyle revolts.",[])
E("french-algeria","French Algeria","polity",1830,1962,False,"Algeria","Departments of France with a large settler population, ended by the war of independence.",["Algerie francaise"])
E("algerian-war","Algerian War of Independence","event",1954,1962,False,"Algeria","Eight-year FLN insurgency and French counterinsurgency that killed hundreds of thousands and toppled the Fourth Republic.",["Guerre d'Algerie"])
E("battle-of-algiers","Battle of Algiers","event",1956,1957,False,"Algeria","Urban campaign of bombings and systematic French torture that became emblematic of the war.",[])
E("republic-of-algeria","People's Democratic Republic of Algeria","polity",1962,None,True,"Algeria","Independent from France in 1962, hydrocarbon-dependent and shaped by FLN rule and the 1990s civil war.",["Algeria"])
E("algerian-civil-war","Algerian Civil War","event",1991,2002,False,"Algeria","War between the state and Islamist insurgents after cancelled elections, with about 150,000 to 200,000 dead.",["Black Decade"])
E("alaouite-morocco","Alaouite Sultanate of Morocco","polity",1631,None,True,"Morocco","Sharifian dynasty that has ruled Morocco since the 17th century, surviving colonial protectorate.",["Morocco"])
E("french-protectorate-morocco","French and Spanish Protectorates in Morocco","polity",1912,1956,False,"Morocco","Treaty of Fez protectorate with a Spanish zone, resisted in the Rif War and ended in 1956.",[])
E("rif-war","Rif War","event",1921,1926,False,"Morocco","Abd el-Krim's republic defeated Spanish armies before falling to a Franco-Spanish offensive.",[])
E("kingdom-of-morocco","Kingdom of Morocco","polity",1956,None,True,"Morocco","Independent monarchy since 1956 under Mohammed V, Hassan II and Mohammed VI.",["Morocco","al-Maghrib"])
E("western-sahara-conflict","Western Sahara Conflict","event",1975,None,True,"Western Sahara","Moroccan annexation after Spanish withdrawal, contested by the Polisario Front and a stalled UN referendum.",["Polisario","Sahrawi Republic"])
E("green-march","Green March","event",1975,1975,False,"Morocco","Mass Moroccan civilian march into Spanish Sahara that secured Moroccan control.",[])
E("husainid-tunisia","Husainid Beylik of Tunis","polity",1705,1957,False,"Tunisia","Dynasty that ruled Tunisia under Ottoman then French suzerainty until the republic.",[])
E("french-protectorate-tunisia","French Protectorate of Tunisia","polity",1881,1956,False,"Tunisia","Protectorate established by the Treaty of Bardo, ended by Neo Destour's independence campaign.",[])
E("republic-of-tunisia","Republic of Tunisia","polity",1957,None,True,"Tunisia","Independent republic under Bourguiba then Ben Ali, birthplace of the Arab Spring.",["Tunisia"])
E("bourguiba-rule","Rule of Habib Bourguiba","reign",1957,1987,False,"Tunisia","Founding president who secularised law and advanced women's rights before being deposed for senility.",[])
E("tunisian-revolution","Tunisian Revolution","event",2010,2011,False,"Tunisia","Protests after Mohamed Bouazizi's self-immolation that ousted Ben Ali and began the Arab Spring.",["Jasmine Revolution"])
E("ottoman-tripolitania","Ottoman Tripolitania","polity",1551,1911,False,"Libya","Ottoman and Karamanli rule over the Libyan coast, ended by the Italian invasion.",[])
E("italian-libya","Italian Libya","polity",1911,1943,False,"Libya","Italian colony whose pacification killed a large share of the Cyrenaican population.",[])
E("kingdom-of-libya","Kingdom of Libya","polity",1951,1969,False,"Libya","Senussi monarchy under Idris I, independent by UN resolution and transformed by oil.",[])
E("gaddafi-rule","Rule of Muammar Gaddafi","reign",1969,2011,False,"Libya","Forty-two years of idiosyncratic rule under the Jamahiriya, ended by uprising and NATO intervention.",["Jamahiriya"])
E("libyan-civil-war","Libyan Civil Wars","event",2011,None,True,"Libya","Uprising and NATO campaign that killed Gaddafi, followed by a decade of rival governments and militias.",[])
E("mahdist-state","Mahdist State","polity",1885,1898,False,"Sudan","Islamic state founded after the fall of Khartoum, destroyed by Kitchener at Omdurman.",["Mahdiyya"])
E("anglo-egyptian-sudan","Anglo-Egyptian Sudan","polity",1899,1956,False,"Sudan","Condominium administered largely by Britain, which governed the south separately.",[])
E("republic-of-sudan","Republic of the Sudan","polity",1956,None,True,"Sudan","Independent in 1956, marked by two civil wars, Darfur, Bashir's rule and renewed war from 2023.",["Sudan"])
E("first-sudanese-civil-war","First Sudanese Civil War","event",1955,1972,False,"Sudan","North-south conflict ended by the Addis Ababa Agreement's autonomy for the south.",[])
E("second-sudanese-civil-war","Second Sudanese Civil War","event",1983,2005,False,"Sudan","Twenty-two-year war with the SPLA that killed some two million and ended in a peace deal.",[])
E("darfur-conflict","Darfur Conflict","event",2003,None,True,"Sudan","Government and Janjaweed campaign against Darfuri rebels and civilians, described as genocide.",[])
E("bashir-rule","Rule of Omar al-Bashir","reign",1989,2019,False,"Sudan","Islamist military ruler indicted by the ICC, overthrown by protests and the army in 2019.",[])
E("south-sudan","Republic of South Sudan","polity",2011,None,True,"South Sudan","World's newest widely recognised state, independent by referendum in 2011 and soon at civil war.",["South Sudan"])
E("sudanese-war-2023","Sudanese Civil War of 2023","event",2023,None,True,"Sudan","War between the army and the Rapid Support Forces that produced the world's largest displacement crisis.",[],"medium")

# ---------------- WEST AFRICA ----------------
E("songhai-fall","Fall of the Songhai Empire","event",1591,1591,False,"West Africa","Moroccan musketeers defeated Songhai at Tondibi, ending the last great Sahelian empire.",[])
E("kingdom-of-benin-late","Kingdom of Benin (late)","period",1500,1897,False,"Nigeria","Powerful Edo kingdom famed for its bronzes, sacked and looted by a British punitive expedition in 1897.",["Benin Empire"])
E("oyo-empire","Oyo Empire","polity",1608,1896,False,"Nigeria","Yoruba cavalry empire that dominated the slave-trading coast before collapsing into civil wars.",[])
E("asante-empire","Asante Empire","polity",1701,1901,False,"Ghana","Akan gold and trading empire centred on Kumasi, annexed by Britain after five wars.",["Ashanti Empire"])
E("dahomey-kingdom","Kingdom of Dahomey","polity",1600,1904,False,"Benin","West African kingdom with its famous women's regiments, conquered by France in the 1890s.",["Danxome"])
E("sokoto-caliphate","Sokoto Caliphate","polity",1804,1903,False,"Nigeria","Vast Fulani state founded by Usman dan Fodio's jihad, defeated by Britain and incorporated as an emirate system.",[])
E("gold-coast-colony","Gold Coast","polity",1821,1957,False,"Ghana","British colony built on gold, cocoa and the conquest of Asante, first in sub-Saharan Africa to independence.",[])
E("republic-of-ghana","Republic of Ghana","polity",1957,None,True,"Ghana","First sub-Saharan colony to gain independence, on 6 March 1957, under Kwame Nkrumah.",["Ghana"])
E("nkrumah-rule","Rule of Kwame Nkrumah","reign",1957,1966,False,"Ghana","Pan-Africanist founding leader who built the Akosombo Dam and was overthrown by a coup in 1966.",[])
E("colonial-nigeria","Colonial Nigeria","polity",1900,1960,False,"Nigeria","British protectorates amalgamated in 1914 and ruled through indirect rule over emirs and chiefs.",[])
E("federal-republic-of-nigeria","Federal Republic of Nigeria","polity",1960,None,True,"Nigeria","Africa's most populous state, independent in 1960, oil-rich and shaped by civil war and military rule.",["Nigeria"])
E("nigerian-civil-war","Nigerian Civil War","event",1967,1970,False,"Nigeria","Biafra's secession and blockade, which killed one to two million people, mostly by starvation.",["Biafran War"])
E("nigerian-military-rule","Nigerian Military Rule","period",1966,1999,False,"Nigeria","Nearly three decades of coups and juntas, including Abacha's dictatorship, ending with the Fourth Republic.",[])
E("nigerian-fourth-republic","Nigerian Fourth Republic","polity",1999,None,True,"Nigeria","Civilian democracy since 1999, contending with Boko Haram, oil-delta conflict and rapid population growth.",[])
E("boko-haram-insurgency","Boko Haram Insurgency","event",2009,None,True,"Nigeria","Jihadist conflict in the northeast with mass abductions and millions displaced across the Lake Chad basin.",[])
E("republic-of-senegal","Republic of Senegal","polity",1960,None,True,"Senegal","West African republic independent in 1960, notable for stable civilian rule and Leopold Senghor's presidency.",["Senegal"])
E("mali-federation","Mali Federation","polity",1959,1960,False,"West Africa","Short-lived union of Senegal and French Sudan that split within months of independence.",[])
E("republic-of-mali","Republic of Mali","polity",1960,None,True,"Mali","Sahelian republic independent in 1960, since 2012 facing jihadist insurgency and coups.",["Mali","French Sudan"])
E("mali-war","Mali War","event",2012,None,True,"Mali","Tuareg and jihadist rebellion, French intervention and successive military coups.",[])
E("republic-of-cote-divoire","Republic of Cote d'Ivoire","polity",1960,None,True,"Cote d'Ivoire","Cocoa-exporting republic independent in 1960 under Houphouet-Boigny, later split by civil war.",["Ivory Coast"])
E("republic-of-guinea","Republic of Guinea","polity",1958,None,True,"Guinea","Only French African colony to reject the 1958 community, independent under Sekou Toure.",["Guinea"])
E("guinea-bissau","Republic of Guinea-Bissau","polity",1974,None,True,"Guinea-Bissau","Independent after Amilcar Cabral's PAIGC war against Portugal.",[])
E("cape-verde","Republic of Cabo Verde","polity",1975,None,True,"Cape Verde","Atlantic island republic independent from Portugal in 1975, a stable multiparty democracy.",["Cape Verde"])
E("burkina-faso","Burkina Faso","polity",1960,None,True,"Burkina Faso","Independent as Upper Volta in 1960, renamed by Thomas Sankara in 1984, now facing jihadist war and coups.",["Upper Volta"])
E("sankara-rule","Rule of Thomas Sankara","reign",1983,1987,False,"Burkina Faso","Revolutionary leader of literacy, vaccination and anti-imperial rhetoric, assassinated in 1987.",[])
E("republic-of-niger","Republic of Niger","polity",1960,None,True,"Niger","Sahelian uranium-producing republic independent in 1960, with a 2023 coup ending civilian rule.",["Niger"])
E("republic-of-benin","Republic of Benin","polity",1960,None,True,"Benin","Independent as Dahomey in 1960, Marxist from 1975 to 1990 and a pioneer of African democratic transition.",["Dahomey"])
E("togolese-republic","Togolese Republic","polity",1960,None,True,"Togo","Former German then French territory independent in 1960, ruled by the Gnassingbe family since 1967.",["Togo"])
E("sierra-leone","Republic of Sierra Leone","polity",1961,None,True,"Sierra Leone","Founded as a settlement for freed slaves, independent in 1961 and scarred by a diamond-fuelled civil war.",[])
E("sierra-leone-civil-war","Sierra Leone Civil War","event",1991,2002,False,"Sierra Leone","Brutal war involving the RUF and blood diamonds, ended by British and UN intervention.",[])
E("republic-of-liberia","Republic of Liberia","polity",1847,None,True,"Liberia","Founded by freed American slaves and independent from 1847, later devastated by two civil wars.",["Liberia"])
E("liberian-civil-wars","Liberian Civil Wars","event",1989,2003,False,"Liberia","Two wars involving Charles Taylor that killed about 250,000 and destabilised the region.",[])
E("the-gambia","Republic of The Gambia","polity",1965,None,True,"The Gambia","Small riverine state independent in 1965, ruled by Yahya Jammeh from 1994 to 2017.",["Gambia"])
E("mauritania","Islamic Republic of Mauritania","polity",1960,None,True,"Mauritania","Saharan republic independent in 1960, which formally abolished slavery only in 1981.",[])

# ---------------- CENTRAL & EAST AFRICA ----------------
E("kingdom-of-kongo","Kingdom of Kongo","polity",1500,1914,False,"Congo","Christianised Central African kingdom that traded with Portugal and declined under the slave trade.",[])
E("congo-free-state","Congo Free State","polity",1885,1908,False,"Congo","Leopold II's personal colony whose rubber regime caused mass death and international scandal.",["Etat independant du Congo"])
E("belgian-congo","Belgian Congo","polity",1908,1960,False,"Congo","Belgian state colony exploited for copper, rubber and uranium, decolonised abruptly in 1960.",[])
E("congo-crisis","Congo Crisis","event",1960,1965,False,"Congo","Post-independence collapse: Katangese secession, Lumumba's murder, UN intervention and Mobutu's rise.",[])
E("mobutu-rule","Rule of Mobutu Sese Seko","reign",1965,1997,False,"Congo","Thirty-two years of kleptocratic rule over the country he renamed Zaire.",["Zaire"])
E("republic-of-zaire","Republic of Zaire","polity",1971,1997,False,"Congo","Mobutu's renamed state, ended by Kabila's rebellion in the First Congo War.",[])
E("dr-congo","Democratic Republic of the Congo","polity",1997,None,True,"Congo","Vast mineral-rich state renamed in 1997, still troubled by conflict in its eastern provinces.",["DRC","Congo-Kinshasa"])
E("first-congo-war","First Congo War","event",1996,1997,False,"Central Africa","Rwandan- and Ugandan-backed rebellion that overthrew Mobutu.",[])
E("second-congo-war","Second Congo War","event",1998,2003,False,"Central Africa","Africa's world war, involving nine countries and causing millions of deaths, mostly from disease and hunger.",["Great War of Africa"])
E("republic-of-congo-brazzaville","Republic of the Congo","polity",1960,None,True,"Congo-Brazzaville","Former French Congo independent in 1960, oil-exporting and long ruled by Denis Sassou Nguesso.",["Congo-Brazzaville"])
E("kingdom-of-rwanda","Kingdom of Rwanda","polity",1500,1961,False,"Rwanda","Tutsi-led monarchy that colonial rule reinforced before the 1959 Hutu revolution abolished it.",[])
E("ruanda-urundi","Ruanda-Urundi","polity",1922,1962,False,"Central Africa","Belgian mandate then trust territory that hardened Hutu-Tutsi categories through identity cards.",[])
E("republic-of-rwanda","Republic of Rwanda","polity",1962,None,True,"Rwanda","Independent in 1962, site of the 1994 genocide and since then of state-led reconstruction under Paul Kagame.",["Rwanda"])
E("rwandan-civil-war","Rwandan Civil War","event",1990,1994,False,"Rwanda","RPF invasion and war that led to the Arusha Accords and then to genocide.",[])
E("rwandan-genocide","Rwandan Genocide","event",1994,1994,False,"Rwanda","Roughly 800,000 to one million Tutsi and moderate Hutu killed in about a hundred days.",["Genocide against the Tutsi"])
E("kagame-rule","Rule of Paul Kagame","reign",1994,None,True,"Rwanda","RPF leader, president since 2000, credited with development and criticised for authoritarianism.",[])
E("republic-of-burundi","Republic of Burundi","polity",1962,None,True,"Burundi","Independent in 1962, marked by mass killings in 1972 and 1993 and a long civil war.",["Burundi"])
E("kingdom-of-buganda","Kingdom of Buganda","polity",1500,None,True,"Uganda","Powerful lacustrine kingdom, the core of the Uganda Protectorate, abolished in 1966 and restored in 1993.",["Buganda"])
E("uganda-protectorate","Uganda Protectorate","polity",1894,1962,False,"Uganda","British protectorate ruled indirectly through Buganda's institutions.",[])
E("republic-of-uganda","Republic of Uganda","polity",1962,None,True,"Uganda","Independent in 1962, ravaged under Amin and Obote, ruled by Yoweri Museveni since 1986.",["Uganda"])
E("idi-amin-rule","Rule of Idi Amin","reign",1971,1979,False,"Uganda","Brutal dictatorship that expelled Uganda's Asians and killed hundreds of thousands, ended by Tanzanian invasion.",[])
E("british-east-africa","East Africa Protectorate and Kenya Colony","polity",1895,1963,False,"Kenya","British colony of settler highlands, the Uganda railway and land alienation from the Kikuyu and Maasai.",[])
E("mau-mau-uprising","Mau Mau Uprising","event",1952,1960,False,"Kenya","Kikuyu-led rebellion met by mass detention camps and emergency rule, hastening independence.",["Kenya Emergency"])
E("republic-of-kenya","Republic of Kenya","polity",1963,None,True,"Kenya","Independent in 1963 under Jomo Kenyatta, later multiparty and shaped by the 2007-08 election violence.",["Kenya"])
E("kenyatta-rule","Rule of Jomo Kenyatta","reign",1963,1978,False,"Kenya","Founding leader who pursued capitalist development and centralised power in KANU.",[])
E("moi-rule","Rule of Daniel arap Moi","reign",1978,2002,False,"Kenya","Twenty-four-year one-party then multiparty presidency marked by patronage and repression.",[])
E("zanzibar-sultanate","Sultanate of Zanzibar","polity",1856,1964,False,"Tanzania","Omani-derived clove and slave-trading sultanate, a British protectorate from 1890, overthrown in the 1964 revolution.",["Zanzibar"])
E("german-east-africa","German East Africa","polity",1885,1919,False,"East Africa","German colony covering Tanganyika, Rwanda and Burundi, site of the Maji Maji rebellion.",[])
E("maji-maji-rebellion","Maji Maji Rebellion","event",1905,1907,False,"Tanzania","Mass revolt against German rule crushed by famine tactics with perhaps 250,000 deaths.",[])
E("tanganyika","Tanganyika","polity",1919,1964,False,"Tanzania","British mandate then trust territory, independent in 1961 and united with Zanzibar in 1964.",[])
E("united-republic-of-tanzania","United Republic of Tanzania","polity",1964,None,True,"Tanzania","Union of Tanganyika and Zanzibar, shaped by Nyerere's ujamaa socialism and later liberalisation.",["Tanzania"])
E("nyerere-rule","Rule of Julius Nyerere","reign",1961,1985,False,"Tanzania","Founding president whose ujamaa villagisation failed economically but built national unity and literacy.",[])
E("ethiopian-empire","Ethiopian Empire","polity",1500,1974,False,"Ethiopia","Christian Solomonic empire that survived European conquest and was abolished by the Derg.",["Abyssinia"])
E("reign-tewodros-ii","Reign of Tewodros II","reign",1855,1868,False,"Ethiopian Empire","Reunified Ethiopia after the era of princes; died resisting a British expedition at Magdala.",[])
E("reign-menelik-ii","Reign of Menelik II","reign",1889,1913,False,"Ethiopian Empire","Expanded the empire southward, founded Addis Ababa and defeated Italy at Adwa.",[])
E("battle-of-adwa","Battle of Adwa","event",1896,1896,False,"Ethiopia","Ethiopian defeat of an Italian army, the only decisive African victory over a European colonial power.",[])
E("reign-haile-selassie","Reign of Haile Selassie","reign",1930,1974,False,"Ethiopian Empire","Last emperor: exile under Italian occupation, postwar modernisation, OAU founding and deposition by famine and revolt.",[])
E("italian-occupation-of-ethiopia","Italian Occupation of Ethiopia","period",1936,1941,False,"Ethiopia","Five years of Italian East Africa rule with poison gas and reprisals, ended by British and Ethiopian forces.",["Second Italo-Ethiopian War"])
E("derg-regime","Derg","polity",1974,1991,False,"Ethiopia","Marxist military junta under Mengistu: Red Terror, famine and war with Eritrea and Somalia.",["Provisional Military Government of Ethiopia"])
E("ethiopian-famine-1983","Ethiopian Famine of 1983-85","event",1983,1985,False,"Ethiopia","Drought and war famine that killed several hundred thousand and prompted global relief campaigns.",[])
E("federal-ethiopia","Federal Democratic Republic of Ethiopia","polity",1991,None,True,"Ethiopia","Ethnic-federal republic established after the Derg's fall, later shaken by the Tigray war.",["Ethiopia"])
E("eritrean-war-of-independence","Eritrean War of Independence","event",1961,1991,False,"Eritrea","Thirty-year struggle against Ethiopian rule won by the EPLF in 1991.",[])
E("state-of-eritrea","State of Eritrea","polity",1993,None,True,"Eritrea","Independent by referendum in 1993, ruled since by Isaias Afwerki without elections.",["Eritrea"])
E("eritrean-ethiopian-war","Eritrean-Ethiopian War","event",1998,2000,False,"Horn of Africa","Border war over Badme that killed tens of thousands and froze relations until 2018.",[])
E("tigray-war","Tigray War","event",2020,2022,False,"Ethiopia","Federal and Eritrean campaign against Tigray's regional government, with mass atrocities and famine conditions.",[])
E("somali-republic","Somali Republic","polity",1960,None,True,"Somalia","Union of British and Italian Somaliland in 1960, collapsed into statelessness after 1991.",["Somalia"])
E("siad-barre-rule","Rule of Siad Barre","reign",1969,1991,False,"Somalia","Military socialist regime that fought the Ogaden War and fell to clan-based rebellion.",[])
E("somali-civil-war","Somali Civil War","event",1991,None,True,"Somalia","State collapse, famine, US and UN interventions, Islamist insurgency and al-Shabaab.",[])
E("somaliland","Republic of Somaliland","polity",1991,None,True,"Somalia","Self-declared unrecognised state in the northwest with relative stability and its own institutions.",[])
E("djibouti","Republic of Djibouti","polity",1977,None,True,"Djibouti","Former French Somaliland independent in 1977, now host to multiple foreign military bases.",["French Somaliland"])
E("central-african-republic","Central African Republic","polity",1960,None,True,"Central African Republic","Independent in 1960, ruled briefly as an empire by Bokassa and repeatedly at civil war.",["CAR","Ubangi-Shari"])
E("republic-of-chad","Republic of Chad","polity",1960,None,True,"Chad","Sahelian republic independent in 1960, with long civil wars and Libyan intervention.",["Chad"])
E("republic-of-cameroon","Republic of Cameroon","polity",1960,None,True,"Cameroon","Former German then French and British territory, independent in 1960-61 and ruled by Paul Biya since 1982.",["Cameroon"])
E("gabonese-republic","Gabonese Republic","polity",1960,None,True,"Gabon","Oil-exporting republic independent in 1960, ruled by the Bongo family from 1967 until a 2023 coup.",["Gabon"])
E("equatorial-guinea","Republic of Equatorial Guinea","polity",1968,None,True,"Equatorial Guinea","Only Spanish-speaking African state, independent in 1968, oil-rich and highly repressive.",[])
E("sao-tome-and-principe","Sao Tome and Principe","polity",1975,None,True,"Sao Tome and Principe","Atlantic island republic independent from Portugal in 1975.",[])

# ---------------- SOUTHERN AFRICA ----------------
E("dutch-cape-colony","Dutch Cape Colony","polity",1652,1806,False,"South Africa","VOC settlement at the Cape whose expansion dispossessed Khoikhoi and San and imported slaves.",["Kaapkolonie"])
E("british-cape-colony","British Cape Colony","polity",1806,1910,False,"South Africa","British colony that abolished slavery, fought frontier wars and expanded north with diamonds and gold.",[])
E("zulu-kingdom","Zulu Kingdom","polity",1816,1897,False,"South Africa","State built by Shaka's military revolution, defeated by Britain in 1879 and annexed.",["Zululand"])
E("mfecane","Mfecane","era",1815,1840,False,"Southern Africa","Period of upheaval, migration and state formation across southern Africa associated with Zulu expansion.",["Difaqane"])
E("great-trek","Great Trek","event",1836,1846,False,"South Africa","Boer migration inland from the Cape that founded the Transvaal and Orange Free State republics.",[])
E("anglo-zulu-war","Anglo-Zulu War","event",1879,1879,False,"South Africa","British invasion of Zululand, defeated at Isandlwana before winning at Ulundi.",["Isandlwana"])
E("south-african-republic","South African Republic and Orange Free State","polity",1852,1902,False,"South Africa","Boer republics of the Transvaal and Free State, annexed by Britain after the Second Anglo-Boer War.",["Transvaal","Boer republics"])
E("mineral-revolution-south-africa","South African Mineral Revolution","era",1867,1900,False,"South Africa","Diamond and Witwatersrand gold discoveries that industrialised the region and created migrant labour systems.",["Witwatersrand gold rush"])
E("second-boer-war","Second Anglo-Boer War","event",1899,1902,False,"South Africa","British conquest of the Boer republics using scorched earth and concentration camps.",["South African War"])
E("union-of-south-africa","Union of South Africa","polity",1910,1961,False,"South Africa","Self-governing dominion uniting four colonies with a whites-only franchise, forerunner of apartheid.",[])
E("anc-founding","Founding of the African National Congress","event",1912,1912,False,"South Africa","Formation of the movement that led the struggle against segregation and apartheid.",["ANC"])
E("natives-land-act","Natives Land Act","event",1913,1913,False,"South Africa","Law restricting African land ownership to about 7 percent of the country, the basis of later dispossession.",[])
E("apartheid","Apartheid","era",1948,1994,False,"South Africa","National Party system of racial classification, pass laws, bantustans and forced removals.",[])
E("sharpeville-massacre","Sharpeville Massacre","event",1960,1960,False,"South Africa","Police killing of 69 anti-pass protesters, after which the ANC and PAC were banned and turned to armed struggle.",[])
E("republic-of-south-africa-1961","Republic of South Africa (apartheid era)","polity",1961,1994,False,"South Africa","Republic that left the Commonwealth in 1961 and faced sanctions, township revolt and regional wars.",[])
E("rivonia-trial","Rivonia Trial","event",1963,1964,False,"South Africa","Trial that sentenced Nelson Mandela and co-accused to life imprisonment.",[])
E("soweto-uprising","Soweto Uprising","event",1976,1976,False,"South Africa","Student protest against Afrikaans instruction met with police fire, igniting a new phase of resistance.",[])
E("south-african-negotiations","South African Negotiated Transition","period",1990,1994,False,"South Africa","Mandela's release, unbanning of the ANC and CODESA talks that produced non-racial elections.",[])
E("south-african-election-1994","South African Election of 1994","event",1994,1994,False,"South Africa","First universal-franchise election, won by the ANC, making Nelson Mandela president.",[])
E("republic-of-south-africa","Republic of South Africa","polity",1994,None,True,"South Africa","Constitutional democracy since 1994, with a rights-based constitution and continuing inequality.",["South Africa"])
E("mandela-presidency","Presidency of Nelson Mandela","reign",1994,1999,False,"South Africa","First democratically elected president, who pursued reconciliation and a new constitution.",[])
E("south-african-trc","South African Truth and Reconciliation Commission","event",1996,1998,False,"South Africa","Tutu-chaired hearings on apartheid-era crimes, offering amnesty for full disclosure.",["TRC"])
E("mbeki-presidency","Presidency of Thabo Mbeki","reign",1999,2008,False,"South Africa","Growth, African Renaissance diplomacy and controversy over HIV/AIDS policy.",[])
E("zuma-presidency","Presidency of Jacob Zuma","reign",2009,2018,False,"South Africa","Presidency marked by state capture scandals and economic stagnation, ended by ANC pressure.",[])
E("ramaphosa-presidency","Presidency of Cyril Ramaphosa","reign",2018,None,True,"South Africa","President since 2018, facing energy shortages, corruption inquiries and coalition politics after 2024.",[])
E("german-south-west-africa","German South West Africa","polity",1884,1915,False,"Namibia","German colony where the Herero and Nama genocide of 1904-08 killed the majority of both peoples.",[])
E("herero-nama-genocide","Herero and Nama Genocide","event",1904,1908,False,"Namibia","German extermination campaign widely regarded as the twentieth century's first genocide.",[])
E("south-west-africa-mandate","South West Africa under South African Rule","polity",1915,1990,False,"Namibia","South African administration that extended apartheid and fought SWAPO's liberation war.",[])
E("republic-of-namibia","Republic of Namibia","polity",1990,None,True,"Namibia","Independent in 1990 after a UN-supervised transition following SWAPO's long struggle.",["Namibia"])
E("southern-rhodesia","Southern Rhodesia","polity",1923,1965,False,"Zimbabwe","Self-governing British settler colony named for Cecil Rhodes, based on land alienation and white minority rule.",[])
E("rhodesian-udi","Rhodesian Unilateral Declaration of Independence","event",1965,1965,False,"Zimbabwe","Ian Smith's white minority government declared independence, triggering sanctions and guerrilla war.",["UDI"])
E("rhodesian-bush-war","Rhodesian Bush War","event",1964,1979,False,"Zimbabwe","Liberation war by ZANLA and ZIPRA that forced the Lancaster House settlement.",["Zimbabwe War of Liberation","Second Chimurenga"])
E("republic-of-zimbabwe","Republic of Zimbabwe","polity",1980,None,True,"Zimbabwe","Independent in 1980 under Robert Mugabe, later hit by land seizures and hyperinflation.",["Zimbabwe"])
E("mugabe-rule","Rule of Robert Mugabe","reign",1980,2017,False,"Zimbabwe","Thirty-seven years in power: Gukurahundi massacres, land reform and economic collapse, ended by a coup.",[])
E("republic-of-zambia","Republic of Zambia","polity",1964,None,True,"Zambia","Copper-exporting republic independent in 1964 under Kenneth Kaunda.",["Northern Rhodesia","Zambia"])
E("republic-of-malawi","Republic of Malawi","polity",1964,None,True,"Malawi","Independent in 1964, ruled for three decades by Hastings Banda before multiparty elections.",["Nyasaland","Malawi"])
E("republic-of-botswana","Republic of Botswana","polity",1966,None,True,"Botswana","Diamond-rich republic independent in 1966, one of Africa's most durable democracies.",["Bechuanaland","Botswana"])
E("kingdom-of-lesotho","Kingdom of Lesotho","polity",1966,None,True,"Lesotho","Mountain kingdom founded by Moshoeshoe I, a British protectorate then independent in 1966.",["Basutoland","Lesotho"])
E("kingdom-of-eswatini","Kingdom of Eswatini","polity",1968,None,True,"Eswatini","Absolute monarchy independent in 1968, renamed from Swaziland in 2018.",["Swaziland","Eswatini"])
E("republic-of-mozambique","Republic of Mozambique","polity",1975,None,True,"Mozambique","Independent from Portugal in 1975 under FRELIMO, then torn by a long civil war.",["Mozambique"])
E("mozambican-civil-war","Mozambican Civil War","event",1977,1992,False,"Mozambique","War between FRELIMO and RENAMO, backed by Rhodesia and South Africa, with about a million deaths.",[])
E("republic-of-angola","Republic of Angola","polity",1975,None,True,"Angola","Oil-rich state independent from Portugal in 1975, at civil war for most of its first three decades.",["Angola"])
E("angolan-civil-war","Angolan Civil War","event",1975,2002,False,"Angola","Cold War proxy war among the MPLA, UNITA and FNLA with Cuban and South African intervention.",["Battle of Cuito Cuanavale"])
E("madagascar-merina-kingdom","Kingdom of Madagascar","polity",1787,1897,False,"Madagascar","Merina kingdom that unified most of the island before French conquest.",["Merina Kingdom"])
E("republic-of-madagascar","Republic of Madagascar","polity",1960,None,True,"Madagascar","Indian Ocean island republic independent from France in 1960.",["Madagascar"])
E("republic-of-mauritius","Republic of Mauritius","polity",1968,None,True,"Mauritius","Independent in 1968 and a republic since 1992, with a diversified economy and stable democracy.",["Mauritius"])
E("seychelles","Republic of Seychelles","polity",1976,None,True,"Seychelles","Indian Ocean archipelago independent from Britain in 1976.",[])
E("comoros","Union of the Comoros","polity",1975,None,True,"Comoros","Indian Ocean state independent in 1975, with numerous coups and Mayotte remaining French.",["Comoros"])
