import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _mn_common import E, ROWS, set_region
set_region('europe')

# ---------------- FRANCE ----------------
E("kingdom-of-france-early-modern","Kingdom of France (Early Modern)","polity",1500,1792,False,"France","Valois and Bourbon monarchy that centralised the French state, fought the Italian and Religious wars, and built Europe's leading absolutist power before the Revolution abolished it.",["Ancien Regime France","Royaume de France"])
E("french-wars-of-religion","French Wars of Religion","period",1562,1598,False,"France","Eight civil wars between Catholics and Huguenots that devastated France and ended with Henry IV's conversion and the Edict of Nantes.",["Huguenot Wars"])
E("reign-francis-i-france","Reign of Francis I of France","reign",1515,1547,False,"Kingdom of France","Renaissance king who fought Charles V in Italy, patronised Leonardo and Chambord, and made French the language of administration in 1539.",["Francois I"])
E("reign-henry-ii-france","Reign of Henry II of France","reign",1547,1559,False,"Kingdom of France","Ended the Italian Wars at Cateau-Cambresis in 1559 and died in a tournament accident, leaving power to Catherine de' Medici.",["Henri II"])
E("reign-francis-ii-france","Reign of Francis II of France","reign",1559,1560,False,"Kingdom of France","Teenage king married to Mary Stuart whose brief reign was dominated by the Guise faction.",["Francois II"])
E("reign-charles-ix-france","Reign of Charles IX of France","reign",1560,1574,False,"Kingdom of France","Ruled under his mother Catherine de' Medici; his reign saw the St Bartholomew's Day massacre of Huguenots in 1572.",[])
E("st-bartholomews-day-massacre","St Bartholomew's Day Massacre","event",1572,1572,False,"France","Mass killing of Huguenots in Paris and the provinces beginning 24 August 1572, a turning point in the Wars of Religion.",["Massacre de la Saint-Barthelemy"])
E("reign-henry-iii-france","Reign of Henry III of France","reign",1574,1589,False,"Kingdom of France","Last Valois king, caught between the Catholic League and Henry of Navarre; assassinated in 1589.",["Henri III"])
E("reign-henry-iv-france","Reign of Henry IV of France","reign",1589,1610,False,"Kingdom of France","First Bourbon king; converted to Catholicism, issued the Edict of Nantes in 1598 and rebuilt the kingdom before his assassination.",["Henri IV","Henry of Navarre"])
E("edict-of-nantes","Edict of Nantes","event",1598,1598,False,"France","Henry IV's grant of limited toleration and fortified towns to French Protestants, revoked in 1685.",[])
E("reign-louis-xiii","Reign of Louis XIII","reign",1610,1643,False,"Kingdom of France","Reign dominated by Cardinal Richelieu, who broke Huguenot autonomy and entered the Thirty Years' War against the Habsburgs.",[])
E("reign-louis-xiv","Reign of Louis XIV","reign",1643,1715,False,"Kingdom of France","Seventy-two-year reign of the Sun King: Versailles, absolutism, revocation of the Edict of Nantes and near-continuous European war.",["Sun King","Louis the Great"])
E("fronde","The Fronde","event",1648,1653,False,"France","Series of aristocratic and parlementaire revolts during Louis XIV's minority that hardened his commitment to absolutism.",[])
E("revocation-edict-of-nantes","Revocation of the Edict of Nantes","event",1685,1685,False,"France","Edict of Fontainebleau outlawed Protestantism and drove several hundred thousand Huguenots into exile.",["Edict of Fontainebleau"])
E("reign-louis-xv","Reign of Louis XV","reign",1715,1774,False,"Kingdom of France","Long reign marked by regency, the War of the Austrian Succession, and the loss of New France and India in the Seven Years' War.",[])
E("reign-louis-xvi","Reign of Louis XVI","reign",1774,1792,False,"Kingdom of France","Fiscal crisis and the summoning of the Estates-General led to revolution; deposed in 1792 and guillotined in 1793.",[])
E("french-revolution","French Revolution","event",1789,1799,False,"France","Collapse of the Ancien Regime: Bastille, Declaration of the Rights of Man, republic, Terror and Directory, ending with Bonaparte's coup.",["Revolution francaise"])
E("storming-of-the-bastille","Storming of the Bastille","event",1789,1789,False,"French Revolution","Parisian crowds seized the royal fortress-prison on 14 July 1789, the symbolic start of the Revolution.",[])
E("declaration-rights-of-man","Declaration of the Rights of Man and of the Citizen","event",1789,1789,False,"French Revolution","Foundational statement of natural rights adopted by the National Assembly in August 1789.",["Declaration des droits de l'homme"])
E("french-first-republic","French First Republic","polity",1792,1804,False,"France","Republic proclaimed after the fall of the monarchy, passing through Convention, Terror, Directory and Consulate before Napoleon's empire.",["Premiere Republique"])
E("reign-of-terror","Reign of Terror","period",1793,1794,False,"French First Republic","Robespierre and the Committee of Public Safety executed tens of thousands until Thermidor ended the Jacobin dictatorship.",["La Terreur"])
E("french-directory","French Directory","polity",1795,1799,False,"French First Republic","Five-man executive governing France between the Terror and Bonaparte's Brumaire coup.",["Directoire"])
E("french-consulate","French Consulate","polity",1799,1804,False,"France","Napoleon Bonaparte ruled as First Consul, creating the Bank of France, the Concordat and the Civil Code.",["Consulat"])
E("napoleonic-code","Napoleonic Code","event",1804,1804,False,"France","Civil Code of 1804 that codified French private law and became a model across Europe and Latin America.",["Code civil","Code Napoleon"])
E("first-french-empire","First French Empire","polity",1804,1815,False,"France","Napoleon I's empire, dominant over continental Europe until defeat in Russia, Leipzig and finally Waterloo.",["Premier Empire"])
E("reign-napoleon-i","Reign of Napoleon I","reign",1804,1814,False,"First French Empire","Emperor of the French who remade Europe's map and law before abdicating in 1814; briefly restored in 1815.",["Napoleon Bonaparte"])
E("hundred-days","The Hundred Days","event",1815,1815,False,"France","Napoleon's return from Elba, restored rule of about a hundred days, and final defeat at Waterloo.",["Cent-Jours"])
E("bourbon-restoration","Bourbon Restoration","polity",1814,1830,False,"France","Constitutional monarchy under Louis XVIII and Charles X, ended by the July Revolution.",["Restauration"])
E("reign-louis-xviii","Reign of Louis XVIII","reign",1814,1824,False,"Bourbon Restoration France","Restored Bourbon king who accepted the Charter of 1814 and steered a moderate course between ultras and liberals.",[])
E("reign-charles-x","Reign of Charles X of France","reign",1824,1830,False,"Bourbon Restoration France","Ultra-royalist king whose July Ordinances provoked the 1830 revolution; began the conquest of Algiers.",[])
E("july-revolution-1830","July Revolution","event",1830,1830,False,"France","Three days of Parisian fighting in July 1830 that replaced Charles X with Louis-Philippe.",["Trois Glorieuses"])
E("july-monarchy","July Monarchy","polity",1830,1848,False,"France","Bourgeois constitutional monarchy of Louis-Philippe, the 'citizen king', toppled in February 1848.",["Monarchie de Juillet"])
E("reign-louis-philippe","Reign of Louis-Philippe I","reign",1830,1848,False,"July Monarchy","Orleanist king of the French whose narrow franchise and refusal of reform ended in the February Revolution.",["Citizen King"])
E("french-second-republic","French Second Republic","polity",1848,1852,False,"France","Republic born of the February Revolution, introduced universal male suffrage, ended by Louis-Napoleon's coup.",["Deuxieme Republique"])
E("second-french-empire","Second French Empire","polity",1852,1870,False,"France","Napoleon III's authoritarian then liberal empire: Haussmann's Paris, Crimea, Italy, Mexico, and collapse at Sedan.",["Second Empire"])
E("reign-napoleon-iii","Reign of Napoleon III","reign",1852,1870,False,"Second French Empire","Emperor whose modernising rule ended in capture at Sedan and the fall of the empire.",["Louis-Napoleon Bonaparte"])
E("franco-prussian-war","Franco-Prussian War","event",1870,1871,False,"France and Germany","Prussian-led German victory that destroyed the Second Empire, annexed Alsace-Lorraine and completed German unification.",["Guerre franco-prussienne"])
E("paris-commune","Paris Commune","polity",1871,1871,False,"France","Radical revolutionary government of Paris from March to May 1871, crushed in the semaine sanglante.",["Commune de Paris"])
E("french-third-republic","French Third Republic","polity",1870,1940,False,"France","Longest-lived French republic: secular laicite laws, colonial expansion, victory in 1914-18, defeat in 1940.",["Troisieme Republique"])
E("dreyfus-affair","Dreyfus Affair","event",1894,1906,False,"French Third Republic","Wrongful conviction of a Jewish officer for treason that split France over antisemitism, army and republic.",["Affaire Dreyfus"])
E("french-law-separation-church-state","French Law on the Separation of Church and State","event",1905,1905,False,"French Third Republic","1905 law establishing laicite by ending state recognition and funding of religions.",["Loi de 1905","laicite law"])
E("vichy-france","Vichy France","polity",1940,1944,False,"France","Authoritarian French State under Marshal Petain that collaborated with Nazi Germany after the 1940 armistice.",["French State","Etat francais"])
E("free-france","Free France","polity",1940,1944,False,"France","De Gaulle's government-in-exile and its forces, which rallied the empire and the Resistance against Vichy and Germany.",["France Libre"])
E("french-provisional-government-1944","Provisional Government of the French Republic","polity",1944,1946,False,"France","De Gaulle-led government that restored republican legality, nationalised key industries and gave women the vote.",["GPRF"])
E("french-fourth-republic","French Fourth Republic","polity",1946,1958,False,"France","Unstable parliamentary republic that rebuilt the economy and began European integration but foundered on Indochina and Algeria.",["Quatrieme Republique"])
E("french-fifth-republic","French Fifth Republic","polity",1958,None,True,"France","De Gaulle's semi-presidential republic, France's current constitutional order since 1958.",["Cinquieme Republique"])
E("presidency-charles-de-gaulle","Presidency of Charles de Gaulle","reign",1959,1969,False,"French Fifth Republic","Founding president of the Fifth Republic: Algerian independence, nuclear force de frappe, NATO withdrawal, and resignation after 1968.",["de Gaulle"])
E("may-1968-france","May 1968 in France","event",1968,1968,False,"French Fifth Republic","Student revolt and general strike of ten million workers that shook de Gaulle's government.",["Mai 68"])
E("presidency-georges-pompidou","Presidency of Georges Pompidou","reign",1969,1974,False,"French Fifth Republic","Gaullist president who oversaw industrial modernisation and accepted British entry into the EEC; died in office.",[])
E("presidency-giscard-destaing","Presidency of Valery Giscard d'Estaing","reign",1974,1981,False,"French Fifth Republic","Centrist president who liberalised social law, legalised abortion and helped create the European Monetary System.",["Giscard"])
E("presidency-francois-mitterrand","Presidency of Francois Mitterrand","reign",1981,1995,False,"French Fifth Republic","First Socialist president of the Fifth Republic; nationalisations then austerity, abolition of the death penalty, Maastricht.",[])
E("presidency-jacques-chirac","Presidency of Jacques Chirac","reign",1995,2007,False,"French Fifth Republic","Gaullist president who ended conscription, adopted the euro and opposed the 2003 Iraq war.",[])
E("presidency-nicolas-sarkozy","Presidency of Nicolas Sarkozy","reign",2007,2012,False,"French Fifth Republic","Presidency marked by the 2008 financial crisis, NATO reintegration and the Libya intervention.",[])
E("presidency-francois-hollande","Presidency of Francois Hollande","reign",2012,2017,False,"French Fifth Republic","Socialist president who legalised same-sex marriage and led France through the 2015 terror attacks and COP21.",[])
E("presidency-emmanuel-macron","Presidency of Emmanuel Macron","reign",2017,None,True,"French Fifth Republic","Centrist president elected 2017 and re-elected 2022, facing gilets jaunes protests, COVID-19 and pension reform.",[])
E("french-colonial-empire","French Colonial Empire","polity",1534,1980,False,"France","Two successive empires spanning the Americas, Africa, Indochina and the Pacific, largely dissolved between 1954 and 1962.",["Empire colonial francais"])

# ---------------- GERMANY ----------------
E("holy-roman-empire-early-modern","Holy Roman Empire (Early Modern)","polity",1500,1806,False,"Germany","Loose confederation of hundreds of German states under an elected emperor, dissolved by Napoleon in 1806.",["Heiliges Romisches Reich","HRE"])
E("protestant-reformation","Protestant Reformation","era",1517,1648,False,"Europe","Luther's challenge to Rome split Western Christianity and reshaped European politics, education and warfare.",["Reformation"])
E("peace-of-augsburg","Peace of Augsburg","event",1555,1555,False,"Holy Roman Empire","Settlement letting each German prince choose Lutheranism or Catholicism for his territory, cuius regio eius religio.",[])
E("thirty-years-war","Thirty Years' War","event",1618,1648,False,"Central Europe","Religious and dynastic war fought largely in Germany that killed a large share of its population and ended Habsburg hegemony.",["Dreissigjahriger Krieg"])
E("defenestration-of-prague-1618","Defenestration of Prague","event",1618,1618,False,"Bohemia","Bohemian Protestants threw imperial regents from a castle window, triggering the Thirty Years' War.",[])
E("peace-of-westphalia","Peace of Westphalia","event",1648,1648,False,"Europe","Treaties of Munster and Osnabruck that ended the Thirty Years' War and framed the modern system of sovereign states.",["Westfalischer Friede"])
E("brandenburg-prussia","Brandenburg-Prussia","polity",1618,1701,False,"Germany","Hohenzollern union of Brandenburg and Prussia built into a military-bureaucratic state by the Great Elector.",[])
E("kingdom-of-prussia","Kingdom of Prussia","polity",1701,1918,False,"Germany","Hohenzollern kingdom that rose to great-power status, led German unification and dominated the German Empire.",["Konigreich Preussen"])
E("reign-frederick-the-great","Reign of Frederick the Great","reign",1740,1786,False,"Kingdom of Prussia","Frederick II seized Silesia, survived the Seven Years' War and made Prussia a great power while patronising the Enlightenment.",["Frederick II of Prussia","Friedrich der Grosse"])
E("silesian-wars","Silesian Wars","event",1740,1763,False,"Prussia and Austria","Three wars in which Prussia took and kept Silesia from Habsburg Austria.",[])
E("confederation-of-the-rhine","Confederation of the Rhine","polity",1806,1813,False,"Germany","Napoleonic client league of German states whose creation ended the Holy Roman Empire.",["Rheinbund"])
E("german-confederation","German Confederation","polity",1815,1866,False,"Germany","Loose association of 39 German states created at Vienna under Austrian presidency, dissolved after the 1866 war.",["Deutscher Bund"])
E("zollverein","Zollverein","polity",1834,1871,False,"Germany","Prussian-led customs union that economically integrated Germany ahead of political unification.",["German Customs Union"])
E("frankfurt-parliament","Frankfurt Parliament","event",1848,1849,False,"Germany","First freely elected all-German assembly; drafted a liberal constitution that Prussia's king refused.",["Frankfurt National Assembly"])
E("austro-prussian-war","Austro-Prussian War","event",1866,1866,False,"Germany","Seven Weeks' War in which Prussia's victory at Koniggratz excluded Austria from Germany.",["Seven Weeks War"])
E("north-german-confederation","North German Confederation","polity",1867,1871,False,"Germany","Prussian-dominated federal state that became the framework for the German Empire.",["Norddeutscher Bund"])
E("german-unification","German Unification of 1871","event",1871,1871,False,"Germany","Proclamation of the German Empire at Versailles on 18 January 1871, completing Bismarck's unification by war and diplomacy.",["Reichsgrundung"])
E("german-empire","German Empire","polity",1871,1918,False,"Germany","Federal Hohenzollern empire, Europe's leading industrial and military power, which collapsed in revolution in November 1918.",["Deutsches Kaiserreich","Second Reich"])
E("reign-wilhelm-i","Reign of Wilhelm I","reign",1871,1888,False,"German Empire","First German emperor, whose reign under Bismarck saw unification, the Kulturkampf and the first welfare state.",["William I of Germany"])
E("bismarck-chancellorship","Bismarck's Chancellorship","reign",1871,1890,False,"German Empire","Otto von Bismarck governed the new empire, building alliances abroad and social insurance and anti-socialist laws at home.",["Otto von Bismarck"])
E("year-of-three-emperors","Year of the Three Emperors","event",1888,1888,False,"German Empire","Wilhelm I, Friedrich III and Wilhelm II all reigned in 1888; Friedrich III ruled only 99 days.",["Dreikaiserjahr"])
E("reign-wilhelm-ii","Reign of Wilhelm II","reign",1888,1918,False,"German Empire","Last German emperor: naval race, Weltpolitik, the First World War and abdication in November 1918.",["Kaiser Wilhelm II"])
E("german-revolution-1918","German Revolution of 1918-19","event",1918,1919,False,"Germany","Naval mutiny and workers' councils toppled the monarchy and produced the Weimar Republic amid failed communist risings.",["Novemberrevolution"])
E("weimar-republic","Weimar Republic","polity",1919,1933,False,"Germany","Germany's first democracy: hyperinflation, Ruhr occupation, Weimar culture, then depression and Nazi takeover.",["Weimarer Republik"])
E("german-hyperinflation-1923","German Hyperinflation of 1923","event",1923,1923,False,"Weimar Republic","Currency collapse that destroyed savings and discredited the young republic before the Rentenmark stabilisation.",[])
E("beer-hall-putsch","Beer Hall Putsch","event",1923,1923,False,"Weimar Republic","Hitler's failed Munich coup, after which he wrote Mein Kampf in prison.",["Munich Putsch"])
E("nazi-germany","Nazi Germany","polity",1933,1945,False,"Germany","Hitler's totalitarian Third Reich: rearmament, persecution, conquest of Europe, the Holocaust and total defeat.",["Third Reich","Drittes Reich"])
E("hitler-chancellorship","Hitler's Rule of Germany","reign",1933,1945,False,"Nazi Germany","Adolf Hitler as chancellor and Fuhrer held dictatorial power from 1933 until his suicide in Berlin in April 1945.",["Adolf Hitler"])
E("nuremberg-laws","Nuremberg Laws","event",1935,1935,False,"Nazi Germany","Racial laws stripping German Jews of citizenship and criminalising intermarriage.",["Nurnberger Gesetze"])
E("anschluss","Anschluss","event",1938,1938,False,"Germany and Austria","German annexation of Austria in March 1938, endorsed by a rigged plebiscite.",["Annexation of Austria"])
E("kristallnacht","Kristallnacht","event",1938,1938,False,"Nazi Germany","November 1938 pogrom that destroyed synagogues and Jewish businesses across Germany and Austria.",["Night of Broken Glass"])
E("munich-agreement","Munich Agreement","event",1938,1938,False,"Europe","Britain, France, Germany and Italy ceded the Sudetenland to Hitler, the high point of appeasement.",["Munich Conference"])
E("molotov-ribbentrop-pact","Molotov-Ribbentrop Pact","event",1939,1939,False,"Germany and Soviet Union","Nazi-Soviet non-aggression pact with secret protocols dividing Eastern Europe, signed days before war.",["Nazi-Soviet Pact"])
E("allied-occupation-of-germany","Allied Occupation of Germany","period",1945,1949,False,"Germany","Four-power division of Germany, denazification, the Nuremberg trials and the Berlin airlift, ending with two German states.",["Besatzungszeit"])
E("nuremberg-trials","Nuremberg Trials","event",1945,1946,False,"Germany","International Military Tribunal that tried surviving Nazi leaders and established modern precedents for crimes against humanity.",[])
E("berlin-blockade","Berlin Blockade and Airlift","event",1948,1949,False,"Germany","Soviet closure of land routes to West Berlin, defeated by an eleven-month Western airlift.",["Berlin Airlift"])
E("west-germany","Federal Republic of Germany (West Germany)","polity",1949,1990,False,"Germany","Democratic western state founded in 1949; Wirtschaftswunder, NATO membership and Ostpolitik until reunification.",["Bundesrepublik Deutschland","West Germany"])
E("east-germany","German Democratic Republic (East Germany)","polity",1949,1990,False,"Germany","Communist state in the Soviet zone, ruled by the SED, dissolved when it acceded to the Federal Republic in 1990.",["DDR","GDR","East Germany"])
E("east-german-uprising-1953","East German Uprising of 1953","event",1953,1953,False,"East Germany","Workers' strikes and protests on 17 June 1953 crushed by Soviet tanks.",[])
E("berlin-wall","Berlin Wall","polity",1961,1989,False,"Germany","Fortified barrier sealing West Berlin from 1961, the Cold War's central symbol, opened on 9 November 1989.",["Berliner Mauer"])
E("chancellorship-konrad-adenauer","Chancellorship of Konrad Adenauer","reign",1949,1963,False,"West Germany","First West German chancellor: Western integration, NATO entry, reconciliation with France and Israel.",[])
E("chancellorship-ludwig-erhard","Chancellorship of Ludwig Erhard","reign",1963,1966,False,"West Germany","Architect of the social market economy who succeeded Adenauer as chancellor.",[])
E("chancellorship-kurt-georg-kiesinger","Chancellorship of Kurt Georg Kiesinger","reign",1966,1969,False,"West Germany","Led the first grand coalition of CDU and SPD.",[])
E("chancellorship-willy-brandt","Chancellorship of Willy Brandt","reign",1969,1974,False,"West Germany","Social Democrat who pursued Ostpolitik, knelt at the Warsaw Ghetto memorial and won the Nobel Peace Prize.",[])
E("chancellorship-helmut-schmidt","Chancellorship of Helmut Schmidt","reign",1974,1982,False,"West Germany","Managed oil shocks, the Red Army Faction's German Autumn and NATO's missile deployment.",[])
E("chancellorship-helmut-kohl","Chancellorship of Helmut Kohl","reign",1982,1998,False,"Germany","Longest-serving postwar chancellor; delivered reunification in 1990 and pushed the euro at Maastricht.",[])
E("german-reunification","German Reunification","event",1990,1990,False,"Germany","On 3 October 1990 the GDR acceded to the Federal Republic under the Two Plus Four Treaty.",["Wiedervereinigung","Die Wende"])
E("federal-republic-of-germany","Federal Republic of Germany","polity",1990,None,True,"Germany","Reunified democratic Germany, the European Union's largest economy, with its capital returned to Berlin.",["Germany","Bundesrepublik Deutschland"])
E("chancellorship-gerhard-schroder","Chancellorship of Gerhard Schroder","reign",1998,2005,False,"Germany","SPD-Green government: Kosovo deployment, Agenda 2010 labour reforms, refusal to join the Iraq war.",[])
E("chancellorship-angela-merkel","Chancellorship of Angela Merkel","reign",2005,2021,False,"Germany","First woman chancellor; steered Germany through the eurozone crisis, the 2015 refugee influx and COVID-19.",[])
E("chancellorship-olaf-scholz","Chancellorship of Olaf Scholz","reign",2021,2025,False,"Germany","Led a three-party coalition through the Zeitenwende response to Russia's invasion of Ukraine and an energy crisis.",[])
E("chancellorship-friedrich-merz","Chancellorship of Friedrich Merz","reign",2025,None,True,"Germany","CDU chancellor from 2025 heading a coalition with the Social Democrats.",[],"medium")

# ---------------- ITALY ----------------
E("italian-wars","Italian Wars","event",1494,1559,False,"Italy","Six decades of conflict over Italy between France, Spain and the Habsburgs, ending in Spanish dominance of the peninsula.",["Habsburg-Valois Wars"])
E("republic-of-venice-modern","Republic of Venice (late)","polity",1500,1797,False,"Italy","Declining maritime republic that lost Cyprus and Crete to the Ottomans and was extinguished by Napoleon in 1797.",["Serenissima"])
E("republic-of-genoa-modern","Republic of Genoa (late)","polity",1500,1797,False,"Italy","Banking and maritime republic tied to Habsburg Spain, annexed to Napoleon's Ligurian Republic.",[])
E("grand-duchy-of-tuscany","Grand Duchy of Tuscany","polity",1569,1859,False,"Italy","Medici then Habsburg-Lorraine state centred on Florence, absorbed into unified Italy.",["Granducato di Toscana"])
E("papal-states-modern","Papal States (Early Modern to 1870)","polity",1500,1870,False,"Italy","Territorial dominion of the popes across central Italy, reduced in 1860 and ended by the capture of Rome in 1870.",["Stato Pontificio"])
E("duchy-of-milan-spanish","Spanish then Austrian Milan","polity",1535,1796,False,"Italy","Duchy of Milan ruled by Habsburg Spain and then Austria before the Napoleonic conquest.",[])
E("kingdom-of-naples-modern","Kingdom of Naples (Early Modern)","polity",1504,1816,False,"Italy","Spanish then Austrian then Bourbon kingdom of southern Italy, merged into the Two Sicilies in 1816.",[])
E("kingdom-of-two-sicilies","Kingdom of the Two Sicilies","polity",1816,1861,False,"Italy","Bourbon kingdom of southern Italy and Sicily, conquered by Garibaldi's volunteers in 1860.",["Regno delle Due Sicilie"])
E("kingdom-of-sardinia","Kingdom of Sardinia","polity",1720,1861,False,"Italy","Savoyard state based in Piedmont that led the Risorgimento and became the Kingdom of Italy.",["Piedmont-Sardinia"])
E("risorgimento","Risorgimento","era",1815,1871,False,"Italy","Movement of ideas, wars and diplomacy that unified Italy under the House of Savoy.",["Italian unification movement"])
E("first-italian-war-independence","First Italian War of Independence","event",1848,1849,False,"Italy","Piedmontese and revolutionary attempt to expel Austria from northern Italy, defeated at Custoza and Novara.",[])
E("roman-republic-1849","Roman Republic of 1849","polity",1849,1849,False,"Italy","Short-lived republic led by Mazzini and defended by Garibaldi until French troops restored the Pope.",[])
E("second-italian-war-independence","Second Italian War of Independence","event",1859,1859,False,"Italy","Franco-Piedmontese victory over Austria at Magenta and Solferino won Lombardy for Piedmont.",[])
E("expedition-of-the-thousand","Expedition of the Thousand","event",1860,1860,False,"Italy","Garibaldi's volunteers conquered Sicily and Naples and handed the south to Victor Emmanuel II.",["Spedizione dei Mille","Garibaldi's march"])
E("kingdom-of-italy","Kingdom of Italy","polity",1861,1946,False,"Italy","Unified Italian monarchy proclaimed in 1861, which annexed Venetia and Rome, fought both world wars and fell to fascism.",["Regno d'Italia"])
E("reign-victor-emmanuel-ii","Reign of Victor Emmanuel II","reign",1861,1878,False,"Kingdom of Italy","First king of united Italy, who annexed Venetia in 1866 and Rome in 1870.",["Vittorio Emanuele II"])
E("third-italian-war-independence","Third Italian War of Independence","event",1866,1866,False,"Italy","Italy's war alongside Prussia against Austria, which gained Venetia despite defeats at Custoza and Lissa.",[])
E("capture-of-rome-1870","Capture of Rome","event",1870,1870,False,"Italy","Italian troops breached Porta Pia on 20 September 1870, ending papal temporal rule and completing unification.",["Breach of Porta Pia"])
E("reign-umberto-i","Reign of Umberto I","reign",1878,1900,False,"Kingdom of Italy","King during colonial expansion in Eritrea and the defeat at Adwa; assassinated by an anarchist in 1900.",[])
E("reign-victor-emmanuel-iii","Reign of Victor Emmanuel III","reign",1900,1946,False,"Kingdom of Italy","King who took Italy into the First World War, appointed Mussolini, dismissed him in 1943 and abdicated in 1946.",["Vittorio Emanuele III"])
E("italo-turkish-war","Italo-Turkish War","event",1911,1912,False,"Italy and Ottoman Empire","Italian conquest of Libya and the Dodecanese from the Ottomans.",[])
E("march-on-rome","March on Rome","event",1922,1922,False,"Italy","Fascist mobilisation that led the king to appoint Mussolini prime minister in October 1922.",["Marcia su Roma"])
E("fascist-italy","Fascist Italy","polity",1922,1943,False,"Italy","Mussolini's one-party regime: Lateran Pacts, Ethiopian conquest, Axis alliance and wartime collapse.",["Italy under Mussolini"])
E("lateran-treaty","Lateran Treaty","event",1929,1929,False,"Italy and the Holy See","Agreement creating Vatican City and settling the Roman Question between Italy and the papacy.",["Lateran Pacts"])
E("vatican-city","Vatican City","polity",1929,None,True,"Italy","Sovereign city-state created in 1929 as the seat of the papacy, the world's smallest state.",["Holy See","Stato della Citta del Vaticano"])
E("italian-social-republic","Italian Social Republic","polity",1943,1945,False,"Italy","German-backed Salo Republic under Mussolini in northern Italy, fought by the partisan Resistance.",["Salo Republic","RSI"])
E("italian-republic","Italian Republic","polity",1946,None,True,"Italy","Republic established by the 1946 referendum, a founding member of NATO and the European communities.",["Repubblica Italiana","Italy"])
E("italian-years-of-lead","Years of Lead","period",1969,1988,False,"Italian Republic","Two decades of left- and right-wing terrorism in Italy, including the Red Brigades' murder of Aldo Moro.",["Anni di piombo"])
E("san-marino-modern","Republic of San Marino","polity",1500,None,True,"Italy","Ancient micro-republic in the Apennines that preserved independence through Italian unification.",[])
E("monaco-modern","Principality of Monaco","polity",1861,None,True,"Europe","Grimaldi principality on the Riviera whose sovereignty was confirmed in 1861 under French protection.",[])

# ---------------- SPAIN & PORTUGAL ----------------
E("habsburg-spain","Habsburg Spain","polity",1516,1700,False,"Spain","Spain under the Austrias, ruling a global empire from the Americas to the Philippines before dynastic extinction in 1700.",["Spain of the Austrias"])
E("spanish-empire","Spanish Empire","polity",1492,1898,False,"Spain","Global empire of the Americas, Philippines and Pacific, dissolved by Latin American independence and 1898.",["Imperio Espanol"])
E("reign-charles-v-spain","Reign of Charles V","reign",1516,1556,False,"Habsburg Spain","Ruled Spain, the Netherlands, Naples and the Holy Roman Empire; faced Luther and the Ottomans before abdicating.",["Carlos I","Charles I of Spain"])
E("reign-philip-ii-spain","Reign of Philip II of Spain","reign",1556,1598,False,"Habsburg Spain","Height of Spanish power: Lepanto, annexation of Portugal, the Dutch Revolt and the Armada's failure.",["Felipe II"])
E("spanish-armada","Spanish Armada","event",1588,1588,False,"Spain","Philip II's invasion fleet against England, scattered by battle and storms.",["Invincible Armada"])
E("reign-philip-iii-spain","Reign of Philip III of Spain","reign",1598,1621,False,"Habsburg Spain","Reign of truce with the Dutch and the expulsion of the Moriscos.",[])
E("reign-philip-iv-spain","Reign of Philip IV of Spain","reign",1621,1665,False,"Habsburg Spain","Golden-age culture amid decline: loss of the Dutch and Portugal, Catalan revolt and defeat by France.",[])
E("reign-charles-ii-spain","Reign of Charles II of Spain","reign",1665,1700,False,"Habsburg Spain","Last Habsburg king of Spain, childless, whose death triggered the War of the Spanish Succession.",["El Hechizado"])
E("war-of-spanish-succession","War of the Spanish Succession","event",1701,1714,False,"Europe","European war over the Spanish throne that installed the Bourbons and ceded Gibraltar and the Netherlands.",[])
E("bourbon-spain","Bourbon Spain","polity",1700,1808,False,"Spain","Reforming Bourbon monarchy that centralised administration and reorganised the American empire.",[])
E("reign-charles-iii-spain","Reign of Charles III of Spain","reign",1759,1788,False,"Bourbon Spain","Enlightened absolutist who reformed the empire, expelled the Jesuits and modernised Madrid.",["Carlos III"])
E("peninsular-war","Peninsular War","event",1808,1814,False,"Iberia","Spanish, Portuguese and British resistance to Napoleon's occupation of Iberia, a decisive drain on the French empire.",["Spanish War of Independence"])
E("cadiz-constitution-1812","Constitution of Cadiz","event",1812,1812,False,"Spain","Liberal constitution of 1812 that inspired constitutionalism across Spain and Latin America.",["La Pepa"])
E("carlist-wars","Carlist Wars","event",1833,1876,False,"Spain","Three dynastic civil wars between supporters of Don Carlos and the liberal monarchy of Isabella II.",[])
E("reign-isabella-ii","Reign of Isabella II of Spain","reign",1833,1868,False,"Spain","Turbulent reign of civil war and pronunciamientos, ended by the Glorious Revolution of 1868.",["Isabel II"])
E("first-spanish-republic","First Spanish Republic","polity",1873,1874,False,"Spain","Short-lived federal republic with four presidents in eleven months, ended by a military coup.",["Primera Republica"])
E("bourbon-restoration-spain","Bourbon Restoration in Spain","polity",1874,1931,False,"Spain","Restored monarchy under Alfonso XII and Alfonso XIII with alternating parties, the 1898 disaster and Rivera's dictatorship.",[])
E("spanish-american-war-1898","Spanish-American War","event",1898,1898,False,"Spain and the Americas","War that stripped Spain of Cuba, Puerto Rico, Guam and the Philippines, the 'Disaster of 98'.",["Desastre del 98"])
E("primo-de-rivera-dictatorship","Dictatorship of Primo de Rivera","reign",1923,1930,False,"Spain","Military dictatorship under Alfonso XIII that modernised infrastructure but collapsed in the Depression.",[])
E("second-spanish-republic","Second Spanish Republic","polity",1931,1939,False,"Spain","Democratic republic of land reform, regional autonomy and polarisation, destroyed by the Civil War.",["Segunda Republica"])
E("spanish-civil-war","Spanish Civil War","event",1936,1939,False,"Spain","Nationalist rebels under Franco, aided by Germany and Italy, defeated the Republic, aided by the USSR and volunteers.",["Guerra Civil Espanola"])
E("francoist-spain","Francoist Spain","polity",1939,1975,False,"Spain","Franco's authoritarian regime: repression, autarky then technocratic growth, ending with his death in 1975.",["Franco dictatorship","Estado Espanol"])
E("spanish-transition","Spanish Transition to Democracy","period",1975,1982,False,"Spain","Dismantling of Francoism under Juan Carlos I and Adolfo Suarez, producing the 1978 constitution.",["la Transicion"])
E("kingdom-of-spain","Kingdom of Spain","polity",1975,None,True,"Spain","Parliamentary monarchy since Franco's death, a member of the EU since 1986 and NATO since 1982.",["Spain","Espana"])
E("reign-juan-carlos-i","Reign of Juan Carlos I","reign",1975,2014,False,"Kingdom of Spain","King who oversaw the democratic transition and faced down the 1981 coup attempt; abdicated in 2014.",[])
E("reign-felipe-vi","Reign of Felipe VI","reign",2014,None,True,"Kingdom of Spain","King since 2014, whose reign has confronted the Catalan independence crisis of 2017.",[])
E("catalan-independence-crisis","Catalan Independence Crisis","event",2017,2017,False,"Spain","Unauthorised referendum and unilateral declaration in Catalonia met by direct rule from Madrid.",[])
E("portuguese-empire","Portuguese Empire","polity",1415,1999,False,"Portugal","First and longest-lived European seaborne empire, from Ceuta and Goa to Brazil, Angola and Macau.",["Imperio Portugues"])
E("iberian-union","Iberian Union","polity",1580,1640,False,"Portugal and Spain","Sixty years in which Habsburg kings of Spain also ruled Portugal and its empire.",["Uniao Iberica"])
E("portuguese-restoration-war","Portuguese Restoration War","event",1640,1668,False,"Portugal","Revolt that installed the House of Braganza and won recognition of Portuguese independence from Spain.",["Guerra da Restauracao"])
E("house-of-braganza","House of Braganza","polity",1640,1910,False,"Portugal","Dynasty that ruled Portugal and later Brazil until the republican revolution of 1910.",["Bragancas"])
E("lisbon-earthquake-1755","Lisbon Earthquake","event",1755,1755,False,"Portugal","Earthquake, tsunami and fire that destroyed Lisbon and prompted Pombal's rebuilding and Enlightenment debate.",[])
E("portuguese-1910-revolution","Portuguese Republican Revolution","event",1910,1910,False,"Portugal","Lisbon rising that deposed Manuel II and established the First Portuguese Republic.",[])
E("portuguese-first-republic","First Portuguese Republic","polity",1910,1926,False,"Portugal","Unstable republic with dozens of governments, ended by the 28 May military coup.",[])
E("estado-novo-portugal","Estado Novo (Portugal)","polity",1933,1974,False,"Portugal","Salazar's corporatist dictatorship, which clung to the African colonies until the Carnation Revolution.",["Salazar regime"])
E("portuguese-colonial-war","Portuguese Colonial War","event",1961,1974,False,"Portugal and Africa","Thirteen-year war against independence movements in Angola, Mozambique and Guinea-Bissau that broke the Estado Novo.",["Overseas War","Guerra do Ultramar"])
E("carnation-revolution","Carnation Revolution","event",1974,1974,False,"Portugal","Bloodless captains' coup of 25 April 1974 that ended dictatorship and led to decolonisation.",["25 de Abril"])
E("portuguese-third-republic","Portuguese Republic","polity",1976,None,True,"Portugal","Democratic republic under the 1976 constitution, an EU member since 1986 and euro founder.",["Portugal"])

# ---------------- LOW COUNTRIES ----------------
E("dutch-revolt","Dutch Revolt","event",1568,1648,False,"Netherlands","Eighty Years' War in which the northern Netherlands won independence from Habsburg Spain.",["Eighty Years War"])
E("union-of-utrecht","Union of Utrecht","event",1579,1579,False,"Netherlands","Alliance of northern provinces that became the constitutional basis of the Dutch Republic.",[])
E("dutch-republic","Dutch Republic","polity",1581,1795,False,"Netherlands","Republic of the Seven United Provinces: a commercial, naval and financial superpower of the 17th century.",["United Provinces","Republiek der Zeven Verenigde Nederlanden"])
E("dutch-golden-age","Dutch Golden Age","era",1588,1672,False,"Netherlands","Era of Dutch commercial primacy, Rembrandt and Vermeer, Spinoza, and global trading empire.",["Gouden Eeuw"])
E("dutch-east-india-company","Dutch East India Company","polity",1602,1799,False,"Netherlands","Chartered company with sovereign powers that dominated Asian trade and founded Batavia and the Cape.",["VOC"])
E("dutch-west-india-company","Dutch West India Company","polity",1621,1792,False,"Netherlands","Chartered company that ran Dutch Brazil, New Netherland and the Atlantic slave trade.",["WIC"])
E("dutch-rampjaar","Disaster Year of 1672","event",1672,1672,False,"Dutch Republic","French, English and German attack that nearly destroyed the Republic and brought William III to power.",["Rampjaar"])
E("batavian-republic","Batavian Republic","polity",1795,1806,False,"Netherlands","French-sponsored revolutionary republic that replaced the Dutch Republic.",["Bataafse Republiek"])
E("kingdom-of-holland","Kingdom of Holland","polity",1806,1810,False,"Netherlands","Napoleonic kingdom under Louis Bonaparte, annexed to France in 1810.",[])
E("united-kingdom-netherlands","United Kingdom of the Netherlands","polity",1815,1839,False,"Low Countries","Congress of Vienna state joining the Dutch and Belgian provinces under William I, split by Belgian independence.",[])
E("kingdom-of-the-netherlands","Kingdom of the Netherlands","polity",1815,None,True,"Netherlands","Constitutional monarchy under the House of Orange-Nassau, a founding member of NATO and the European communities.",["Holland","Nederland"])
E("reign-william-i-netherlands","Reign of William I of the Netherlands","reign",1815,1840,False,"Kingdom of the Netherlands","First Dutch king; lost Belgium in 1830-39 and abdicated in 1840.",[])
E("dutch-constitution-1848","Dutch Constitutional Reform of 1848","event",1848,1848,False,"Netherlands","Thorbecke's revision created ministerial responsibility and parliamentary government.",[])
E("reign-wilhelmina","Reign of Queen Wilhelmina","reign",1890,1948,False,"Kingdom of the Netherlands","Queen through both world wars who led resistance broadcasts from London exile.",[])
E("dutch-famine-1944","Dutch Hunger Winter","event",1944,1945,False,"Netherlands","Famine in German-occupied western Netherlands that killed some 20,000 people.",["Hongerwinter"])
E("reign-juliana","Reign of Queen Juliana","reign",1948,1980,False,"Kingdom of the Netherlands","Queen during Indonesian independence, the 1953 North Sea flood and postwar reconstruction.",[])
E("reign-beatrix","Reign of Queen Beatrix","reign",1980,2013,False,"Kingdom of the Netherlands","Queen for 33 years, abdicating in favour of her son in 2013.",[])
E("reign-willem-alexander","Reign of King Willem-Alexander","reign",2013,None,True,"Kingdom of the Netherlands","Dutch king since 2013.",[])
E("spanish-netherlands","Spanish Netherlands","polity",1556,1714,False,"Low Countries","Habsburg Spanish provinces of the southern Low Countries, roughly modern Belgium and Luxembourg.",[])
E("austrian-netherlands","Austrian Netherlands","polity",1714,1794,False,"Low Countries","Habsburg Austrian rule over the southern Low Countries, disrupted by the Brabant Revolution and French annexation.",[])
E("belgian-revolution","Belgian Revolution","event",1830,1830,False,"Belgium","Brussels rising against Dutch rule that created an independent, neutral Belgium recognised in 1839.",[])
E("kingdom-of-belgium","Kingdom of Belgium","polity",1830,None,True,"Belgium","Constitutional monarchy independent since 1830, twice invaded by Germany, now a federal state and EU seat.",["Belgium","Belgique","Belgie"])
E("reign-leopold-i-belgium","Reign of Leopold I of Belgium","reign",1831,1865,False,"Kingdom of Belgium","First king of the Belgians, who secured recognition and neutrality for the new state.",[])
E("reign-leopold-ii-belgium","Reign of Leopold II of Belgium","reign",1865,1909,False,"Kingdom of Belgium","King who ran the Congo Free State as personal property, causing mass death, and industrialised Belgium.",[])
E("reign-albert-i-belgium","Reign of Albert I of Belgium","reign",1909,1934,False,"Kingdom of Belgium","Knight-king who led Belgian resistance to the German invasion of 1914.",[])
E("reign-leopold-iii-belgium","Reign of Leopold III of Belgium","reign",1934,1951,False,"Kingdom of Belgium","Surrendered in 1940 and remained in occupied Belgium; abdicated after the postwar Royal Question.",[])
E("reign-baudouin","Reign of King Baudouin","reign",1951,1993,False,"Kingdom of Belgium","King during Congolese independence and the federalisation of Belgium.",["Boudewijn"])
E("belgian-federalisation","Federalisation of Belgium","period",1970,1993,False,"Belgium","Series of state reforms that turned unitary Belgium into a federation of language communities and regions.",[])
E("grand-duchy-of-luxembourg","Grand Duchy of Luxembourg","polity",1815,None,True,"Luxembourg","Grand duchy created at Vienna, fully independent since 1839-1890, a founding member of the European communities.",["Luxembourg"])

# ---------------- SWITZERLAND ----------------
E("old-swiss-confederacy","Old Swiss Confederacy","polity",1500,1798,False,"Switzerland","League of thirteen cantons whose independence from the Empire was recognised in 1648 and which pioneered armed neutrality.",["Alte Eidgenossenschaft"])
E("swiss-reformation","Swiss Reformation","event",1519,1531,False,"Switzerland","Zwingli in Zurich and later Calvin in Geneva made Switzerland a centre of Reformed Protestantism.",["Zwingli reformation"])
E("helvetic-republic","Helvetic Republic","polity",1798,1803,False,"Switzerland","French-imposed centralised republic that replaced the cantonal confederacy.",["Helvetische Republik"])
E("swiss-confederation-1815","Restored Swiss Confederation","polity",1815,1848,False,"Switzerland","Confederation of 22 cantons whose perpetual neutrality was guaranteed at the Congress of Vienna.",[])
E("sonderbund-war","Sonderbund War","event",1847,1847,False,"Switzerland","Brief civil war in which federal forces defeated a league of Catholic cantons, clearing the way for the 1848 constitution.",[])
E("swiss-confederation","Swiss Confederation","polity",1848,None,True,"Switzerland","Federal state created by the 1848 constitution, neutral, directly democratic and home to many international bodies.",["Switzerland","Schweiz","Suisse"])
E("swiss-womens-suffrage","Swiss Women's Suffrage","event",1971,1971,False,"Switzerland","Federal referendum granting women the vote, among the last in Europe.",[])
E("liechtenstein","Principality of Liechtenstein","polity",1719,None,True,"Europe","Alpine principality created in 1719, sovereign since 1806 and closely tied to Switzerland.",[])
E("andorra","Principality of Andorra","polity",1500,None,True,"Europe","Pyrenean co-principality under the Spanish bishop of Urgell and the French head of state; parliamentary since 1993.",[])
