import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _mn_common import E, ROWS, set_region
set_region('west-asia')

# ---------------- OTTOMAN EMPIRE & TURKEY ----------------
E("ottoman-empire-early-modern","Ottoman Empire (Early Modern)","period",1500,1699,False,"Ottoman Empire","Height of Ottoman power from Selim I's conquests to the Treaty of Karlowitz, spanning three continents.",["Osmanli Devleti"])
E("reign-selim-i","Reign of Selim I","reign",1512,1520,False,"Ottoman Empire","Conquered the Mamluk sultanate and the Hejaz, bringing the caliphate and holy cities under Ottoman rule.",["Selim the Grim"])
E("reign-suleiman-magnificent","Reign of Suleiman the Magnificent","reign",1520,1566,False,"Ottoman Empire","Longest-reigning sultan: conquest of Belgrade, Rhodes and Hungary, legal codification and the siege of Vienna.",["Kanuni Sultan Suleyman"])
E("battle-of-lepanto","Battle of Lepanto","event",1571,1571,False,"Mediterranean","Holy League naval victory over the Ottoman fleet that ended the myth of Ottoman invincibility at sea.",[])
E("ottoman-sultanate-of-women","Sultanate of Women","period",1533,1656,False,"Ottoman Empire","Period when imperial mothers and consorts exercised great political power in the Ottoman court.",["Kadinlar Saltanati"])
E("treaty-of-karlowitz","Treaty of Karlowitz","event",1699,1699,False,"Ottoman Empire","First treaty in which the Ottomans ceded major territory, giving Hungary to the Habsburgs.",[])
E("ottoman-decline","Ottoman Decline and Reform","period",1699,1839,False,"Ottoman Empire","Territorial losses to Russia and Austria, Janissary revolts, and the reforming reigns of Selim III and Mahmud II.",[])
E("reign-mahmud-ii","Reign of Mahmud II","reign",1808,1839,False,"Ottoman Empire","Destroyed the Janissaries in 1826 and began sweeping military and administrative Westernisation.",[])
E("tanzimat","Tanzimat","era",1839,1876,False,"Ottoman Empire","Reform era of legal equality, codified law, conscription and centralisation.",["Ottoman reform era"])
E("ottoman-first-constitutional-era","First Ottoman Constitutional Era","period",1876,1878,False,"Ottoman Empire","Brief constitutional government under the 1876 Kanun-i Esasi, suspended by Abdulhamid II.",[])
E("reign-abdulhamid-ii","Reign of Abdulhamid II","reign",1876,1909,False,"Ottoman Empire","Autocratic sultan of railways and pan-Islamism who suspended parliament and was deposed by the Young Turks.",[])
E("young-turk-revolution","Young Turk Revolution","event",1908,1908,False,"Ottoman Empire","Committee of Union and Progress forced the restoration of the constitution and parliament.",[])
E("ottoman-entry-first-world-war","Ottoman Entry into the First World War","event",1914,1914,False,"Ottoman Empire","Alliance with Germany brought campaigns at Gallipoli, in Mesopotamia, the Caucasus and Palestine.",[])
E("gallipoli-campaign","Gallipoli Campaign","event",1915,1916,False,"Ottoman Empire","Allied failure to force the Dardanelles, a formative event for Turkish, Australian and New Zealand identity.",["Dardanelles campaign"])
E("armenian-genocide","Armenian Genocide","event",1915,1917,False,"Ottoman Empire","Systematic deportation and killing of about 1.5 million Armenians, alongside Assyrians and Greeks.",["Medz Yeghern"])
E("arab-revolt","Arab Revolt","event",1916,1918,False,"West Asia","Hashemite rising against Ottoman rule, encouraged by Britain and aided by T. E. Lawrence.",[])
E("sykes-picot-agreement","Sykes-Picot Agreement","event",1916,1916,False,"West Asia","Secret Anglo-French plan to divide Ottoman Arab lands, the basis of later mandate borders.",[])
E("treaty-of-sevres","Treaty of Sevres","event",1920,1920,False,"Ottoman Empire","Punitive partition treaty rejected by the Turkish nationalists and superseded by Lausanne.",[])
E("turkish-war-of-independence","Turkish War of Independence","event",1919,1923,False,"Turkey","Kemal's nationalist campaign against Greek, Armenian and French forces that saved Anatolian sovereignty.",[])
E("abolition-of-ottoman-sultanate","Abolition of the Ottoman Sultanate and Caliphate","event",1922,1924,False,"Turkey","The sultanate ended in 1922 and the caliphate in 1924, closing six centuries of Ottoman rule.",[])
E("treaty-of-lausanne","Treaty of Lausanne","event",1923,1923,False,"Turkey","Settlement recognising the Turkish republic's borders and mandating population exchange with Greece.",[])
E("republic-of-turkey","Republic of Turkey","polity",1923,None,True,"Turkey","Secular republic founded by Ataturk on 29 October 1923, a NATO member since 1952.",["Turkey","Turkiye"])
E("ataturk-presidency","Presidency of Mustafa Kemal Ataturk","reign",1923,1938,False,"Republic of Turkey","Founding president who abolished the caliphate, latinised the alphabet, secularised law and enfranchised women.",["Mustafa Kemal"])
E("inonu-presidency","Presidency of Ismet Inonu","reign",1938,1950,False,"Republic of Turkey","Kept Turkey neutral in the Second World War and permitted the transition to multiparty democracy.",[])
E("turkish-coups","Turkish Military Coups","event",1960,1997,False,"Turkey","Interventions in 1960, 1971, 1980 and 1997 that repeatedly reset Turkish politics.",[])
E("turkish-invasion-of-cyprus","Turkish Invasion of Cyprus","event",1974,1974,False,"Cyprus","Turkish intervention after a Greek-backed coup, dividing the island and creating a northern Turkish entity.",[])
E("erdogan-era","Erdogan Era","reign",2003,None,True,"Turkey","Prime minister then president since 2003: economic growth, Islamic conservatism, the 2016 coup attempt and executive presidency.",["Recep Tayyip Erdogan"])
E("turkish-coup-attempt-2016","Turkish Coup Attempt of 2016","event",2016,2016,False,"Turkey","Failed military putsch followed by mass purges and a state of emergency.",[])
E("republic-of-cyprus","Republic of Cyprus","polity",1960,None,True,"Cyprus","Independent from Britain in 1960, de facto divided since 1974 and an EU member since 2004.",["Cyprus"])
E("northern-cyprus","Turkish Republic of Northern Cyprus","polity",1983,None,True,"Cyprus","Self-declared state recognised only by Turkey.",["TRNC"])

# ---------------- IRAN ----------------
E("safavid-empire","Safavid Empire","polity",1501,1736,False,"Iran","Dynasty that made Twelver Shi'ism Iran's state religion and built Isfahan as an imperial capital.",["Safavids"])
E("reign-abbas-the-great","Reign of Shah Abbas I","reign",1588,1629,False,"Safavid Empire","Reformed the army, retook lands from the Ottomans and Uzbeks, and rebuilt Isfahan.",["Abbas the Great"])
E("afsharid-dynasty","Afsharid Dynasty","polity",1736,1796,False,"Iran","Nader Shah's short-lived empire, which sacked Delhi in 1739 and collapsed after his assassination.",["Nader Shah"])
E("zand-dynasty","Zand Dynasty","polity",1751,1794,False,"Iran","Karim Khan's relatively peaceful regime based at Shiraz.",[])
E("qajar-dynasty","Qajar Dynasty","polity",1789,1925,False,"Iran","Dynasty that lost the Caucasus to Russia, granted foreign concessions and faced the Constitutional Revolution.",["Qajars"])
E("russo-persian-wars","Russo-Persian Wars","event",1804,1828,False,"Iran and Russia","Wars ending in the treaties of Gulistan and Turkmenchay, which ceded the Caucasus to Russia.",[])
E("tobacco-protest","Tobacco Protest","event",1891,1892,False,"Iran","Nationwide boycott led by clerics that forced cancellation of a British tobacco monopoly.",[])
E("persian-constitutional-revolution","Persian Constitutional Revolution","event",1905,1911,False,"Iran","Movement that won a constitution and the first Majlis, then was undermined by royal and foreign intervention.",[])
E("anglo-russian-convention-1907","Anglo-Russian Convention","event",1907,1907,False,"Iran","Agreement dividing Persia into Russian and British spheres of influence.",[])
E("discovery-of-persian-oil","Discovery of Oil in Persia","event",1908,1908,False,"Iran","Masjed Soleyman strike led to the Anglo-Persian Oil Company and a century of oil politics.",["Anglo-Persian Oil Company"])
E("pahlavi-dynasty","Pahlavi Dynasty","polity",1925,1979,False,"Iran","Two shahs who modernised, secularised and centralised Iran until the Islamic Revolution.",["Pahlavis"])
E("reza-shah-reign","Reign of Reza Shah Pahlavi","reign",1925,1941,False,"Pahlavi Iran","Army officer turned shah who built railways, unveiled women and was deposed by the Allies in 1941.",[])
E("anglo-soviet-invasion-iran","Anglo-Soviet Invasion of Iran","event",1941,1941,False,"Iran","Allied occupation to secure oil and a supply corridor to the USSR, forcing Reza Shah's abdication.",[])
E("mohammad-reza-shah-reign","Reign of Mohammad Reza Pahlavi","reign",1941,1979,False,"Pahlavi Iran","Last shah: oil nationalisation crisis, the 1953 coup, White Revolution, SAVAK repression and revolution.",[])
E("iranian-oil-nationalisation","Iranian Oil Nationalisation","event",1951,1951,False,"Iran","Mosaddegh's nationalisation of the Anglo-Iranian Oil Company, met by boycott and covert action.",["Mosaddegh"])
E("iranian-coup-1953","Iranian Coup of 1953","event",1953,1953,False,"Iran","CIA and MI6 operation that removed Prime Minister Mosaddegh and restored the shah's power.",["Operation Ajax"])
E("white-revolution","White Revolution","era",1963,1979,False,"Iran","Shah's programme of land reform, literacy and women's suffrage that also displaced rural populations.",[])
E("iranian-revolution","Iranian Revolution","event",1978,1979,False,"Iran","Mass movement that overthrew the shah and established an Islamic republic under Khomeini.",["Islamic Revolution"])
E("islamic-republic-of-iran","Islamic Republic of Iran","polity",1979,None,True,"Iran","Theocratic republic with a supreme leader and elected institutions, in confrontation with the West since 1979.",["Iran","Persia"])
E("iran-hostage-crisis","Iran Hostage Crisis","event",1979,1981,False,"Iran","444-day seizure of the US embassy in Tehran that severed relations with Washington.",[])
E("khomeini-leadership","Leadership of Ruhollah Khomeini","reign",1979,1989,False,"Islamic Republic of Iran","Founder and first supreme leader, who institutionalised clerical rule and led the war with Iraq.",[])
E("iran-iraq-war","Iran-Iraq War","event",1980,1988,False,"West Asia","Eight-year war of attrition with chemical weapons and about a million casualties, ending in stalemate.",[])
E("khamenei-leadership","Leadership of Ali Khamenei","reign",1989,None,True,"Islamic Republic of Iran","Supreme leader since 1989, presiding over nuclear disputes, sanctions and protest movements.",[])
E("iranian-green-movement","Iranian Green Movement","event",2009,2010,False,"Iran","Mass protests against a disputed presidential election, suppressed by security forces.",[])
E("iran-nuclear-deal","Iran Nuclear Deal","event",2015,2018,False,"Iran","JCPOA limiting Iran's nuclear programme for sanctions relief, abandoned by the United States in 2018.",["JCPOA"])
E("mahsa-amini-protests","Mahsa Amini Protests","event",2022,2023,False,"Iran","Nationwide 'Woman, Life, Freedom' uprising after a young woman's death in morality police custody.",[])

# ---------------- ARAB WORLD & ISRAEL ----------------
E("ottoman-syria","Ottoman Syria and the Levant","polity",1516,1918,False,"Levant","Four centuries of Ottoman provincial rule over Syria, Lebanon, Palestine and Transjordan.",[])
E("mount-lebanon-emirate","Emirate of Mount Lebanon","polity",1516,1842,False,"Lebanon","Autonomous Druze and Maronite emirate under Ottoman suzerainty, notably under Fakhr al-Din II.",[])
E("mount-lebanon-mutasarrifate","Mount Lebanon Mutasarrifate","polity",1861,1918,False,"Lebanon","Autonomous Christian-governed Ottoman province created after the 1860 civil war under European pressure.",[])
E("mandatory-palestine","Mandatory Palestine","polity",1920,1948,False,"Palestine","British League of Nations mandate under the Balfour Declaration's terms, ending in war and partition.",["British Mandate of Palestine"])
E("balfour-declaration","Balfour Declaration","event",1917,1917,False,"Palestine","British pledge to favour a Jewish national home in Palestine while protecting non-Jewish rights.",[])
E("zionist-movement","Zionist Movement","era",1897,1948,False,"Israel","Political movement founded at Basel by Herzl to establish a Jewish state, realised in 1948.",["Zionism"])
E("arab-revolt-palestine-1936","Arab Revolt in Palestine","event",1936,1939,False,"Palestine","Palestinian rebellion against British rule and Jewish immigration, suppressed with heavy casualties.",[])
E("un-partition-plan","United Nations Partition Plan for Palestine","event",1947,1947,False,"Palestine","Resolution 181 recommended Jewish and Arab states with international status for Jerusalem.",["Resolution 181"])
E("state-of-israel","State of Israel","polity",1948,None,True,"Israel","Jewish state declared on 14 May 1948, which has fought repeated wars with its neighbours and Palestinians.",["Israel"])
E("arab-israeli-war-1948","1948 Arab-Israeli War","event",1948,1949,False,"West Asia","War following Israel's declaration, ending in armistice lines and the displacement of most Palestinian Arabs.",["War of Independence","Nakba"])
E("nakba","Nakba","event",1948,1948,False,"Palestine","Expulsion and flight of about 750,000 Palestinians and the destruction of hundreds of villages.",["Palestinian catastrophe"])
E("ben-gurion-premiership","Premiership of David Ben-Gurion","reign",1948,1963,False,"Israel","Founding prime minister who built state institutions, absorbed mass immigration and led the 1956 Sinai campaign.",[])
E("suez-crisis","Suez Crisis","event",1956,1956,False,"Egypt and West Asia","British, French and Israeli attack on Egypt after Nasser nationalised the canal, reversed by US and Soviet pressure.",["Tripartite Aggression"],"high","africa")
E("six-day-war","Six-Day War","event",1967,1967,False,"West Asia","Israeli victory over Egypt, Jordan and Syria that took Sinai, Gaza, the West Bank, Jerusalem and the Golan.",["1967 war"])
E("yom-kippur-war","Yom Kippur War","event",1973,1973,False,"West Asia","Egyptian and Syrian surprise attack on Israel that led to the oil embargo and eventually to peace talks.",["October War","Ramadan War"])
E("camp-david-accords","Camp David Accords","event",1978,1979,False,"West Asia","Egyptian-Israeli peace brokered by Carter, returning Sinai to Egypt; Sadat was assassinated in 1981.",[])
E("lebanese-civil-war","Lebanese Civil War","event",1975,1990,False,"Lebanon","Fifteen-year multi-sided war with Syrian and Israeli intervention, ending in the Taif Agreement.",[])
E("israeli-invasion-of-lebanon-1982","Israeli Invasion of Lebanon","event",1982,1985,False,"Lebanon","Invasion to expel the PLO, the siege of Beirut and the Sabra and Shatila massacre.",[])
E("plo","Palestine Liberation Organization","polity",1964,None,True,"Palestine","Umbrella national movement led by Yasser Arafat from 1969, recognised as the Palestinian representative.",["PLO"])
E("first-intifada","First Intifada","event",1987,1993,False,"Palestine","Palestinian mass uprising in the occupied territories, ended by the Oslo process.",[])
E("oslo-accords","Oslo Accords","event",1993,1995,False,"West Asia","Israeli-Palestinian agreements creating the Palestinian Authority and mutual recognition.",[])
E("palestinian-authority","Palestinian Authority","polity",1994,None,True,"Palestine","Interim self-governing body in the West Bank and, until 2007, Gaza.",["PA","Palestinian National Authority"])
E("second-intifada","Second Intifada","event",2000,2005,False,"Palestine","Violent uprising with suicide bombings and Israeli reoccupation, followed by the separation barrier.",["al-Aqsa Intifada"])
E("gaza-disengagement","Israeli Disengagement from Gaza","event",2005,2005,False,"Palestine","Israel withdrew settlers and soldiers from Gaza, which Hamas took over in 2007.",[])
E("state-of-palestine","State of Palestine","polity",1988,None,True,"Palestine","Declared in 1988 and recognised by most UN members; a UN observer state since 2012.",["Palestine"])
E("gaza-war-2023","Gaza War","event",2023,None,True,"Palestine and Israel","War following the Hamas attack of 7 October 2023, with devastating destruction and casualties in Gaza.",["Israel-Hamas war"],"medium")
E("french-mandate-syria","French Mandate for Syria and Lebanon","polity",1923,1946,False,"Levant","French League of Nations mandate that created the borders of modern Syria and Lebanon.",[])
E("republic-of-lebanon","Lebanese Republic","polity",1943,None,True,"Lebanon","Independent confessional republic, shaped by civil war, Syrian tutelage and economic collapse.",["Lebanon"])
E("syrian-arab-republic","Syrian Arab Republic","polity",1946,None,True,"Syria","Independent from France in 1946; Ba'athist from 1963, ruled by the Assads from 1970 to 2024.",["Syria"])
E("united-arab-republic","United Arab Republic","polity",1958,1961,False,"Egypt and Syria","Short-lived union of Egypt and Syria under Nasser, dissolved by a Syrian coup.",["UAR"],"high","africa")
E("hafez-al-assad-rule","Rule of Hafez al-Assad","reign",1970,2000,False,"Syria","Thirty years of Ba'athist Alawite-led authoritarian rule, including the 1982 Hama massacre.",[])
E("bashar-al-assad-rule","Rule of Bashar al-Assad","reign",2000,2024,False,"Syria","Presidency that met the 2011 uprising with war, chemical attacks and displacement, ending in his flight in December 2024.",[])
E("syrian-civil-war","Syrian Civil War","event",2011,None,True,"Syria","Uprising turned multi-sided war with Russian, Iranian, Turkish and US involvement and over half a million dead.",[])
E("fall-of-assad","Fall of the Assad Regime","event",2024,2024,False,"Syria","Rebel offensive that captured Damascus in December 2024 and ended 54 years of Assad family rule.",[],"medium")
E("british-mandate-mesopotamia","British Mandate for Mesopotamia","polity",1920,1932,False,"Iraq","British mandate over Iraq established after the Ottoman collapse, resisted in the 1920 revolt.",[])
E("kingdom-of-iraq","Kingdom of Iraq","polity",1932,1958,False,"Iraq","Hashemite kingdom independent from 1932, overthrown in the bloody 1958 revolution.",[])
E("republic-of-iraq","Republic of Iraq","polity",1958,None,True,"Iraq","Republic since 1958: Ba'athist rule, three wars, occupation and a federal constitution since 2005.",["Iraq"])
E("saddam-hussein-rule","Rule of Saddam Hussein","reign",1979,2003,False,"Iraq","Ba'athist dictator: war with Iran, gassing of Kurds, invasion of Kuwait and overthrow by US-led invasion.",[])
E("gulf-war","Gulf War","event",1990,1991,False,"West Asia","US-led coalition expelled Iraq from Kuwait after its August 1990 invasion.",["Operation Desert Storm"])
E("iraq-war","Iraq War","event",2003,2011,False,"Iraq","US-led invasion that toppled Saddam Hussein, followed by insurgency, sectarian civil war and occupation.",[])
E("isis-caliphate","Islamic State Caliphate","polity",2014,2019,False,"Iraq and Syria","Jihadist proto-state that seized Mosul and Raqqa before being destroyed by coalition and local forces.",["ISIS","ISIL","Daesh"])
E("kurdistan-region-iraq","Kurdistan Region of Iraq","polity",1991,None,True,"Iraq","Autonomous Kurdish region established under no-fly-zone protection and constitutionally recognised in 2005.",["Iraqi Kurdistan"])
E("kurdish-question","The Kurdish Question","era",1920,None,True,"West Asia","Statelessness of the Kurds after Sevres, with insurgencies and autonomy struggles in Turkey, Iraq, Iran and Syria.",[])
E("emirate-of-transjordan","Emirate of Transjordan","polity",1921,1946,False,"Jordan","British-mandated Hashemite emirate under Abdullah I, independent as a kingdom in 1946.",[])
E("kingdom-of-jordan","Hashemite Kingdom of Jordan","polity",1946,None,True,"Jordan","Hashemite monarchy independent in 1946, host to large Palestinian refugee populations.",["Jordan"])
E("hussein-of-jordan-reign","Reign of King Hussein of Jordan","reign",1952,1999,False,"Jordan","Forty-six-year reign through the 1967 war, Black September and peace with Israel in 1994.",[])
E("first-saudi-state","Emirate of Diriyah","polity",1744,1818,False,"Saudi Arabia","First Saudi state, founded on the alliance of Muhammad ibn Saud and Muhammad ibn Abd al-Wahhab, crushed by Egypt.",["First Saudi State"])
E("second-saudi-state","Emirate of Nejd","polity",1824,1891,False,"Saudi Arabia","Second Saudi state, based at Riyadh, overthrown by the Rashidis.",["Second Saudi State"])
E("ibn-saud-unification","Unification of Saudi Arabia","event",1902,1932,False,"Saudi Arabia","Ibn Saud's campaigns from the recapture of Riyadh to the proclamation of the kingdom in 1932.",[])
E("kingdom-of-saudi-arabia","Kingdom of Saudi Arabia","polity",1932,None,True,"Saudi Arabia","Absolute monarchy guarding Mecca and Medina, transformed by the world's largest conventional oil reserves.",["Saudi Arabia"])
E("saudi-oil-discovery","Discovery of Saudi Oil","event",1938,1938,False,"Saudi Arabia","Dammam strike that made Saudi Arabia the centre of world oil and founded Aramco.",["Aramco"])
E("reign-faisal-saudi","Reign of King Faisal","reign",1964,1975,False,"Saudi Arabia","Modernising king who led the 1973 oil embargo; assassinated by a nephew.",[])
E("reign-fahd","Reign of King Fahd","reign",1982,2005,False,"Saudi Arabia","King during the Gulf War, when US troops were stationed in the kingdom, and the Basic Law of 1992.",[])
E("reign-abdullah-saudi","Reign of King Abdullah","reign",2005,2015,False,"Saudi Arabia","Cautious reformer who expanded education and faced the Arab Spring.",[])
E("mbs-era","Rule of Mohammed bin Salman","reign",2017,None,True,"Saudi Arabia","Crown prince driving Vision 2030 reforms, the Yemen war and a crackdown on dissent.",["Vision 2030","MBS"])
E("grand-mosque-seizure","Seizure of the Grand Mosque","event",1979,1979,False,"Saudi Arabia","Two-week takeover of the Kaaba compound by militants, after which the kingdom hardened religious policy.",[])
E("state-of-kuwait","State of Kuwait","polity",1961,None,True,"Kuwait","Oil-rich Gulf emirate independent from Britain in 1961, occupied by Iraq in 1990-91.",["Kuwait"])
E("kingdom-of-bahrain","Kingdom of Bahrain","polity",1971,None,True,"Bahrain","Gulf island state independent in 1971 and a kingdom since 2002, host to the US Fifth Fleet.",["Bahrain"])
E("state-of-qatar","State of Qatar","polity",1971,None,True,"Qatar","Gas-rich emirate independent in 1971, home to Al Jazeera and host of the 2022 World Cup.",["Qatar"])
E("united-arab-emirates","United Arab Emirates","polity",1971,None,True,"United Arab Emirates","Federation of seven emirates formed on British withdrawal, now a global trade and finance hub.",["UAE","Trucial States"])
E("sultanate-of-oman","Sultanate of Oman","polity",1744,None,True,"Oman","Al Bu Said sultanate that once ruled Zanzibar, modernised after Sultan Qaboos took power in 1970.",["Oman","Muscat and Oman"])
E("dhofar-rebellion","Dhofar Rebellion","event",1963,1976,False,"Oman","Leftist insurgency in southern Oman defeated with British and Iranian help.",[])
E("mutawakkilite-yemen","Mutawakkilite Kingdom of Yemen","polity",1918,1962,False,"Yemen","Zaydi imamate in North Yemen, overthrown in the 1962 revolution.",[])
E("south-yemen","People's Democratic Republic of Yemen","polity",1967,1990,False,"Yemen","Marxist state based at Aden after British withdrawal, merged with the north in 1990.",["South Yemen"])
E("republic-of-yemen","Republic of Yemen","polity",1990,None,True,"Yemen","Unified in 1990, since 2014 divided by civil war and Saudi-led intervention.",["Yemen"])
E("yemeni-civil-war","Yemeni Civil War","event",2014,None,True,"Yemen","Houthi takeover of Sanaa and Saudi-led intervention producing a severe humanitarian crisis.",[])
E("arab-spring","Arab Spring","era",2010,2012,False,"West Asia and North Africa","Wave of uprisings from Tunisia to Bahrain that toppled four rulers and triggered wars in Libya, Syria and Yemen.",[],"high","global")
E("opec","Organization of the Petroleum Exporting Countries","polity",1960,None,True,"West Asia and global","Cartel founded in Baghdad that reshaped global energy politics, notably in the 1973 embargo.",["OPEC"],"high","global")
E("oil-crisis-1973","1973 Oil Crisis","event",1973,1974,False,"Global","Arab oil embargo that quadrupled prices, ending the postwar boom and reshaping energy policy.",["oil shock"],"high","global")
E("arab-league","Arab League","polity",1945,None,True,"West Asia and North Africa","Regional organisation of Arab states founded in Cairo in 1945.",["League of Arab States"])
E("gulf-cooperation-council","Gulf Cooperation Council","polity",1981,None,True,"Arabian Peninsula","Six-member Gulf political and economic union founded in 1981.",["GCC"])
E("abraham-accords","Abraham Accords","event",2020,2020,False,"West Asia","Normalisation agreements between Israel and the UAE, Bahrain, Morocco and Sudan.",[])
