import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _mn_common import E, ROWS, set_region
set_region('europe')

# ---------------- RUSSIA ----------------
E("tsardom-of-russia","Tsardom of Russia","polity",1547,1721,False,"Russia","Muscovite state proclaimed a tsardom under Ivan IV, which conquered Kazan and Siberia and survived the Time of Troubles.",["Muscovy","Tsardom of Muscovy"])
E("reign-ivan-the-terrible","Reign of Ivan IV the Terrible","reign",1547,1584,False,"Tsardom of Russia","First crowned tsar; conquered Kazan and Astrakhan, launched the Livonian War and terrorised the boyars with the oprichnina.",["Ivan the Terrible","Ivan Grozny"])
E("russian-conquest-of-siberia","Russian Conquest of Siberia","era",1580,1700,False,"Russia","Cossack and merchant expansion across northern Asia to the Pacific, driven by the fur trade.",["Siberian conquest"])
E("time-of-troubles","Time of Troubles","period",1598,1613,False,"Russia","Dynastic vacuum, famine, false Dmitrys and Polish-Swedish intervention, ended by the election of the Romanovs.",["Smuta"])
E("house-of-romanov","House of Romanov","polity",1613,1917,False,"Russia","Dynasty that ruled Russia for three centuries, from Michael I to Nicholas II.",["Romanov dynasty"])
E("reign-peter-the-great","Reign of Peter the Great","reign",1682,1725,False,"Russia","Westernising tsar who built St Petersburg and a navy, beat Sweden at Poltava and proclaimed the Russian Empire.",["Peter I"])
E("founding-of-st-petersburg","Founding of St Petersburg","event",1703,1703,False,"Russia","Peter I founded his new capital on the Neva as a window on Europe.",[])
E("russian-empire","Russian Empire","polity",1721,1917,False,"Russia","Empire proclaimed by Peter I that expanded into the Baltic, Poland, the Caucasus, Central Asia and Alaska before 1917.",["Imperial Russia","Rossiyskaya Imperiya"])
E("reign-catherine-the-great","Reign of Catherine the Great","reign",1762,1796,False,"Russian Empire","Enlightened empress who annexed Crimea and much of Poland, expanded serfdom and corresponded with the philosophes.",["Catherine II"])
E("pugachev-rebellion","Pugachev's Rebellion","event",1773,1775,False,"Russian Empire","Massive Cossack and peasant revolt suppressed by Catherine II, hardening noble control over serfs.",[])
E("reign-alexander-i-russia","Reign of Alexander I of Russia","reign",1801,1825,False,"Russian Empire","Tsar who defeated Napoleon's invasion, entered Paris and shaped the Holy Alliance at Vienna.",[])
E("french-invasion-of-russia","French Invasion of Russia","event",1812,1812,False,"Russia","Napoleon's Grande Armee reached Moscow and was destroyed in retreat, losing most of half a million men.",["Patriotic War of 1812"])
E("decembrist-revolt","Decembrist Revolt","event",1825,1825,False,"Russian Empire","Failed liberal officers' coup at Nicholas I's accession, followed by decades of repression.",[])
E("reign-nicholas-i-russia","Reign of Nicholas I","reign",1825,1855,False,"Russian Empire","Autocracy of orthodoxy and censorship, the 'gendarme of Europe', ending in defeat in the Crimean War.",[])
E("crimean-war","Crimean War","event",1853,1856,False,"Europe and West Asia","Russia's defeat by Britain, France, the Ottomans and Piedmont, which exposed its backwardness and forced reform.",[])
E("reign-alexander-ii-russia","Reign of Alexander II","reign",1855,1881,False,"Russian Empire","Tsar-liberator who emancipated the serfs and reformed law and local government; assassinated in 1881.",[])
E("emancipation-of-the-serfs","Emancipation of the Serfs","event",1861,1861,False,"Russian Empire","Alexander II's manifesto freeing some 23 million serfs, with land redemption payments.",[])
E("reign-alexander-iii-russia","Reign of Alexander III","reign",1881,1894,False,"Russian Empire","Counter-reforming tsar of Russification, pogroms and rapid railway-led industrialisation.",[])
E("reign-nicholas-ii","Reign of Nicholas II","reign",1894,1917,False,"Russian Empire","Last tsar: defeat by Japan, the 1905 revolution, the Duma, war in 1914 and abdication in 1917.",[])
E("russo-japanese-war","Russo-Japanese War","event",1904,1905,False,"East Asia","Japan's victory over Russia at Port Arthur, Mukden and Tsushima, the first modern Asian defeat of a European power.",[],"high","east-asia")
E("russian-revolution-1905","Russian Revolution of 1905","event",1905,1905,False,"Russian Empire","Bloody Sunday, mass strikes and mutinies forced Nicholas II to grant the October Manifesto and a Duma.",[])
E("february-revolution","February Revolution","event",1917,1917,False,"Russia","Petrograd bread riots and mutiny toppled the tsar and created a Provisional Government and soviets.",[])
E("russian-provisional-government","Russian Provisional Government","polity",1917,1917,False,"Russia","Liberal-socialist government under Lvov then Kerensky that kept Russia in the war and fell in October.",[])
E("october-revolution","October Revolution","event",1917,1917,False,"Russia","Bolshevik seizure of power in Petrograd under Lenin and Trotsky, creating the world's first communist state.",["Bolshevik Revolution"])
E("russian-civil-war","Russian Civil War","event",1917,1922,False,"Russia","Reds defeated Whites, nationalists and Allied interventions at a cost of millions of lives and famine.",[])
E("treaty-brest-litovsk","Treaty of Brest-Litovsk","event",1918,1918,False,"Russia and Germany","Bolshevik peace with Germany that surrendered Ukraine, the Baltics and Poland, annulled in November 1918.",[])
E("war-communism","War Communism","period",1918,1921,False,"Soviet Russia","Forced grain requisitioning and nationalisation during the civil war, ended by famine and the New Economic Policy.",[])
E("soviet-union","Soviet Union","polity",1922,1991,False,"Russia and Eurasia","Union of Soviet Socialist Republics: one-party communist federation, industrial and nuclear superpower, dissolved in December 1991.",["USSR","Sovetsky Soyuz"])
E("lenin-rule","Lenin's Leadership of Soviet Russia","reign",1917,1924,False,"Soviet Union","Founder of the Bolshevik state, architect of the one-party system, the Comintern and the NEP.",["Vladimir Lenin"])
E("new-economic-policy","New Economic Policy","period",1921,1928,False,"Soviet Union","Partial market restoration in agriculture and small trade that revived the economy after war communism.",["NEP"])
E("stalin-rule","Stalin's Rule of the Soviet Union","reign",1924,1953,False,"Soviet Union","Collectivisation, five-year plans, terror and victory over Germany under a totalitarian personality cult.",["Joseph Stalin"])
E("soviet-collectivisation","Soviet Collectivisation","event",1929,1933,False,"Soviet Union","Forced collectivisation of agriculture and dekulakisation, causing famine across Ukraine, Kazakhstan and Russia.",[])
E("holodomor","Holodomor","event",1932,1933,False,"Ukraine","Man-made famine in Soviet Ukraine that killed roughly four million people, recognised by many states as genocide.",["Ukrainian famine"])
E("great-purge","Great Purge","event",1936,1938,False,"Soviet Union","Stalin's terror: show trials, mass executions of some 700,000 people and destruction of the party and army leadership.",["Great Terror","Yezhovshchina"])
E("gulag","Gulag System","polity",1930,1960,False,"Soviet Union","Vast network of forced-labour camps that held millions of prisoners, wound down after Stalin's death.",["Gulag Archipelago"])
E("great-patriotic-war","Great Patriotic War","event",1941,1945,False,"Soviet Union","Soviet war against Germany from Barbarossa to Berlin, with roughly 27 million Soviet dead.",["Eastern Front"])
E("khrushchev-rule","Khrushchev Era","reign",1953,1964,False,"Soviet Union","De-Stalinisation, the Secret Speech, Sputnik, the Virgin Lands and the Cuban missile crisis, ending in his ouster.",["Nikita Khrushchev"])
E("khrushchev-thaw","Khrushchev Thaw","period",1956,1964,False,"Soviet Union","Relative cultural and political liberalisation after the denunciation of Stalin's crimes.",[])
E("brezhnev-era","Brezhnev Era","reign",1964,1982,False,"Soviet Union","Stagnation and stability: Prague Spring suppression, detente, oil-funded consumerism and the Afghan invasion.",["Leonid Brezhnev","Era of Stagnation"])
E("andropov-chernenko","Andropov and Chernenko Interregnum","reign",1982,1985,False,"Soviet Union","Two brief, ailing general secretaries between Brezhnev and Gorbachev.",[])
E("gorbachev-era","Gorbachev Era","reign",1985,1991,False,"Soviet Union","Perestroika, glasnost and arms control that ended the Cold War and unintentionally dissolved the USSR.",["Mikhail Gorbachev"])
E("chernobyl-disaster","Chernobyl Disaster","event",1986,1986,False,"Soviet Union and Ukraine","Reactor explosion on 26 April 1986 that spread radiation across Europe and discredited Soviet secrecy.",[])
E("soviet-august-coup","August Coup","event",1991,1991,False,"Soviet Union","Failed hardline putsch against Gorbachev that accelerated the union's collapse and Yeltsin's rise.",["1991 Soviet coup attempt"])
E("dissolution-of-the-soviet-union","Dissolution of the Soviet Union","event",1991,1991,False,"Soviet Union","Belovezha Accords and Gorbachev's resignation ended the USSR on 26 December 1991, creating fifteen states.",["Fall of the Soviet Union","Collapse of the USSR"])
E("russian-federation","Russian Federation","polity",1991,None,True,"Russia","Successor state to the USSR: shock-therapy transition, Chechen wars, oil-fuelled recovery and wars in Georgia and Ukraine.",["Russia"])
E("yeltsin-presidency","Presidency of Boris Yeltsin","reign",1991,1999,False,"Russian Federation","First Russian president: market shock therapy, the 1993 constitutional crisis, Chechnya and the 1998 default.",[])
E("first-chechen-war","First Chechen War","event",1994,1996,False,"Russia","Russian invasion of separatist Chechnya ending in a humiliating ceasefire at Khasavyurt.",[])
E("second-chechen-war","Second Chechen War","event",1999,2009,False,"Russia","Renewed campaign that reasserted Moscow's control over Chechnya under Kadyrov.",[])
E("putin-rule","Rule of Vladimir Putin","reign",2000,None,True,"Russian Federation","President from 2000 (prime minister 2008-12), centralising power, curbing media and pursuing war in Ukraine.",["Vladimir Putin"])
E("medvedev-presidency","Presidency of Dmitry Medvedev","reign",2008,2012,False,"Russian Federation","Interim presidency with Putin as premier; the 2008 Georgia war and the financial crisis.",[])
E("russo-georgian-war","Russo-Georgian War","event",2008,2008,False,"Caucasus","Five-day war over South Ossetia and Abkhazia that Russia won and followed by recognising both.",[])
E("annexation-of-crimea","Russian Annexation of Crimea","event",2014,2014,False,"Russia and Ukraine","Russian forces seized Crimea and staged a referendum, triggering Western sanctions and war in the Donbas.",[])
E("war-in-donbas","War in Donbas","event",2014,2022,False,"Ukraine","Russian-backed separatist conflict in eastern Ukraine that killed over 13,000 before the full invasion.",[])
E("russian-invasion-of-ukraine-2022","Russian Invasion of Ukraine","event",2022,None,True,"Ukraine","Full-scale Russian invasion from 24 February 2022, Europe's largest war since 1945.",["Russo-Ukrainian War"])

# ---------------- OTHER POST-SOVIET EUROPE ----------------
E("cossack-hetmanate","Cossack Hetmanate","polity",1649,1764,False,"Ukraine","Cossack state under Khmelnytsky that allied with Muscovy at Pereiaslav and was absorbed by Russia.",["Zaporizhian Host"])
E("ukrainian-peoples-republic","Ukrainian People's Republic","polity",1917,1921,False,"Ukraine","Short-lived independent Ukraine under Hrushevsky, Skoropadsky and Petliura, defeated by Bolshevik forces.",["UNR"])
E("ukrainian-ssr","Ukrainian Soviet Socialist Republic","polity",1922,1991,False,"Ukraine","Soviet Ukraine, site of the Holodomor, brutal Nazi occupation and postwar industrialisation.",[])
E("independent-ukraine","Ukraine","polity",1991,None,True,"Ukraine","Independent since the 1991 referendum; the Orange Revolution, Euromaidan and war with Russia have shaped its statehood.",["Ukraina"])
E("orange-revolution","Orange Revolution","event",2004,2005,False,"Ukraine","Mass protests that overturned a rigged presidential election in favour of Viktor Yushchenko.",[])
E("euromaidan","Euromaidan","event",2013,2014,False,"Ukraine","Kyiv protests against a shelved EU agreement that ousted President Yanukovych.",["Revolution of Dignity"])
E("belarusian-ssr","Byelorussian Soviet Socialist Republic","polity",1922,1991,False,"Belarus","Soviet Belarus, which lost about a quarter of its population in the Second World War.",[])
E("republic-of-belarus","Republic of Belarus","polity",1991,None,True,"Belarus","Independent since 1991 and ruled by Alexander Lukashenko since 1994 in close alignment with Russia.",["Belarus"])
E("moldova","Republic of Moldova","polity",1991,None,True,"Moldova","Former Soviet republic independent since 1991, with the breakaway Transnistria region and EU candidate status.",["Moldova","Bessarabia"])
E("transnistria","Transnistria","polity",1990,None,True,"Moldova","Unrecognised Russian-backed breakaway statelet on the left bank of the Dniester.",["Pridnestrovie"])

# ---------------- CAUCASUS & CENTRAL ASIA ----------------
set_region('central-asia')
E("khanate-of-crimea","Crimean Khanate","polity",1500,1783,False,"Black Sea region","Tatar successor of the Golden Horde, an Ottoman vassal and slave-raiding power, annexed by Russia in 1783.",["Crimean Tatars"],"high","europe")
E("khanate-of-khiva","Khanate of Khiva","polity",1511,1920,False,"Central Asia","Uzbek khanate on the Amu Darya that became a Russian protectorate in 1873 and a Soviet republic in 1920.",["Khwarazm"])
E("emirate-of-bukhara","Emirate of Bukhara","polity",1785,1920,False,"Central Asia","Manghit emirate, a Russian protectorate from 1868, overthrown by the Red Army in 1920.",["Bukhara"])
E("khanate-of-kokand","Khanate of Kokand","polity",1709,1876,False,"Central Asia","Ferghana valley khanate annexed outright by Russia in 1876.",[])
E("russian-conquest-central-asia","Russian Conquest of Central Asia","era",1839,1895,False,"Central Asia","Tsarist campaigns that absorbed Turkestan and the steppe, part of the Great Game with Britain.",["Russian Turkestan"])
E("great-game","The Great Game","era",1830,1907,False,"Central Asia","Anglo-Russian strategic rivalry over Afghanistan, Persia and Turkestan, settled by the 1907 convention.",[])
E("basmachi-revolt","Basmachi Revolt","event",1916,1934,False,"Central Asia","Muslim resistance to Russian and Soviet rule across Turkestan, suppressed by the Red Army.",[])
E("kazakh-ssr","Kazakh Soviet Socialist Republic","polity",1936,1991,False,"Kazakhstan","Soviet Kazakhstan: famine under collectivisation, Virgin Lands campaign, Semipalatinsk nuclear tests and Baikonur.",[])
E("republic-of-kazakhstan","Republic of Kazakhstan","polity",1991,None,True,"Kazakhstan","Largest Central Asian state, independent in 1991, oil-rich and ruled by Nazarbayev until 2019.",["Kazakhstan"])
E("republic-of-uzbekistan","Republic of Uzbekistan","polity",1991,None,True,"Uzbekistan","Most populous Central Asian state, independent in 1991, ruled by Karimov until 2016.",["Uzbekistan"])
E("turkmenistan","Turkmenistan","polity",1991,None,True,"Turkmenistan","Gas-rich neutral state independent in 1991 under Niyazov's personality cult and his successors.",[])
E("kyrgyz-republic","Kyrgyz Republic","polity",1991,None,True,"Kyrgyzstan","Central Asian republic independent in 1991, with revolutions in 2005, 2010 and 2020.",["Kyrgyzstan"])
E("republic-of-tajikistan","Republic of Tajikistan","polity",1991,None,True,"Tajikistan","Independent in 1991 and scarred by a civil war from 1992 to 1997; ruled by Emomali Rahmon.",["Tajikistan"])
E("tajik-civil-war","Tajik Civil War","event",1992,1997,False,"Tajikistan","Post-Soviet conflict between government and Islamist-democratic opposition that killed tens of thousands.",[])
E("aral-sea-desiccation","Desiccation of the Aral Sea","event",1960,None,True,"Central Asia","Soviet irrigation of cotton lands shrank the Aral Sea by most of its volume, a landmark ecological disaster.",[])
set_region('west-asia')
E("kingdom-of-kartli-kakheti","Kingdom of Kartli-Kakheti","polity",1762,1801,False,"Georgia","Unified eastern Georgian kingdom that sought Russian protection and was annexed by Russia in 1801.",[])
E("democratic-republic-of-georgia","Democratic Republic of Georgia","polity",1918,1921,False,"Georgia","Independent Menshevik-led Georgia, invaded and sovietised by the Red Army in 1921.",[])
E("republic-of-georgia","Georgia","polity",1991,None,True,"Georgia","Independent since 1991; the Rose Revolution, the 2008 war with Russia and EU aspirations have defined it.",["Sakartvelo"])
E("rose-revolution","Rose Revolution","event",2003,2003,False,"Georgia","Peaceful protests that removed Eduard Shevardnadze and brought Mikheil Saakashvili to power.",[])
E("first-republic-of-armenia","First Republic of Armenia","polity",1918,1920,False,"Armenia","Independent Armenia after Ottoman collapse, overwhelmed by Turkish and Soviet forces.",[])
E("republic-of-armenia","Republic of Armenia","polity",1991,None,True,"Armenia","Independent since 1991, shaped by the Nagorno-Karabakh conflict with Azerbaijan.",["Armenia","Hayastan"])
E("republic-of-azerbaijan","Republic of Azerbaijan","polity",1991,None,True,"Azerbaijan","Oil-rich Caspian republic independent in 1991, ruled by the Aliyev family since 1993.",["Azerbaijan"])
E("azerbaijan-democratic-republic","Azerbaijan Democratic Republic","polity",1918,1920,False,"Azerbaijan","First secular democratic republic in the Muslim world, sovietised in 1920.",[])
E("first-nagorno-karabakh-war","First Nagorno-Karabakh War","event",1988,1994,False,"Caucasus","War between Armenians and Azerbaijan over Karabakh that displaced about a million people.",[])
E("second-nagorno-karabakh-war","Second Nagorno-Karabakh War","event",2020,2020,False,"Caucasus","Forty-four-day Azerbaijani victory that recovered most occupied territory; Karabakh fell entirely in 2023.",[])
