import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _mn_common import E, ROWS, set_region
set_region('europe')

# ---------------- SCANDINAVIA ----------------
E("kalmar-union-late","Kalmar Union (late)","polity",1500,1523,False,"Scandinavia","Dynastic union of Denmark, Norway and Sweden that broke up when Sweden seceded under Gustav Vasa.",["Kalmarunionen"])
E("swedish-war-of-liberation","Swedish War of Liberation","event",1521,1523,False,"Sweden","Rising led by Gustav Vasa after the Stockholm Bloodbath that ended Danish rule and the Kalmar Union.",["Gustav Vasa's rebellion"])
E("house-of-vasa","House of Vasa","polity",1523,1654,False,"Sweden","Dynasty that made Sweden Protestant, hereditary and a great power in the Baltic.",["Vasa dynasty"])
E("reign-gustav-i-vasa","Reign of Gustav I Vasa","reign",1523,1560,False,"Sweden","Founder of modern Sweden: broke with Denmark and Rome, created a hereditary Lutheran monarchy.",["Gustav Vasa"])
E("reign-gustavus-adolphus","Reign of Gustavus Adolphus","reign",1611,1632,False,"Sweden","Warrior king who reformed the army and intervened decisively in the Thirty Years' War; killed at Lutzen.",["Gustav II Adolf"])
E("swedish-empire","Swedish Empire","polity",1611,1721,False,"Sweden","Stormaktstiden, when Sweden controlled much of the Baltic littoral until defeat in the Great Northern War.",["Stormaktstiden","Swedish Great Power era"])
E("reign-christina-sweden","Reign of Queen Christina","reign",1632,1654,False,"Sweden","Learned queen who ended the Thirty Years' War, then abdicated and converted to Catholicism.",[])
E("great-northern-war","Great Northern War","event",1700,1721,False,"Northern Europe","Coalition war that destroyed Sweden's Baltic empire and established Russia as a great power.",[])
E("reign-charles-xii","Reign of Charles XII of Sweden","reign",1697,1718,False,"Swedish Empire","Warrior king whose victories ended at Poltava in 1709; killed besieging Fredriksten.",["Karl XII"])
E("swedish-age-of-liberty","Swedish Age of Liberty","period",1719,1772,False,"Sweden","Period of parliamentary dominance by the Riksdag over a weakened crown, ended by Gustav III's coup.",["Frihetstiden"])
E("reign-gustav-iii","Reign of Gustav III of Sweden","reign",1771,1792,False,"Sweden","Enlightened absolutist who restored royal power by coup and was assassinated at a masked ball.",[])
E("house-of-bernadotte","House of Bernadotte","polity",1818,None,True,"Sweden","Dynasty founded by Napoleon's marshal Jean Bernadotte, still reigning in Sweden.",[])
E("union-sweden-norway","Union of Sweden and Norway","polity",1814,1905,False,"Scandinavia","Personal union imposed after Denmark ceded Norway, dissolved peacefully in 1905.",["Swedish-Norwegian Union"])
E("kingdom-of-sweden","Kingdom of Sweden","polity",1523,None,True,"Sweden","Continuous Swedish state since 1523, neutral through both world wars, an EU member from 1995 and NATO from 2024.",["Sweden","Sverige"])
E("reign-gustaf-v","Reign of Gustaf V of Sweden","reign",1907,1950,False,"Kingdom of Sweden","Longest-reigning modern Swedish king, on the throne through both world wars and the rise of social democracy.",[])
E("reign-carl-xvi-gustaf","Reign of Carl XVI Gustaf","reign",1973,None,True,"Kingdom of Sweden","Swedish king since 1973 under the 1974 instrument of government that stripped royal political power.",[])
E("swedish-nato-accession","Swedish Accession to NATO","event",2024,2024,False,"Sweden","Sweden abandoned two centuries of non-alignment and joined NATO in March 2024 after Russia's invasion of Ukraine.",[])
E("denmark-norway","Denmark-Norway","polity",1536,1814,False,"Scandinavia","Oldenburg composite monarchy of Denmark, Norway, Iceland and the North Atlantic islands, split at Kiel in 1814.",["Dano-Norwegian realm"])
E("danish-absolutism","Danish Absolutism","period",1660,1848,False,"Denmark","Hereditary absolute monarchy codified in the Lex Regia of 1665, ended by the 1849 constitution.",["Enevaelde"])
E("treaty-of-kiel","Treaty of Kiel","event",1814,1814,False,"Scandinavia","Denmark ceded Norway to Sweden after backing Napoleon, keeping Iceland, Greenland and the Faroes.",[])
E("kingdom-of-denmark","Kingdom of Denmark","polity",1500,None,True,"Denmark","Europe's oldest continuous monarchy, constitutional since 1849, occupied 1940-45, an EU member since 1973.",["Denmark","Danmark"])
E("danish-constitution-1849","Danish June Constitution","event",1849,1849,False,"Denmark","Constitution ending absolutism and creating a bicameral parliament.",["Grundloven"])
E("first-schleswig-war","First Schleswig War","event",1848,1851,False,"Denmark and Germany","Danish victory over Schleswig-Holstein German nationalists and their German allies.",["Three Years War"])
E("second-schleswig-war","Second Schleswig War","event",1864,1864,False,"Denmark and Germany","Prussian-Austrian defeat of Denmark, which lost Schleswig, Holstein and Lauenburg.",["Danish-Prussian War"])
E("reign-christian-x","Reign of Christian X of Denmark","reign",1912,1947,False,"Kingdom of Denmark","King during the Easter Crisis, Icelandic separation and the German occupation, when he became a symbol of resistance.",[])
E("reign-margrethe-ii","Reign of Margrethe II","reign",1972,2024,False,"Kingdom of Denmark","Denmark's first queen regnant in modern times, who abdicated in 2024 after 52 years.",[])
E("reign-frederik-x","Reign of Frederik X","reign",2024,None,True,"Kingdom of Denmark","King of Denmark since January 2024.",[])
E("greenland-home-rule","Greenland Home Rule and Self-Government","event",1979,1979,False,"Denmark","Greenland gained home rule in 1979, extended to self-government in 2009 within the Danish realm.",[])
E("kingdom-of-norway","Kingdom of Norway","polity",1905,None,True,"Norway","Independent constitutional monarchy since the 1905 dissolution of the union with Sweden; oil wealth since the 1970s.",["Norway","Norge"])
E("norwegian-constitution-1814","Norwegian Constitution of 1814","event",1814,1814,False,"Norway","Eidsvoll assembly's liberal constitution, still in force and celebrated on 17 May.",["Eidsvoll constitution"])
E("norwegian-independence-1905","Dissolution of the Union with Sweden","event",1905,1905,False,"Norway","Peaceful separation confirmed by referendum, with Prince Carl of Denmark crowned Haakon VII.",[])
E("reign-haakon-vii","Reign of Haakon VII","reign",1905,1957,False,"Kingdom of Norway","First king of independent Norway, who refused to legitimise the German occupation and led resistance from London.",[])
E("occupation-of-norway","German Occupation of Norway","period",1940,1945,False,"Norway","Five years of German rule under Quisling's collaborationist administration.",[])
E("reign-harald-v","Reign of Harald V","reign",1991,None,True,"Kingdom of Norway","King of Norway since 1991.",[])
E("iceland-independence","Icelandic Sovereignty and Republic","event",1918,1944,False,"Iceland","Iceland became a sovereign kingdom in personal union with Denmark in 1918 and a republic in 1944.",[])
E("republic-of-iceland","Republic of Iceland","polity",1944,None,True,"Iceland","Republic declared in 1944, NATO founder, hit hard by the 2008 banking collapse.",["Iceland","Island"])
E("cod-wars","Cod Wars","event",1958,1976,False,"Iceland","Disputes with Britain over fishing limits that Iceland won, extending its zone to 200 miles.",[])
E("grand-duchy-of-finland","Grand Duchy of Finland","polity",1809,1917,False,"Finland","Autonomous Russian grand duchy where Finnish national identity and institutions took shape.",[])
E("finnish-independence","Finnish Declaration of Independence","event",1917,1917,False,"Finland","Finland declared independence from revolutionary Russia on 6 December 1917.",[])
E("finnish-civil-war","Finnish Civil War","event",1918,1918,False,"Finland","Whites under Mannerheim defeated the Reds in a brief, bloody conflict after independence.",[])
E("republic-of-finland","Republic of Finland","polity",1917,None,True,"Finland","Nordic republic that preserved independence against the USSR, joined the EU in 1995 and NATO in 2023.",["Finland","Suomi"])
E("winter-war","Winter War","event",1939,1940,False,"Finland and Soviet Union","Soviet invasion resisted fiercely by Finland, which ceded Karelia in the Moscow Peace.",["Talvisota"])
E("continuation-war","Continuation War","event",1941,1944,False,"Finland and Soviet Union","Finland's co-belligerent war alongside Germany, ended by armistice and territorial loss.",["Jatkosota"])
E("finlandization","Finlandization","period",1948,1991,False,"Finland","Cold War policy of neutrality and accommodation with the USSR while remaining a Western democracy.",[])
E("finnish-nato-accession","Finnish Accession to NATO","event",2023,2023,False,"Finland","Finland joined NATO in April 2023, ending decades of military non-alignment.",[])

# ---------------- BALTICS ----------------
E("swedish-livonia","Swedish and Polish Livonia","polity",1561,1721,False,"Baltic states","Partition of the Livonian Order's lands among Sweden, Poland-Lithuania and Denmark after the Livonian War.",[])
E("baltic-german-nobility","Baltic Provinces of the Russian Empire","polity",1721,1918,False,"Baltic states","Estonia, Livonia and Courland under Russian rule with Baltic German elites, until 1918 independence.",[])
E("republic-of-estonia-first","Republic of Estonia (first period)","polity",1918,1940,False,"Estonia","Independent Estonia after the War of Independence against Soviet Russia and the Baltic Germans, annexed by the USSR in 1940.",[])
E("republic-of-latvia-first","Republic of Latvia (first period)","polity",1918,1940,False,"Latvia","Independent Latvia between the wars, ended by Soviet annexation under the Molotov-Ribbentrop Pact.",[])
E("republic-of-lithuania-first","Republic of Lithuania (first period)","polity",1918,1940,False,"Lithuania","Interwar Lithuania, which lost Vilnius to Poland and was annexed by the USSR in 1940.",[])
E("soviet-annexation-baltics","Soviet Annexation of the Baltic States","event",1940,1940,False,"Baltic states","Forced incorporation of Estonia, Latvia and Lithuania into the USSR, followed by deportations.",[])
E("singing-revolution","Singing Revolution","event",1987,1991,False,"Baltic states","Mass non-violent movement, including the 1989 Baltic Way human chain, that restored Baltic independence.",["Baltic Way"])
E("republic-of-estonia","Republic of Estonia","polity",1991,None,True,"Estonia","Baltic republic that restored independence in 1991 and joined the EU and NATO in 2004; a digital-government pioneer.",["Estonia","Eesti"])
E("republic-of-latvia","Republic of Latvia","polity",1991,None,True,"Latvia","Baltic republic independent again from 1991, in the EU and NATO since 2004 and the euro since 2014.",["Latvia","Latvija"])
E("republic-of-lithuania","Republic of Lithuania","polity",1990,None,True,"Lithuania","First Soviet republic to declare independence, in March 1990; EU and NATO member since 2004.",["Lithuania","Lietuva"])

# ---------------- POLAND ----------------
E("polish-lithuanian-commonwealth","Polish-Lithuanian Commonwealth","polity",1569,1795,False,"Poland","Elective monarchy and noble republic, once Europe's largest state, paralysed by the liberum veto and destroyed by partition.",["Rzeczpospolita","Poland-Lithuania"])
E("union-of-lublin","Union of Lublin","event",1569,1569,False,"Poland and Lithuania","Treaty creating a single Commonwealth with one monarch, diet and currency.",[])
E("the-deluge","The Deluge","event",1655,1660,False,"Polish-Lithuanian Commonwealth","Swedish and Russian invasions that devastated Poland-Lithuania and began its long decline.",["Potop"])
E("battle-of-vienna-1683","Battle of Vienna","event",1683,1683,False,"Central Europe","Polish, Imperial and German relief army under Jan III Sobieski broke the Ottoman siege of Vienna.",["Siege of Vienna"])
E("constitution-of-3-may","Constitution of 3 May 1791","event",1791,1791,False,"Polish-Lithuanian Commonwealth","Europe's first modern codified constitution, an attempt at reform that provoked partition.",[])
E("first-partition-of-poland","First Partition of Poland","event",1772,1772,False,"Poland","Russia, Prussia and Austria seized about a third of Commonwealth territory.",[])
E("second-partition-of-poland","Second Partition of Poland","event",1793,1793,False,"Poland","Russia and Prussia took further large territories after the war in defence of the 1791 constitution.",[])
E("kosciuszko-uprising","Kosciuszko Uprising","event",1794,1794,False,"Poland","National insurrection led by Tadeusz Kosciuszko, defeated by Russia and Prussia.",[])
E("third-partition-of-poland","Third Partition of Poland","event",1795,1795,False,"Poland","Final partition erased Poland-Lithuania from the map for 123 years.",[])
E("duchy-of-warsaw","Duchy of Warsaw","polity",1807,1815,False,"Poland","Napoleonic Polish state that revived hopes of independence and supplied troops for the Grande Armee.",["Grand Duchy of Warsaw"])
E("congress-poland","Kingdom of Poland (Congress Poland)","polity",1815,1915,False,"Poland","Russian-ruled Polish kingdom whose autonomy was stripped after the 1830 and 1863 uprisings.",["Congress Poland","Krolestwo Polskie"])
E("november-uprising","November Uprising","event",1830,1831,False,"Poland","Polish revolt against Russian rule, crushed with the loss of the kingdom's army and constitution.",[])
E("january-uprising","January Uprising","event",1863,1864,False,"Poland","Largest Polish insurrection against Russia, followed by Russification and the abolition of serfdom.",[])
E("second-polish-republic","Second Polish Republic","polity",1918,1939,False,"Poland","Poland restored in 1918, victorious over Soviet Russia in 1920, ruled after 1926 by Pilsudski's Sanacja, destroyed in 1939.",["Interwar Poland"])
E("polish-soviet-war","Polish-Soviet War","event",1919,1921,False,"Poland and Soviet Russia","War ended by Poland's victory at the Vistula in 1920 and the Treaty of Riga.",["Miracle on the Vistula"])
E("invasion-of-poland-1939","Invasion of Poland","event",1939,1939,False,"Poland","German attack on 1 September and Soviet attack on 17 September partitioned Poland and began the Second World War.",[])
E("general-government","General Government","polity",1939,1945,False,"Poland","German occupation regime in central Poland, site of mass murder including the extermination camps.",["Generalgouvernement"])
E("warsaw-ghetto-uprising","Warsaw Ghetto Uprising","event",1943,1943,False,"Poland","Jewish armed revolt against deportations to Treblinka, crushed with the ghetto's destruction.",[])
E("warsaw-uprising-1944","Warsaw Uprising","event",1944,1944,False,"Poland","Home Army rising for 63 days, defeated while Soviet forces halted; Warsaw was razed in reprisal.",[])
E("polish-peoples-republic","Polish People's Republic","polity",1947,1989,False,"Poland","Communist Poland, shaken by 1956, 1968, 1970 and 1980 protests and by martial law in 1981.",["PRL","Communist Poland"])
E("solidarity-movement","Solidarity","event",1980,1989,False,"Poland","Independent trade union born in Gdansk under Lech Walesa that led the peaceful end of communist rule.",["Solidarnosc"])
E("polish-martial-law","Polish Martial Law","event",1981,1983,False,"Poland","General Jaruzelski's crackdown that interned Solidarity leaders and suspended civil liberties.",[])
E("polish-round-table","Polish Round Table Talks","event",1989,1989,False,"Poland","Negotiations that produced semi-free elections and the first non-communist government in the bloc.",[])
E("third-polish-republic","Third Polish Republic","polity",1989,None,True,"Poland","Democratic Poland since 1989, in NATO from 1999 and the EU from 2004.",["Poland","Polska"])

# ---------------- AUSTRIA, HUNGARY, BOHEMIA ----------------
E("habsburg-monarchy","Habsburg Monarchy","polity",1526,1804,False,"Central Europe","Composite realm of Austria, Bohemia and Hungary that anchored Catholic Europe and fought the Ottomans and Prussia.",["Danubian monarchy","Austrian Habsburgs"])
E("reign-maria-theresa","Reign of Maria Theresa","reign",1740,1780,False,"Habsburg Monarchy","Only female ruler of the Habsburg lands: survived the succession war, lost Silesia and reformed the state.",[])
E("reign-joseph-ii","Reign of Joseph II","reign",1780,1790,False,"Habsburg Monarchy","Radical enlightened absolutist who abolished serfdom and issued the Patent of Toleration.",[])
E("austrian-empire","Austrian Empire","polity",1804,1867,False,"Austria","Empire proclaimed by Francis II in response to Napoleon, dominant in the German Confederation until 1866.",["Kaisertum Osterreich"])
E("metternich-era","Metternich Era","period",1815,1848,False,"Austria and Europe","Conservative order of censorship, congresses and repression of nationalism directed from Vienna.",["Age of Metternich","Vormarz"])
E("reign-franz-joseph","Reign of Franz Joseph I","reign",1848,1916,False,"Austria-Hungary","Sixty-eight-year reign spanning 1848, the Compromise of 1867, and the outbreak of the First World War.",["Francis Joseph"])
E("austro-hungarian-compromise","Austro-Hungarian Compromise of 1867","event",1867,1867,False,"Austria-Hungary","Agreement creating the Dual Monarchy with separate Austrian and Hungarian governments under one emperor-king.",["Ausgleich"])
E("austro-hungarian-empire","Austro-Hungarian Empire","polity",1867,1918,False,"Central Europe","Multinational dual monarchy of eleven major nationalities that dissolved in defeat in 1918.",["Dual Monarchy","Austria-Hungary","k.u.k. monarchy"])
E("bosnian-annexation-1908","Austro-Hungarian Annexation of Bosnia","event",1908,1908,False,"Austria-Hungary","Formal annexation of Bosnia-Herzegovina, inflaming Serbian nationalism and Russian rivalry.",[])
E("reign-charles-i-austria","Reign of Charles I of Austria","reign",1916,1918,False,"Austria-Hungary","Last Habsburg emperor, whose peace efforts failed and whose empire dissolved in 1918.",["Karl I","Charles IV of Hungary"])
E("first-austrian-republic","First Austrian Republic","polity",1919,1934,False,"Austria","Rump Austrian republic of political violence between Social Democrats and Christian Socials.",["Deutschosterreich"])
E("austrofascism","Federal State of Austria","polity",1934,1938,False,"Austria","Dollfuss and Schuschnigg's clerical-authoritarian state, ended by German annexation.",["Austrofascism","Standestaat"])
E("allied-occupation-austria","Allied Occupation of Austria","period",1945,1955,False,"Austria","Four-power occupation ended by the State Treaty, which restored sovereignty on condition of neutrality.",[])
E("second-austrian-republic","Republic of Austria","polity",1945,None,True,"Austria","Neutral democratic republic, sovereign from 1955 and an EU member since 1995.",["Austria","Osterreich"])
E("kingdom-of-hungary-habsburg","Kingdom of Hungary under the Habsburgs","polity",1526,1867,False,"Hungary","Hungarian crown held by the Habsburgs, partly Ottoman-occupied until 1699 and repeatedly in revolt.",["Royal Hungary"])
E("ottoman-hungary","Ottoman Hungary","polity",1541,1699,False,"Hungary","Central Hungary under Ottoman rule after Mohacs, recovered by the Habsburgs at Karlowitz.",["Budin Eyalet"])
E("rakoczi-uprising","Rakoczi's War of Independence","event",1703,1711,False,"Hungary","Large anti-Habsburg revolt led by Francis II Rakoczi, ended by the Peace of Szatmar.",[])
E("hungarian-revolution-1848","Hungarian Revolution of 1848","event",1848,1849,False,"Hungary","Kossuth's national revolution and war of independence, defeated by Austrian and Russian armies.",[])
E("hungarian-soviet-republic","Hungarian Soviet Republic","polity",1919,1919,False,"Hungary","Bela Kun's 133-day communist regime, overthrown after Romanian invasion.",[])
E("treaty-of-trianon","Treaty of Trianon","event",1920,1920,False,"Hungary","Peace treaty that reduced Hungary to a third of its prewar territory, a lasting national grievance.",[])
E("horthy-regency","Horthy Regency","reign",1920,1944,False,"Hungary","Admiral Miklos Horthy ruled Hungary as regent of a kingdom without a king, allying with Nazi Germany.",[])
E("hungarian-peoples-republic","Hungarian People's Republic","polity",1949,1989,False,"Hungary","Communist Hungary under Rakosi then Kadar's 'goulash communism' after the crushed 1956 revolution.",[])
E("hungarian-revolution-1956","Hungarian Revolution of 1956","event",1956,1956,False,"Hungary","National uprising against Soviet domination, crushed by Red Army intervention with thousands killed.",[])
E("republic-of-hungary","Hungary","polity",1989,None,True,"Hungary","Democratic republic since 1989, in NATO from 1999 and the EU from 2004; governed by Viktor Orban since 2010.",["Magyarorszag","Hungary"])
E("kingdom-of-bohemia-habsburg","Kingdom of Bohemia under the Habsburgs","polity",1526,1918,False,"Czech lands","Bohemian crown lands within the Habsburg realm, Germanised after 1620 and industrialised in the 19th century.",[])
E("battle-of-white-mountain","Battle of White Mountain","event",1620,1620,False,"Bohemia","Catholic victory outside Prague that ended Bohemian independence and began forced re-Catholicisation.",[])
E("czechoslovakia","Czechoslovakia","polity",1918,1992,False,"Central Europe","State of Czechs and Slovaks founded in 1918, dismembered in 1938-39, communist from 1948, split in 1993.",["CSR","Ceskoslovensko"])
E("masaryk-presidency","Presidency of Tomas Masaryk","reign",1918,1935,False,"Czechoslovakia","Founding president who made interwar Czechoslovakia central Europe's most durable democracy.",[])
E("sudetenland-crisis","Sudeten Crisis and Annexation","event",1938,1938,False,"Czechoslovakia","German-speaking borderlands ceded under the Munich Agreement, followed by occupation in March 1939.",[])
E("protectorate-bohemia-moravia","Protectorate of Bohemia and Moravia","polity",1939,1945,False,"Czech lands","German protectorate over the Czech lands, site of Heydrich's assassination and the Lidice massacre.",[])
E("czechoslovak-coup-1948","Czechoslovak Coup of 1948","event",1948,1948,False,"Czechoslovakia","Communist seizure of power in February 1948 that ended postwar pluralism.",["Victorious February"])
E("prague-spring","Prague Spring","event",1968,1968,False,"Czechoslovakia","Dubcek's 'socialism with a human face', crushed by a Warsaw Pact invasion in August 1968.",[])
E("velvet-revolution","Velvet Revolution","event",1989,1989,False,"Czechoslovakia","Non-violent mass protests that ended communist rule and made Vaclav Havel president.",[])
E("velvet-divorce","Velvet Divorce","event",1993,1993,False,"Czechoslovakia","Peaceful split of Czechoslovakia into the Czech Republic and Slovakia on 1 January 1993.",[])
E("czech-republic","Czech Republic","polity",1993,None,True,"Czech lands","Central European republic since 1993, in NATO from 1999 and the EU from 2004.",["Czechia","Ceska republika"])
E("slovak-republic","Slovakia","polity",1993,None,True,"Slovakia","Independent Slovak republic since 1993, in NATO and the EU from 2004 and the euro from 2009.",["Slovak Republic","Slovensko"])
E("slovak-state-1939","Slovak State","polity",1939,1945,False,"Slovakia","German client state under Jozef Tiso, which deported most Slovak Jews and faced the 1944 national uprising.",["First Slovak Republic"])

# ---------------- BALKANS ----------------
E("greek-war-of-independence","Greek War of Independence","event",1821,1829,False,"Greece","Revolt against Ottoman rule, won with British, French and Russian help at Navarino and by Russian invasion.",["Greek Revolution"])
E("first-hellenic-republic","First Hellenic Republic","polity",1822,1832,False,"Greece","Provisional revolutionary government under Kapodistrias until the powers imposed a monarchy.",[])
E("kingdom-of-greece","Kingdom of Greece","polity",1832,1924,False,"Greece","Monarchy created by the great powers, which expanded through the Balkan Wars and collapsed after the Asia Minor defeat.",["Vasileion tis Ellados"])
E("reign-otto-of-greece","Reign of Otto of Greece","reign",1832,1862,False,"Kingdom of Greece","Bavarian prince installed as first king of Greece, deposed by a military revolt.",[])
E("reign-george-i-greece","Reign of George I of Greece","reign",1863,1913,False,"Kingdom of Greece","Long-reigning Danish-born king who gained the Ionian Islands, Thessaly and Macedonia; assassinated in 1913.",[])
E("balkan-wars","Balkan Wars","event",1912,1913,False,"Balkans","Two wars that expelled the Ottomans from most of Europe and then set the victors against each other over Macedonia.",[])
E("greco-turkish-war-1919","Greco-Turkish War","event",1919,1922,False,"Greece and Turkey","Greek invasion of Anatolia defeated by Kemal's forces, ending with the burning of Smyrna.",["Asia Minor Catastrophe"])
E("greek-turkish-population-exchange","Greek-Turkish Population Exchange","event",1923,1923,False,"Greece and Turkey","Compulsory exchange under the Lausanne Convention that uprooted about 1.6 million people.",[])
E("second-hellenic-republic","Second Hellenic Republic","polity",1924,1935,False,"Greece","Interwar republic of coups and refugee resettlement, ended by the restoration of the monarchy.",[])
E("metaxas-regime","Metaxas Regime","reign",1936,1941,False,"Greece","Authoritarian '4th of August' government that rejected Mussolini's 1940 ultimatum with 'Oxi'.",[])
E("axis-occupation-greece","Axis Occupation of Greece","period",1941,1944,False,"Greece","German, Italian and Bulgarian occupation with famine, the destruction of Greek Jewry and mass resistance.",[])
E("greek-civil-war","Greek Civil War","event",1946,1949,False,"Greece","Communist insurgency defeated by the government with British and then American support under the Truman Doctrine.",[])
E("greek-junta","Greek Military Junta","polity",1967,1974,False,"Greece","Colonels' dictatorship that abolished the monarchy and fell after the Cyprus crisis.",["Regime of the Colonels"])
E("third-hellenic-republic","Hellenic Republic","polity",1974,None,True,"Greece","Democratic Greece since the fall of the junta, an EU member since 1981 and euro member since 2001.",["Greece","Hellas"])
E("greek-debt-crisis","Greek Government-Debt Crisis","event",2009,2018,False,"Greece","Sovereign-debt collapse and three bailout programmes with severe austerity inside the eurozone.",[])
E("first-serbian-uprising","First Serbian Uprising","event",1804,1813,False,"Serbia","Revolt under Karadjordje against Ottoman rule that began modern Serbian statehood.",[])
E("principality-of-serbia","Principality of Serbia","polity",1817,1882,False,"Serbia","Autonomous then independent Serbian principality under the Obrenovic and Karadjordjevic houses.",[])
E("kingdom-of-serbia","Kingdom of Serbia","polity",1882,1918,False,"Serbia","Independent kingdom that won the Balkan Wars, suffered occupation in 1915 and became the core of Yugoslavia.",[])
E("congress-of-berlin","Congress of Berlin","event",1878,1878,False,"Balkans","Great-power settlement that recognised Serbia, Montenegro and Romania and shrank Bulgaria.",["Treaty of Berlin"])
E("principality-of-bulgaria","Principality of Bulgaria","polity",1878,1908,False,"Bulgaria","Autonomous Ottoman tributary created at Berlin, which absorbed Eastern Rumelia in 1885.",[])
E("kingdom-of-bulgaria","Kingdom of Bulgaria","polity",1908,1946,False,"Bulgaria","Independent tsardom that fought on the losing side in both world wars.",["Tsardom of Bulgaria"])
E("peoples-republic-bulgaria","People's Republic of Bulgaria","polity",1946,1990,False,"Bulgaria","Communist state closely tied to the USSR under Todor Zhivkov for 35 years.",[])
E("republic-of-bulgaria","Republic of Bulgaria","polity",1990,None,True,"Bulgaria","Democratic republic since 1990, in NATO from 2004 and the EU from 2007.",["Bulgaria"])
E("principalities-wallachia-moldavia","Wallachia and Moldavia","polity",1500,1859,False,"Romania","Ottoman tributary principalities, later under Phanariot then Russian-protected regimes, united in 1859.",["Danubian Principalities"])
E("united-principalities-romania","United Principalities of Romania","polity",1859,1881,False,"Romania","Union under Alexandru Ioan Cuza and then Carol I, independent from the Ottomans in 1878.",[])
E("kingdom-of-romania","Kingdom of Romania","polity",1881,1947,False,"Romania","Kingdom that doubled in size as Greater Romania in 1918 and fell to communism after 1944.",["Greater Romania"])
E("socialist-republic-romania","Socialist Republic of Romania","polity",1947,1989,False,"Romania","Communist Romania, independent-minded under Ceausescu's increasingly repressive personality cult.",[])
E("romanian-revolution-1989","Romanian Revolution of 1989","event",1989,1989,False,"Romania","Violent uprising that overthrew and executed Nicolae Ceausescu in December 1989.",[])
E("republic-of-romania","Romania","polity",1989,None,True,"Romania","Democratic republic since 1989, in NATO from 2004 and the EU from 2007.",["Romania"])
E("principality-of-montenegro","Principality and Kingdom of Montenegro","polity",1852,1918,False,"Montenegro","Independent mountain state under the Petrovic-Njegos dynasty, recognised in 1878 and merged into Yugoslavia.",[])
E("albanian-independence","Albanian Declaration of Independence","event",1912,1912,False,"Albania","Ismail Qemali proclaimed Albanian independence at Vlore during the First Balkan War.",[])
E("kingdom-of-albania","Kingdom of Albania","polity",1928,1939,False,"Albania","Zog I's kingdom, increasingly an Italian dependency until Italy invaded in 1939.",[])
E("peoples-socialist-republic-albania","People's Socialist Republic of Albania","polity",1946,1992,False,"Albania","Enver Hoxha's isolated Stalinist state, which broke with Yugoslavia, the USSR and finally China.",[])
E("republic-of-albania","Republic of Albania","polity",1992,None,True,"Albania","Post-communist democracy since 1992, a NATO member from 2009 and EU candidate.",["Albania","Shqiperia"])
E("kingdom-of-yugoslavia","Kingdom of Yugoslavia","polity",1918,1941,False,"Yugoslavia","Kingdom of Serbs, Croats and Slovenes renamed Yugoslavia in 1929, a royal dictatorship destroyed by Axis invasion.",["Kingdom of Serbs Croats and Slovenes"])
E("invasion-of-yugoslavia-1941","Axis Invasion of Yugoslavia","event",1941,1941,False,"Yugoslavia","German-led attack that dismembered the kingdom and produced the Ustase state and partisan resistance.",[])
E("independent-state-of-croatia","Independent State of Croatia","polity",1941,1945,False,"Croatia","Ustase puppet state under Ante Pavelic responsible for the Jasenovac camps and genocide of Serbs, Jews and Roma.",["NDH"])
E("socialist-yugoslavia","Socialist Federal Republic of Yugoslavia","polity",1945,1992,False,"Yugoslavia","Tito's federation of six republics, non-aligned and self-managing, which disintegrated in war after his death.",["SFRY","Tito's Yugoslavia"])
E("tito-rule","Rule of Josip Broz Tito","reign",1945,1980,False,"Yugoslavia","Partisan leader turned president for life who split with Stalin in 1948 and led the Non-Aligned Movement.",["Marshal Tito"])
E("yugoslav-wars","Yugoslav Wars","event",1991,2001,False,"Balkans","Series of wars accompanying Yugoslavia's breakup, with ethnic cleansing, siege warfare and NATO intervention.",["Balkan wars of the 1990s"])
E("ten-day-war-slovenia","Slovenian Ten-Day War","event",1991,1991,False,"Slovenia","Brief conflict after Slovenia's independence declaration, ending with Yugoslav withdrawal.",[])
E("croatian-war-of-independence","Croatian War of Independence","event",1991,1995,False,"Croatia","War between Croatia and Serb forces, including the siege of Dubrovnik and Vukovar and Operation Storm.",["Homeland War"])
E("bosnian-war","Bosnian War","event",1992,1995,False,"Bosnia and Herzegovina","Three-way war with the siege of Sarajevo and genocide at Srebrenica, ended by the Dayton Agreement.",[])
E("srebrenica-genocide","Srebrenica Genocide","event",1995,1995,False,"Bosnia and Herzegovina","Massacre of over 8,000 Bosniak men and boys by Bosnian Serb forces in a UN safe area.",["Srebrenica massacre"])
E("dayton-agreement","Dayton Agreement","event",1995,1995,False,"Bosnia and Herzegovina","US-brokered peace ending the Bosnian War and creating a federal state of two entities.",["Dayton Accords"])
E("kosovo-war","Kosovo War","event",1998,1999,False,"Kosovo","Insurgency and Serbian counter-offensive that triggered NATO's 78-day bombing campaign and UN administration.",[])
E("fr-yugoslavia","Federal Republic of Yugoslavia","polity",1992,2003,False,"Balkans","Rump federation of Serbia and Montenegro under Slobodan Milosevic, renamed Serbia and Montenegro in 2003.",["FRY"])
E("serbia-and-montenegro","Serbia and Montenegro","polity",2003,2006,False,"Balkans","Loose state union that dissolved when Montenegro voted for independence in 2006.",[])
E("republic-of-serbia","Republic of Serbia","polity",2006,None,True,"Serbia","Independent Serbia since Montenegro's separation; an EU candidate that does not recognise Kosovo.",["Serbia","Srbija"])
E("republic-of-montenegro","Montenegro","polity",2006,None,True,"Montenegro","Adriatic republic independent since a 2006 referendum, a NATO member since 2017.",["Crna Gora"])
E("republic-of-croatia","Republic of Croatia","polity",1991,None,True,"Croatia","Independent since 1991, a NATO member from 2009, EU from 2013 and eurozone from 2023.",["Croatia","Hrvatska"])
E("republic-of-slovenia","Republic of Slovenia","polity",1991,None,True,"Slovenia","First Yugoslav republic to secede successfully; joined the EU and NATO in 2004 and the euro in 2007.",["Slovenia","Slovenija"])
E("bosnia-and-herzegovina","Bosnia and Herzegovina","polity",1992,None,True,"Bosnia and Herzegovina","Independent state since 1992, governed since Dayton as a federation of two entities with international oversight.",["Bosnia"])
E("north-macedonia","North Macedonia","polity",1991,None,True,"North Macedonia","Independent since 1991; renamed under the 2018 Prespa Agreement and a NATO member since 2020.",["Macedonia","Republic of Macedonia"])
E("republic-of-kosovo","Republic of Kosovo","polity",2008,None,True,"Kosovo","Declared independence from Serbia in 2008, recognised by about half the world's states.",["Kosova"])
E("republic-of-ireland","Ireland","polity",1922,None,True,"Ireland","Independent Irish state, a republic from 1949, neutral, and an EU member since 1973.",["Irish Free State","Eire","Republic of Ireland"])
E("irish-war-of-independence","Irish War of Independence","event",1919,1921,False,"Ireland","Guerrilla war by the IRA that led to the Anglo-Irish Treaty and the Irish Free State.",["Anglo-Irish War"])
E("irish-civil-war","Irish Civil War","event",1922,1923,False,"Ireland","Conflict between pro- and anti-Treaty forces over partition and the oath to the crown.",[])
E("great-irish-famine","Great Irish Famine","event",1845,1852,False,"Ireland","Potato blight famine that killed about a million people and drove a million more to emigrate.",["An Gorta Mor","Irish Potato Famine"])
E("the-troubles","The Troubles","event",1968,1998,False,"Northern Ireland","Three decades of conflict between republicans, loyalists and the British state, ended by the Good Friday Agreement.",["Northern Ireland conflict"])
E("good-friday-agreement","Good Friday Agreement","event",1998,1998,False,"Northern Ireland","Peace settlement creating power-sharing devolution and North-South institutions.",["Belfast Agreement"])
E("republic-of-malta","Republic of Malta","polity",1964,None,True,"Malta","Mediterranean island state independent from Britain in 1964, a republic from 1974 and EU member from 2004.",["Malta"])
E("hospitaller-malta","Hospitaller Malta","polity",1530,1798,False,"Malta","Rule of the Knights of St John, who withstood the Great Siege of 1565 and built Valletta.",["Knights of Malta"])
