import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _mn_common import E, ROWS, set_region
set_region('east-asia')

# ---------------- JAPAN ----------------
E("sengoku-period-late","Late Sengoku Period","period",1500,1600,False,"Japan","Century of warring daimyo, firearms and castle towns, unified in stages by Nobunaga, Hideyoshi and Ieyasu.",["Warring States period of Japan"])
E("oda-nobunaga-rule","Rule of Oda Nobunaga","reign",1568,1582,False,"Japan","Warlord who seized Kyoto, broke the Buddhist militant orders and began unifying Japan before being betrayed at Honno-ji.",[])
E("toyotomi-hideyoshi-rule","Rule of Toyotomi Hideyoshi","reign",1582,1598,False,"Japan","Completed unification, froze the social order by sword hunts and land surveys, and invaded Korea twice.",[])
E("battle-of-sekigahara","Battle of Sekigahara","event",1600,1600,False,"Japan","Tokugawa Ieyasu's decisive victory that opened the way to the shogunate.",[])
E("tokugawa-shogunate","Tokugawa Shogunate","polity",1603,1868,False,"Japan","Edo-based military government that gave Japan 265 years of peace under strict social order and limited foreign contact.",["Edo period","Tokugawa bakufu"])
E("sakoku","Sakoku","period",1639,1854,False,"Tokugawa Japan","Policy of closed borders permitting only limited Dutch, Chinese, Korean and Ryukyuan contact.",["closed country policy"])
E("shimabara-rebellion","Shimabara Rebellion","event",1637,1638,False,"Tokugawa Japan","Christian and peasant revolt in Kyushu whose suppression sealed the proscription of Christianity.",[])
E("perry-expedition","Perry Expedition","event",1853,1854,False,"Japan","American gunboat diplomacy that forced Japan open with the Convention of Kanagawa.",["Opening of Japan","Black Ships"])
E("boshin-war","Boshin War","event",1868,1869,False,"Japan","Civil war in which imperial loyalists defeated the shogunate and restored direct rule to the emperor.",[])
E("meiji-restoration","Meiji Restoration","event",1868,1868,False,"Japan","Restoration of imperial rule and the start of rapid, state-led modernisation on Western models.",["Meiji Ishin"])
E("empire-of-japan","Empire of Japan","polity",1868,1947,False,"Japan","Constitutional empire that industrialised, defeated China and Russia, built a colonial empire and lost the Pacific War.",["Dai Nippon Teikoku","Imperial Japan"])
E("meiji-era","Meiji Era","era",1868,1912,False,"Empire of Japan","Reign of Emperor Meiji: abolition of the samurai class, conscription, industry, constitution and imperial expansion.",["reign of Emperor Meiji","Mutsuhito"])
E("abolition-of-the-han","Abolition of the Han","event",1871,1871,False,"Meiji Japan","Domains replaced by prefectures, ending feudal decentralisation.",["haihan chiken"])
E("satsuma-rebellion","Satsuma Rebellion","event",1877,1877,False,"Meiji Japan","Last samurai revolt, led by Saigo Takamori and crushed by the conscript army.",[])
E("meiji-constitution","Meiji Constitution","event",1889,1889,False,"Empire of Japan","Prussian-inspired constitution granting a Diet while vesting sovereignty in the emperor.",[])
E("first-sino-japanese-war","First Sino-Japanese War","event",1894,1895,False,"East Asia","Japanese victory that took Taiwan and ended Chinese suzerainty over Korea.",[])
E("japanese-annexation-of-korea","Japanese Annexation of Korea","event",1910,1910,False,"Korea and Japan","Treaty imposed after the 1905 protectorate made Korea a Japanese colony until 1945.",[])
E("taisho-era","Taisho Era","era",1912,1926,False,"Empire of Japan","Reign of Emperor Taisho: party cabinets, universal male suffrage, rice riots and the 1923 Kanto earthquake.",["reign of Emperor Taisho","Yoshihito"])
E("taisho-democracy","Taisho Democracy","period",1912,1932,False,"Japan","Era of party government, mass politics and liberal culture, ended by militarist assassinations.",[])
E("great-kanto-earthquake","Great Kanto Earthquake","event",1923,1923,False,"Japan","Quake and firestorm that destroyed much of Tokyo and Yokohama and killed over 100,000.",[])
E("showa-era","Showa Era","era",1926,1989,False,"Japan","Reign of Emperor Hirohito: militarism, war, defeat, occupation and the postwar economic miracle.",["reign of Emperor Hirohito","Hirohito"])
E("manchurian-incident","Manchurian Incident","event",1931,1931,False,"Japan and China","Staged railway explosion used to justify the Japanese conquest of Manchuria.",["Mukden Incident"])
E("manchukuo","Manchukuo","polity",1932,1945,False,"Northeast Asia","Japanese puppet state in Manchuria nominally headed by the last Qing emperor Puyi.",[])
E("february-26-incident","February 26 Incident","event",1936,1936,False,"Japan","Failed young-officers' coup in Tokyo after which the army dominated the government.",[])
E("second-sino-japanese-war","Second Sino-Japanese War","event",1937,1945,False,"East Asia","Full-scale Japanese invasion of China, part of the Second World War, with 15-20 million Chinese deaths.",["War of Resistance"])
E("nanjing-massacre","Nanjing Massacre","event",1937,1938,False,"China","Mass killing and rape of Chinese civilians and prisoners after the fall of Nanjing.",["Rape of Nanking"])
E("attack-on-pearl-harbor","Attack on Pearl Harbor","event",1941,1941,False,"Pacific War","Japanese carrier strike on 7 December 1941 that brought the United States into the Second World War.",[])
E("pacific-war","Pacific War","event",1941,1945,False,"Asia and the Pacific","War between Japan and the Allies from Pearl Harbor to the surrender aboard USS Missouri.",[])
E("atomic-bombings","Atomic Bombings of Hiroshima and Nagasaki","event",1945,1945,False,"Japan","First use of nuclear weapons in war, killing well over 100,000 and hastening Japan's surrender.",["Hiroshima","Nagasaki"])
E("occupation-of-japan","Allied Occupation of Japan","period",1945,1952,False,"Japan","MacArthur's SCAP administration demilitarised Japan, wrote a new constitution and reformed land and industry.",["SCAP","Occupied Japan"])
E("japanese-constitution-1947","Constitution of Japan","event",1947,1947,False,"Japan","Postwar constitution establishing popular sovereignty, a symbolic emperor and Article 9's renunciation of war.",["Postwar Constitution","Article 9"])
E("state-of-japan","Japan","polity",1947,None,True,"Japan","Postwar parliamentary state under the 1947 constitution, long the world's second-largest economy.",["Nippon","Nihon"])
E("treaty-of-san-francisco","Treaty of San Francisco","event",1951,1952,False,"Japan","Peace treaty restoring Japanese sovereignty, accompanied by the US-Japan security treaty.",[])
E("japanese-economic-miracle","Japanese Economic Miracle","era",1955,1973,False,"Japan","Two decades of double-digit growth that made Japan an industrial giant, symbolised by the 1964 Tokyo Olympics.",[])
E("japanese-asset-bubble","Japanese Asset Price Bubble and Lost Decades","event",1986,2005,False,"Japan","Stock and land bubble whose collapse produced prolonged stagnation and deflation.",["Lost Decade"])
E("heisei-era","Heisei Era","era",1989,2019,False,"Japan","Reign of Emperor Akihito: bubble collapse, Kobe earthquake, Aum attack and the 2011 triple disaster.",["reign of Emperor Akihito","Akihito"])
E("kobe-earthquake","Great Hanshin Earthquake","event",1995,1995,False,"Japan","Kobe earthquake that killed over 6,000 and exposed weaknesses in disaster response.",["Kobe earthquake"])
E("tohoku-earthquake-fukushima","Tohoku Earthquake and Fukushima Disaster","event",2011,2011,False,"Japan","Magnitude 9 quake, tsunami killing about 18,000, and the Fukushima Daiichi nuclear meltdowns.",["3.11","Fukushima"])
E("reiwa-era","Reiwa Era","era",2019,None,True,"Japan","Reign of Emperor Naruhito, beginning with his father's abdication in 2019.",["reign of Emperor Naruhito","Naruhito"])
E("abe-premierships","Premierships of Shinzo Abe","reign",2006,2020,False,"Japan","Japan's longest-serving prime minister (2006-07, 2012-20): Abenomics, security reinterpretation, assassinated in 2022.",["Abenomics"])
E("ryukyu-kingdom-modern","Kingdom of Ryukyu (late)","polity",1500,1879,False,"Japan","Okinawan maritime kingdom, a Satsuma vassal from 1609, annexed as Okinawa Prefecture in 1879.",["Ryukyu","Okinawa"])
E("battle-of-okinawa","Battle of Okinawa","event",1945,1945,False,"Japan","Eighty-two-day battle that killed perhaps a quarter of Okinawan civilians; US administration lasted to 1972.",[])
E("okinawa-reversion","Reversion of Okinawa","event",1972,1972,False,"Japan","Return of Okinawa to Japanese sovereignty, with US bases remaining.",[])

# ---------------- CHINA ----------------
E("late-ming-dynasty","Late Ming Dynasty","period",1500,1644,False,"China","Silver-fuelled commerce, population growth and crisis ending in rebellion, famine and Manchu conquest.",["Ming"])
E("qing-dynasty","Qing Dynasty","polity",1636,1912,False,"China","Last imperial dynasty, Manchu-ruled, which tripled China's territory then fell to internal revolt and foreign pressure.",["Manchu dynasty","Great Qing"])
E("manchu-conquest-of-china","Manchu Conquest of China","event",1618,1683,False,"China","Qing conquest from Beijing's fall in 1644 to the taking of Taiwan in 1683.",[])
E("kangxi-reign","Kangxi Reign","reign",1661,1722,False,"Qing Dynasty","Sixty-one-year reign that consolidated Qing rule, took Taiwan and pushed into Mongolia and Tibet.",["Kangxi Emperor"])
E("qianlong-reign","Qianlong Reign","reign",1735,1796,False,"Qing Dynasty","High Qing prosperity, conquest of Xinjiang and the Macartney embassy's rebuff.",["Qianlong Emperor"])
E("canton-system","Canton System","polity",1757,1842,False,"Qing China","Restriction of Western trade to Guangzhou through licensed hong merchants, ended by the Opium War.",[])
E("first-opium-war","First Opium War","event",1839,1842,False,"China","British victory forcing the Treaty of Nanking, ceding Hong Kong and opening treaty ports.",[])
E("unequal-treaties","Unequal Treaties","era",1842,1943,False,"China","Century of imposed treaties granting extraterritoriality, indemnities and concessions to foreign powers.",["Century of Humiliation"])
E("taiping-rebellion","Taiping Rebellion","event",1850,1864,False,"China","Millenarian civil war under Hong Xiuquan that killed perhaps 20-30 million people.",["Taiping Heavenly Kingdom"])
E("second-opium-war","Second Opium War","event",1856,1860,False,"China","Anglo-French campaign that burned the Summer Palace and opened more of China to foreign trade and missions.",["Arrow War"])
E("self-strengthening-movement","Self-Strengthening Movement","era",1861,1895,False,"Qing China","Reform effort to adopt Western arms and industry while preserving Confucian institutions.",["Tongzhi Restoration"])
E("cixi-regency","Regency of Empress Dowager Cixi","reign",1861,1908,False,"Qing China","Cixi dominated the Qing court for almost fifty years, blocking then belatedly embracing reform.",["Empress Dowager Cixi"])
E("hundred-days-reform","Hundred Days' Reform","event",1898,1898,False,"Qing China","Guangxu Emperor's rapid reform programme, ended by Cixi's coup.",[])
E("boxer-rebellion","Boxer Rebellion","event",1899,1901,False,"China","Anti-foreign uprising crushed by an eight-nation force, followed by a crippling indemnity.",["Boxer Uprising"])
E("xinhai-revolution","Xinhai Revolution","event",1911,1912,False,"China","Wuchang uprising and provincial secessions that ended two millennia of imperial rule.",["1911 Revolution"])
E("republic-of-china-mainland","Republic of China (mainland era)","polity",1912,1949,False,"China","Republic founded by Sun Yat-sen, ruled by Yuan Shikai, warlords and then the Kuomintang until defeat by the communists.",["ROC","Nationalist China"])
E("yuan-shikai-rule","Rule of Yuan Shikai","reign",1912,1916,False,"Republic of China","First president who dissolved parliament and briefly proclaimed himself emperor in 1916.",[])
E("warlord-era","Warlord Era","period",1916,1928,False,"China","Fragmentation of China among regional militarists after Yuan Shikai's death.",[])
E("may-fourth-movement","May Fourth Movement","event",1919,1919,False,"China","Student protests against the Versailles settlement that catalysed Chinese nationalism and the New Culture Movement.",[])
E("founding-of-the-ccp","Founding of the Chinese Communist Party","event",1921,1921,False,"China","First congress in Shanghai established the CCP with Comintern support.",["CCP"])
E("northern-expedition","Northern Expedition","event",1926,1928,False,"China","Chiang Kai-shek's campaign that nominally unified China under the Kuomintang.",[])
E("nanjing-decade","Nanjing Decade","period",1927,1937,False,"Republic of China","Decade of Nationalist state-building interrupted by communist insurgency and Japanese encroachment.",[])
E("chinese-civil-war","Chinese Civil War","event",1927,1949,False,"China","Intermittent war between Nationalists and Communists, won by the CCP in 1949.",[])
E("long-march","Long March","event",1934,1935,False,"China","Communist retreat of some 9,000 kilometres during which Mao secured party leadership.",[])
E("peoples-republic-of-china","People's Republic of China","polity",1949,None,True,"China","Communist state proclaimed by Mao on 1 October 1949, now the world's most populous nation for most of its history and second-largest economy.",["PRC","China"])
E("mao-era","Mao Era","reign",1949,1976,False,"People's Republic of China","Land reform, Korean War, Great Leap Forward famine and Cultural Revolution under Mao Zedong.",["Mao Zedong"])
E("chinese-annexation-of-tibet","Chinese Annexation of Tibet","event",1950,1951,False,"Tibet and China","PLA entry into Tibet and the Seventeen Point Agreement, followed by the Dalai Lama's flight in 1959.",[])
E("great-leap-forward","Great Leap Forward","event",1958,1962,False,"People's Republic of China","Forced collectivisation and industrial campaign that caused a famine killing tens of millions.",["Great Chinese Famine"])
E("sino-soviet-split","Sino-Soviet Split","event",1960,1989,False,"China and Soviet Union","Ideological and strategic rupture between the communist giants, including border clashes in 1969.",[])
E("cultural-revolution","Cultural Revolution","event",1966,1976,False,"People's Republic of China","Mao's mass campaign against 'revisionists' that closed schools, destroyed heritage and killed over a million.",[])
E("nixon-visit-china","Nixon's Visit to China","event",1972,1972,False,"China and the United States","Opening of relations that realigned Cold War diplomacy; the PRC took China's UN seat in 1971.",[])
E("deng-era","Deng Xiaoping Era","reign",1978,1992,False,"People's Republic of China","Reform and opening: household farming, special economic zones, and the Tiananmen crackdown.",["Deng Xiaoping"])
E("chinese-reform-and-opening","Reform and Opening Up","era",1978,None,True,"People's Republic of China","Market reforms that lifted hundreds of millions from poverty and made China a manufacturing superpower.",["gaige kaifang"])
E("one-child-policy","One-Child Policy","polity",1980,2016,False,"People's Republic of China","Coercive birth-limitation programme that reshaped China's demography.",[])
E("tiananmen-square-1989","Tiananmen Square Protests and Massacre","event",1989,1989,False,"People's Republic of China","Seven weeks of pro-democracy protests ended by military force on 3-4 June 1989.",["June Fourth"])
E("jiang-zemin-era","Jiang Zemin Era","reign",1989,2002,False,"People's Republic of China","Consolidation after Tiananmen, WTO accession and the Hong Kong and Macau handovers.",[])
E("hu-jintao-era","Hu Jintao Era","reign",2002,2012,False,"People's Republic of China","Rapid growth, the 2008 Beijing Olympics and stimulus after the global financial crisis.",[])
E("xi-jinping-era","Xi Jinping Era","reign",2012,None,True,"People's Republic of China","Anti-corruption campaign, Belt and Road, term-limit abolition, Xinjiang repression and zero-COVID.",["Xi Jinping"])
E("chinese-wto-accession","Chinese Accession to the WTO","event",2001,2001,False,"China","Entry into the World Trade Organization that accelerated China's export-led growth.",[])
E("belt-and-road-initiative","Belt and Road Initiative","era",2013,None,True,"People's Republic of China","Global infrastructure and lending programme announced by Xi Jinping in 2013.",["One Belt One Road","BRI"])
E("british-hong-kong","British Hong Kong","polity",1842,1997,False,"Hong Kong","Crown colony ceded in 1842 and leased in 1898 that became a global financial centre.",[])
E("hong-kong-handover","Handover of Hong Kong","event",1997,1997,False,"Hong Kong","Transfer of sovereignty to China on 1 July 1997 under 'one country, two systems'.",[])
E("hong-kong-sar","Hong Kong Special Administrative Region","polity",1997,None,True,"China","Autonomous Chinese territory whose freedoms narrowed after the 2019 protests and 2020 national security law.",["Hong Kong"])
E("hong-kong-protests-2019","Hong Kong Protests of 2019","event",2019,2020,False,"Hong Kong","Mass movement against an extradition bill, answered by Beijing's national security law.",[])
E("portuguese-macau","Portuguese Macau","polity",1557,1999,False,"Macau","Oldest European settlement in East Asia, returned to China in 1999.",["Macao"])
E("macau-sar","Macau Special Administrative Region","polity",1999,None,True,"China","Chinese special administrative region and the world's largest gambling centre.",["Macao"])
E("republic-of-china-taiwan","Republic of China on Taiwan","polity",1949,None,True,"Taiwan","Nationalist government relocated to Taipei in 1949; now a democracy claimed by the PRC.",["Taiwan","ROC"])
E("japanese-taiwan","Japanese Taiwan","polity",1895,1945,False,"Taiwan","Fifty years of Japanese colonial rule that industrialised the island.",[])
E("february-28-incident","February 28 Incident","event",1947,1947,False,"Taiwan","Nationalist suppression of a Taiwanese uprising, followed by the White Terror.",[])
E("taiwan-martial-law","Taiwanese Martial Law Period","period",1949,1987,False,"Taiwan","Thirty-eight years of one-party Kuomintang rule under martial law and the White Terror.",[])
E("chiang-kai-shek-rule","Rule of Chiang Kai-shek","reign",1928,1975,False,"China and Taiwan","Nationalist leader who unified China in 1928, lost the civil war and governed Taiwan until his death.",[])
E("taiwanese-democratisation","Taiwanese Democratisation","period",1987,1996,False,"Taiwan","Lifting of martial law, party competition and the first direct presidential election in 1996.",[])
E("taiwan-strait-crises","Taiwan Strait Crises","event",1954,1996,False,"East Asia","Series of military confrontations between the PRC and Taiwan involving American intervention.",[])

# ---------------- MONGOLIA & KOREA ----------------
E("dzungar-khanate","Dzungar Khanate","polity",1634,1755,False,"Central Asia","Last great steppe empire, destroyed by the Qing in a campaign of near-annihilation.",["Zungar"],"high","central-asia")
E("qing-mongolia","Qing Mongolia","polity",1691,1911,False,"Mongolia","Outer and Inner Mongolia under Qing administration through the Manchu-Mongol aristocratic system.",[])
E("bogd-khanate-mongolia","Bogd Khanate of Mongolia","polity",1911,1924,False,"Mongolia","Theocratic Mongolian state under the Jebtsundamba Khutughtu after the Qing collapse.",[])
E("mongolian-peoples-republic","Mongolian People's Republic","polity",1924,1992,False,"Mongolia","Second communist state in the world, a Soviet satellite with purges of the Buddhist clergy.",[])
E("mongolia","Mongolia","polity",1992,None,True,"Mongolia","Democratic parliamentary republic since 1992 with a mining-based economy.",[])
E("joseon-late","Late Joseon Dynasty","period",1500,1897,False,"Korea","Neo-Confucian kingdom that survived the Imjin and Manchu invasions and pursued isolation until forced open.",["Choson","Yi dynasty"])
E("imjin-war","Imjin War","event",1592,1598,False,"Korea","Hideyoshi's two invasions of Korea, repelled with Ming aid and Admiral Yi Sun-sin's naval victories.",["Japanese invasions of Korea"])
E("korean-empire","Korean Empire","polity",1897,1910,False,"Korea","Gojong's proclaimed empire, which attempted reform before becoming a Japanese protectorate and colony.",["Daehan Jeguk"])
E("japanese-colonial-korea","Japanese Colonial Rule in Korea","polity",1910,1945,False,"Korea","Thirty-five years of colonial rule with land expropriation, assimilation policy and wartime forced labour.",[])
E("march-first-movement","March First Movement","event",1919,1919,False,"Korea","Nationwide independence demonstrations suppressed with thousands killed.",[])
E("division-of-korea","Division of Korea","event",1945,1945,False,"Korea","American and Soviet occupation zones split at the 38th parallel, hardening into two states.",[])
E("republic-of-korea","Republic of Korea","polity",1948,None,True,"South Korea","South Korean state founded in 1948, which industrialised rapidly and democratised in 1987.",["South Korea","Hanguk"])
E("dprk","Democratic People's Republic of Korea","polity",1948,None,True,"North Korea","Northern state under three generations of Kim family rule, nuclear-armed since 2006.",["North Korea","DPRK"])
E("korean-war","Korean War","event",1950,1953,False,"Korea","War begun by the North's invasion, drawing in UN and Chinese forces; an armistice, not a peace, ended fighting.",[])
E("kim-il-sung-rule","Rule of Kim Il-sung","reign",1948,1994,False,"North Korea","Founding leader who built the juche system and a hereditary personality cult.",[])
E("kim-jong-il-rule","Rule of Kim Jong-il","reign",1994,2011,False,"North Korea","Ruled through the 1990s famine and the first nuclear test, under 'military first' policy.",[])
E("kim-jong-un-rule","Rule of Kim Jong-un","reign",2011,None,True,"North Korea","Third-generation leader who expanded the nuclear and missile programmes and met US and South Korean leaders.",[])
E("north-korean-famine","North Korean Famine","event",1994,1998,False,"North Korea","Famine after Soviet aid ended that killed hundreds of thousands.",["Arduous March"])
E("rhee-syngman-rule","Presidency of Syngman Rhee","reign",1948,1960,False,"South Korea","Authoritarian founding president, ousted by the April Revolution.",[])
E("park-chung-hee-rule","Rule of Park Chung-hee","reign",1961,1979,False,"South Korea","Military strongman who drove export-led industrialisation under the repressive Yushin system; assassinated in 1979.",[])
E("gwangju-uprising","Gwangju Uprising","event",1980,1980,False,"South Korea","Pro-democracy revolt crushed by paratroopers under Chun Doo-hwan with hundreds killed.",[])
E("korean-june-struggle","June Democratic Struggle","event",1987,1987,False,"South Korea","Mass protests that forced direct presidential elections and the end of military rule.",[])
E("miracle-on-the-han","Miracle on the Han River","era",1961,1997,False,"South Korea","Transformation from postwar poverty to an advanced industrial economy led by chaebol conglomerates.",[])
E("asian-financial-crisis","Asian Financial Crisis","event",1997,1998,False,"East and Southeast Asia","Currency and banking collapse from Thailand to Korea and Indonesia, with IMF programmes and political upheaval.",[])
