# -*- coding: utf-8 -*-
"""Part 2: polities, dynasties, prime ministers, wars, constitutional events, social eras."""

def add(ENTRIES, E):
    UK = "United Kingdom"
    GB = "Kingdom of Great Britain"
    EN = "Kingdom of England"
    SC = "Kingdom of Scotland"
    BI = "Britain and Ireland"

    # ---------------- POLITIES ----------------
    E("roman-britain", "Roman Britain", "polity", 43, 410, "Roman Empire",
      "The Roman province of Britannia, from the Claudian invasion of AD 43 to the effective end of imperial administration around 410.",
      ["Britannia", "Roman province of Britannia"], dm="calendar")
    E("britannia-inferior-superior", "Division of Britannia into provinces", "event", 197, 197, "Roman Britain",
      "Severus divided Britain into Britannia Superior and Inferior; Diocletian later subdivided it further into a diocese of four or five provinces.",
      ["Britannia Superior", "Britannia Inferior"], dm="received", conf="medium")
    E("sub-roman-britain", "Sub-Roman Britain", "period", 410, 597, BI,
      "The period between the end of Roman rule and the Augustinian mission, marked by British kingdoms, Saxon settlement and very thin sources. Dating is conventional rather than exact.",
      ["post-Roman Britain", "Brittonic period"], dm="received", conf="medium")
    E("anglo-saxon-england", "Anglo-Saxon England", "period", 450, 1066, BI,
      "The era of Germanic-speaking kingdoms in lowland Britain, from the traditional adventus Saxonum to the Norman Conquest. The start date is received tradition, not a fixed event.",
      ["Early medieval England", "Saxon England"], dm="received")
    E("heptarchy", "The Heptarchy", "polity", 500, 850, "Anglo-Saxon England",
      "Conventional label for the seven principal Anglo-Saxon kingdoms of Wessex, Mercia, Northumbria, Kent, East Anglia, Essex and Sussex. The scheme is a later historiographical construct.",
      ["Seven kingdoms", "Anglo-Saxon heptarchy"], dm="received", conf="medium")
    E("kingdom-of-wessex", "Kingdom of Wessex", "polity", 519, 927, "Anglo-Saxon England",
      "Kingdom of the West Saxons, founded according to tradition by Cerdic and Cynric, which under Alfred and his heirs became the nucleus of England. Foundation date is received tradition.",
      ["West Saxons", "Wessex"], dm="received")
    E("kingdom-of-mercia", "Kingdom of Mercia", "polity", 527, 918, "Anglo-Saxon England",
      "Midland kingdom dominant in the eighth century under Aethelbald and Offa, absorbed into the English realm after 918. Foundation date is first-attestation rather than calendar.",
      ["Mercians", "Mierce"], dm="first-attestation", conf="medium")
    E("kingdom-of-northumbria", "Kingdom of Northumbria", "polity", 604, 954, "Anglo-Saxon England",
      "Northern kingdom formed by the union of Bernicia and Deira, a centre of Insular learning, later a Viking kingdom of York. Dates are received from chronicle tradition.",
      ["Northumbria", "Norhymbre"], dm="received")
    E("kingdom-of-bernicia", "Kingdom of Bernicia", "polity", 547, 654, "Kingdom of Northumbria",
      "Northern Anglian kingdom between the Tees and the Forth, later joined with Deira to form Northumbria. Dates are received tradition.",
      ["Bernicia", "Bryneich"], dm="received", conf="medium")
    E("kingdom-of-deira", "Kingdom of Deira", "polity", 559, 664, "Kingdom of Northumbria",
      "Anglian kingdom in what became Yorkshire, absorbed into Northumbria in the seventh century. Dates are received tradition.",
      ["Deira", "Deur"], dm="received", conf="medium")
    E("kingdom-of-kent", "Kingdom of Kent", "polity", 455, 871, "Anglo-Saxon England",
      "Earliest recorded Anglo-Saxon kingdom, traditionally founded by Hengist, first to be converted by Augustine's mission in 597. Foundation date is received tradition.",
      ["Kent", "Cantware"], dm="received")
    E("kingdom-of-east-anglia", "Kingdom of East Anglia", "polity", 571, 918, "Anglo-Saxon England",
      "Kingdom of the North and South Folk, home of the Sutton Hoo burial and the Wuffing dynasty, later part of the Danelaw. Dates are first-attestation approximations.",
      ["East Angles", "East Anglia"], dm="first-attestation", conf="medium")
    E("kingdom-of-essex", "Kingdom of Essex", "polity", 527, 825, "Anglo-Saxon England",
      "Kingdom of the East Saxons, including London for a time, absorbed by Wessex in 825. Dates are received tradition.",
      ["East Saxons", "Essex"], dm="received", conf="medium")
    E("kingdom-of-sussex", "Kingdom of Sussex", "polity", 477, 827, "Anglo-Saxon England",
      "Kingdom of the South Saxons, traditionally founded by AElle, annexed by Wessex in the ninth century. Foundation date is received tradition.",
      ["South Saxons", "Sussex"], dm="received", conf="medium")
    E("danelaw", "The Danelaw", "polity", 878, 954, "Anglo-Saxon England",
      "The area of eastern and northern England under Danish law and settlement after the Treaty of Alfred and Guthrum, gradually reconquered by the West Saxon kings.",
      ["Danelagh", "Scandinavian England"], dm="received")
    E("kingdom-of-york", "Kingdom of York (Jorvik)", "polity", 866, 954, "The Danelaw",
      "Norse kingdom centred on York, ruled by Viking kings until Eric Bloodaxe's expulsion and death in 954. Dates are received from chronicles.",
      ["Jorvik", "Norse kingdom of York"], dm="received", conf="medium")
    E("kingdom-of-england", "Kingdom of England", "polity", 927, 1707, BI,
      "The English kingdom from AEthelstan's unification of the Anglo-Saxon realms to its merger with Scotland in the Kingdom of Great Britain in 1707.",
      ["England", "Angelcynn", "Regnum Anglorum"], dm="received")
    E("kingdom-of-scotland", "Kingdom of Scotland", "polity", 843, 1707, BI,
      "The Scottish kingdom, from the traditional union of Picts and Gaels under Kenneth MacAlpin to the Union of 1707. The foundation date is received tradition.",
      ["Scotland", "Kingdom of Alba", "Alba"], dm="received")
    E("pictland", "Pictland", "polity", 300, 900, BI,
      "The kingdoms of the Picts north of the Forth, absorbed into the Gaelic-speaking kingdom of Alba during the ninth century. Dates are approximate and received.",
      ["Picts", "Fortriu", "Pictish kingdom"], dm="received", conf="medium")
    E("dal-riata", "Dal Riata", "polity", 500, 839, BI,
      "Gaelic kingdom of Argyll and northern Ireland whose dynasty gave rise to the kings of Alba. Dates are received tradition.",
      ["Dalriada", "Dal Riada"], dm="received", conf="medium")
    E("kingdom-of-strathclyde", "Kingdom of Strathclyde", "polity", 500, 1030, BI,
      "Brittonic kingdom centred on Dumbarton and later Govan, absorbed into Scotland in the eleventh century. Dates are received and approximate.",
      ["Alt Clut", "Cumbria", "Strathclyde"], dm="received", conf="medium")
    E("principality-of-wales", "Principality of Wales", "polity", 1216, 1536, BI,
      "The Welsh principality of Gwynedd's rulers recognised as Princes of Wales, conquered by Edward I in 1283 and annexed to England by the Laws in Wales Acts.",
      ["Wales", "Tywysogaeth Cymru"], dm="calendar")
    E("kingdom-of-gwynedd", "Kingdom of Gwynedd", "polity", 450, 1283, BI,
      "The dominant kingdom of north Wales, whose rulers claimed the principality of Wales until Edward I's conquest. Foundation date is received tradition.",
      ["Gwynedd", "Venedotia"], dm="received", conf="medium")
    E("kingdom-of-powys", "Kingdom of Powys", "polity", 450, 1160, BI,
      "Kingdom of eastern mid-Wales, later divided into Powys Fadog and Powys Wenwynwyn. Dates are received tradition.",
      ["Powys"], dm="received", conf="medium")
    E("kingdom-of-deheubarth", "Kingdom of Deheubarth", "polity", 920, 1197, BI,
      "South-western Welsh kingdom formed from Seisyllwg and Dyfed, prominent under Hywel Dda and Rhys ap Gruffydd. Dates are received tradition.",
      ["Deheubarth", "South Wales"], dm="received", conf="medium")
    E("laws-in-wales-acts", "Laws in Wales Acts", "event", 1535, 1543, EN,
      "Tudor statutes annexing Wales to the realm of England, creating Welsh counties and parliamentary representation and making English the language of the courts.",
      ["Act of Union 1536", "Acts of Union with Wales"], dm="calendar")
    E("lordship-of-ireland", "Lordship of Ireland", "polity", 1177, 1542, BI,
      "The papal-sanctioned lordship held by the kings of England after the Angevin invasion, effective authority often confined to the Pale.",
      ["Anglo-Norman Ireland", "Dominus Hiberniae"], dm="calendar")
    E("kingdom-of-ireland", "Kingdom of Ireland", "polity", 1542, 1801, BI,
      "Created by the Crown of Ireland Act of 1542, a client kingdom under the English and then British crown until the Union of 1801.",
      ["Ireland", "Rioghacht Eireann"], dm="calendar")
    E("gaelic-ireland", "Gaelic Ireland", "polity", 400, 1607, BI,
      "The network of Irish kingdoms and lordships under Gaelic law, ending with the Nine Years War and the Flight of the Earls. Dates are approximate and received.",
      ["Gaelic Irish kingdoms", "High Kingship of Ireland"], dm="received", conf="medium")
    E("commonwealth-of-england", "Commonwealth of England", "polity", 1649, 1660, BI,
      "The republic established after the execution of Charles I, governing England, and after conquest Scotland and Ireland, until the Restoration.",
      ["English Republic", "Commonwealth of England, Scotland and Ireland"], dm="calendar")
    E("the-protectorate", "The Protectorate", "polity", 1653, 1659, "Commonwealth of England",
      "Constitutional regime under the Instrument of Government in which Oliver and then Richard Cromwell governed as Lord Protector.",
      ["Cromwellian Protectorate"], dm="calendar")
    E("kingdom-of-great-britain", "Kingdom of Great Britain", "polity", 1707, 1801, BI,
      "State created by the Acts of Union of 1707 uniting England and Scotland under one parliament at Westminster, until the union with Ireland in 1801.",
      ["Great Britain", "Britain"], dm="calendar")
    E("uk-gb-ireland", "United Kingdom of Great Britain and Ireland", "polity", 1801, 1922, BI,
      "State created by the Acts of Union of 1800 and lasting until the secession of the Irish Free State in 1922.",
      ["United Kingdom 1801", "UK of Great Britain and Ireland"], dm="calendar")
    E("united-kingdom", "United Kingdom of Great Britain and Northern Ireland", "polity", 1922, None, BI,
      "The present United Kingdom, comprising England, Scotland, Wales and Northern Ireland, dating in its current form from the Irish Free State's separation in 1922.",
      ["United Kingdom", "UK", "Britain"], dm="calendar", extant=True)
    E("british-empire", "British Empire", "polity", 1583, 1997, UK,
      "The worldwide network of English and then British colonies, dominions and dependencies, conventionally dated from Elizabethan claims to the handover of Hong Kong in 1997.",
      ["the Empire", "British colonial empire"], dm="calendar")
    E("first-british-empire", "First British Empire", "period", 1583, 1783, "British Empire",
      "The Atlantic-focused empire of American colonies, Caribbean sugar islands and the slave trade, ending with American independence.",
      ["Atlantic empire"], dm="calendar", conf="medium")
    E("second-british-empire", "Second British Empire", "period", 1783, 1945, "British Empire",
      "The eastward-facing empire centred on India, Africa and the settler dominions, at its greatest extent after the First World War.",
      ["Victorian empire"], dm="calendar", conf="medium")
    E("northern-ireland", "Northern Ireland", "polity", 1921, None, UK,
      "Constituted in 1921 from six Ulster counties under the Government of Ireland Act, remaining part of the United Kingdom after partition.",
      ["Ulster", "Six Counties"], dm="calendar", extant=True)
    E("irish-free-state", "Irish Free State", "polity", 1922, 1937, BI,
      "Dominion established by the Anglo-Irish Treaty, covering twenty-six counties, replaced by the constitution of Ireland in 1937.",
      ["Saorstat Eireann"], dm="calendar")
    E("republic-of-ireland", "Republic of Ireland", "polity", 1937, None, BI,
      "The sovereign Irish state under the 1937 constitution, formally declared a republic and outside the Commonwealth in 1949.",
      ["Ireland", "Eire"], dm="calendar", extant=True)
    E("isle-of-man-lordship", "Lordship and Crown Dependency of the Isle of Man", "polity", 1266, None, BI,
      "Norse-Gaelic kingdom ceded to Scotland in 1266, later an English lordship and today a Crown Dependency with its own ancient parliament.",
      ["Isle of Man", "Mann", "Ellan Vannin"], dm="calendar", extant=True, conf="medium")
    E("lordship-of-the-isles", "Lordship of the Isles", "polity", 1336, 1493, SC,
      "MacDonald lordship dominating the Hebrides and west coast, forfeited to James IV in 1493.",
      ["Clan Donald lordship"], dm="calendar", conf="medium")
    E("channel-islands", "Channel Islands (Bailiwicks of Jersey and Guernsey)", "polity", 1204, None, BI,
      "Remnants of the Duchy of Normandy that stayed loyal to the English crown in 1204 and remain self-governing Crown Dependencies.",
      ["Jersey", "Guernsey", "Bailiwicks"], dm="calendar", extant=True, conf="medium")

    # ---------------- DYNASTIES ----------------
    for slug, name, s, e, parent, summ, al, conf, dm in [
        ("house-of-wessex", "House of Wessex", 519, 1066, EN, "The Cerdicing dynasty of West Saxon kings who became kings of the English, ending with Edward the Confessor and Edgar the AEtheling. Foundation date is received tradition.", ["Cerdicings", "House of Cerdic"], "high", "received"),
        ("house-of-denmark-england", "House of Denmark (Knytlinga) in England", 1013, 1042, EN, "The Danish kings Sweyn, Cnut, Harold Harefoot and Harthacnut who ruled England as part of a North Sea empire. Dates received from chronicles.", ["Knytlinga", "Danish kings of England"], "medium", "received"),
        ("house-of-normandy", "House of Normandy", 1066, 1154, EN, "The Norman dynasty of William I, William II, Henry I and Stephen of Blois that transformed English land tenure, law and architecture.", ["Norman dynasty", "Normans"], "high", "calendar"),
        ("house-of-plantagenet", "House of Plantagenet", 1154, 1485, EN, "The Angevin and Plantagenet kings from Henry II to Richard III, under whom Parliament, common law and the Hundred Years War took shape.", ["Angevins", "Plantagenets"], "high", "calendar"),
        ("house-of-lancaster", "House of Lancaster", 1399, 1471, EN, "The cadet Plantagenet line of Henry IV, Henry V and Henry VI, symbolised by the red rose.", ["Lancastrians", "Red Rose"], "high", "calendar"),
        ("house-of-york", "House of York", 1461, 1485, EN, "The rival Plantagenet line of Edward IV, Edward V and Richard III, symbolised by the white rose.", ["Yorkists", "White Rose"], "high", "calendar"),
        ("house-of-tudor", "House of Tudor", 1485, 1603, EN, "The Welsh-descended dynasty of Henry VII to Elizabeth I, spanning the English Reformation and the growth of the Tudor state.", ["Tudors"], "high", "calendar"),
        ("house-of-stuart", "House of Stuart", 1371, 1714, BI, "Dynasty of Scottish kings from Robert II which acquired England in 1603 and ended with Queen Anne; interrupted by the Interregnum and the Revolution.", ["Stewarts", "Stuarts", "House of Stewart"], "high", "calendar"),
        ("house-of-hanover", "House of Hanover", 1714, 1901, UK, "The German-descended dynasty of the four Georges, William IV and Victoria, under which cabinet government and the empire matured.", ["Hanoverians", "Guelphs"], "high", "calendar"),
        ("house-of-saxe-coburg-gotha", "House of Saxe-Coburg-Gotha", 1901, 1917, UK, "The dynastic name inherited from Prince Albert, borne by Edward VII and briefly George V until it was changed in 1917.", ["Saxe-Coburg and Gotha", "Wettin"], "high", "calendar"),
        ("house-of-windsor", "House of Windsor", 1917, None, UK, "The reigning royal house, renamed from Saxe-Coburg-Gotha by George V in July 1917 amid wartime anti-German feeling.", ["Windsors", "Mountbatten-Windsor"], "high", "calendar"),
        ("house-of-blois", "House of Blois", 1135, 1154, EN, "The single-reign dynasty of King Stephen, whose disputed rule produced the Anarchy.", ["Stephen of Blois dynasty"], "medium", "calendar"),
        ("house-of-dunkeld", "House of Dunkeld", 1058, 1290, SC, "The Scottish royal line descended from Malcolm III and Duncan I that presided over the feudalisation of Scotland.", ["Canmore dynasty", "MacMalcolm"], "medium", "calendar"),
        ("house-of-alpin", "House of Alpin", 843, 1034, SC, "The Alpinid kings of Alba descended from Kenneth MacAlpin, ruling by alternating succession between two branches. Dates received from king-lists.", ["Alpinids", "MacAlpin dynasty"], "medium", "received"),
        ("house-of-balliol", "House of Balliol", 1292, 1356, SC, "The rival royal line of John and Edward Balliol, sustained by English support against the Bruces.", ["Balliols"], "medium", "calendar"),
        ("house-of-bruce", "House of Bruce", 1306, 1371, SC, "The dynasty of Robert I and David II which secured Scottish independence.", ["Bruces", "de Brus"], "high", "calendar"),
        ("house-of-orange-nassau-britain", "House of Orange-Nassau in Britain", 1689, 1702, EN, "The reign of William III, the only Dutch monarch of the British kingdoms, ruling first jointly with Mary II.", ["Orange", "Williamite"], "medium", "calendar"),
        ("jacobite-succession", "Jacobite line of succession", 1688, 1807, BI, "The exiled Stuart claimants James II, James Francis Edward, Charles Edward and Henry Benedict, whose cause ended with the cardinal duke's death.", ["Jacobites", "the Old Pretender", "the Young Pretender"], "medium", "calendar"),
    ]:
        E(slug, name, "polity", s, e, parent, summ, al, conf=conf, dm=dm, extant=(e is None))

    # ---------------- PRIME MINISTERS ----------------
    PMS = [
        ("robert-walpole", "Robert Walpole", 1721, 1742, "Regarded as the first prime minister, Whig dominator of politics for two decades who kept Britain out of war until Jenkins' Ear.", ["Sir Robert Walpole", "Earl of Orford"]),
        ("earl-of-wilmington", "Spencer Compton, Earl of Wilmington", 1742, 1743, "Nominal head of the ministry that succeeded Walpole, with real power held by Carteret and the Pelhams.", ["Spencer Compton", "Lord Wilmington"]),
        ("henry-pelham", "Henry Pelham", 1743, 1754, "Whig premier who ended the War of the Austrian Succession, reduced the debt and presided over the Broad Bottom ministry.", ["Pelham"]),
        ("duke-of-newcastle-1", "Thomas Pelham-Holles, Duke of Newcastle (first ministry)", 1754, 1756, "Succeeded his brother Henry Pelham but proved unable to manage the opening disasters of the Seven Years War.", ["Duke of Newcastle", "Newcastle"]),
        ("duke-of-devonshire", "William Cavendish, Duke of Devonshire", 1756, 1757, "Caretaker premier of the Pitt-Devonshire ministry during the crisis after the loss of Minorca.", ["Duke of Devonshire"]),
        ("duke-of-newcastle-2", "Duke of Newcastle (second ministry)", 1757, 1762, "Partnership with Pitt the Elder that produced the victories of the annus mirabilis of 1759.", ["Newcastle-Pitt ministry"]),
        ("earl-of-bute", "John Stuart, Earl of Bute", 1762, 1763, "Favourite of George III who concluded the Peace of Paris and resigned amid intense unpopularity.", ["Lord Bute"]),
        ("george-grenville", "George Grenville", 1763, 1765, "Premier responsible for the Stamp Act and the prosecution of John Wilkes.", ["Grenville"]),
        ("marquess-of-rockingham-1", "Charles Watson-Wentworth, Marquess of Rockingham (first ministry)", 1765, 1766, "Whig ministry that repealed the Stamp Act while passing the Declaratory Act.", ["Rockingham"]),
        ("earl-of-chatham", "William Pitt the Elder, Earl of Chatham", 1766, 1768, "Architect of victory in the Seven Years War who as premier was incapacitated by illness.", ["Pitt the Elder", "Chatham"]),
        ("duke-of-grafton", "Augustus FitzRoy, Duke of Grafton", 1768, 1770, "Led a divided ministry through the Wilkes affair and rising American discontent.", ["Grafton"]),
        ("lord-north", "Frederick North, Lord North", 1770, 1782, "Premier throughout the American War of Independence, resigning after Yorktown.", ["North", "Earl of Guilford"]),
        ("marquess-of-rockingham-2", "Marquess of Rockingham (second ministry)", 1782, 1782, "Short second ministry that opened peace negotiations with America and passed Irish legislative independence; ended with his death.", ["Rockingham second ministry"]),
        ("earl-of-shelburne", "William Petty, Earl of Shelburne", 1782, 1783, "Concluded the Peace of Paris recognising American independence.", ["Shelburne", "Marquess of Lansdowne"]),
        ("duke-of-portland-1", "William Cavendish-Bentinck, Duke of Portland (first ministry)", 1783, 1783, "Figurehead of the Fox-North coalition, dismissed by George III over the India Bill.", ["Portland", "Fox-North coalition"]),
        ("william-pitt-younger-1", "William Pitt the Younger (first ministry)", 1783, 1801, "Youngest prime minister at 24, reformer of finance and administration who led Britain into the French revolutionary wars; resigned over Catholic emancipation.", ["Pitt the Younger", "Pitt"]),
        ("henry-addington", "Henry Addington", 1801, 1804, "Negotiated the Peace of Amiens and resumed war before making way for Pitt's return.", ["Viscount Sidmouth", "Addington"]),
        ("william-pitt-younger-2", "William Pitt the Younger (second ministry)", 1804, 1806, "Formed the Third Coalition against Napoleon and died in office weeks after Austerlitz.", ["Pitt second ministry"]),
        ("lord-grenville", "William Grenville, Lord Grenville", 1806, 1807, "Head of the Ministry of All the Talents, which abolished the British slave trade in 1807.", ["Grenville", "Ministry of All the Talents"]),
        ("duke-of-portland-2", "Duke of Portland (second ministry)", 1807, 1809, "Presided over the Peninsular War's opening and the Walcheren fiasco before ill health forced resignation.", ["Portland second ministry"]),
        ("spencer-perceval", "Spencer Perceval", 1809, 1812, "The only British prime minister to be assassinated, shot in the lobby of the House of Commons in May 1812.", ["Perceval"]),
        ("earl-of-liverpool", "Robert Jenkinson, Earl of Liverpool", 1812, 1827, "Long-serving Tory premier through the defeat of Napoleon, Peterloo, repressive legislation and later liberal reform.", ["Liverpool"]),
        ("george-canning", "George Canning", 1827, 1827, "Shortest-serving prime minister, dying after 119 days in office.", ["Canning"]),
        ("viscount-goderich", "Frederick Robinson, Viscount Goderich", 1827, 1828, "Unable to hold his coalition together and resigned without facing Parliament.", ["Goderich", "Earl of Ripon"]),
        ("duke-of-wellington-1", "Arthur Wellesley, Duke of Wellington (first ministry)", 1828, 1830, "Victor of Waterloo who as premier reluctantly carried Catholic emancipation and opposed parliamentary reform.", ["Wellington", "the Iron Duke"]),
        ("earl-grey", "Charles Grey, Earl Grey", 1830, 1834, "Whig premier who carried the Great Reform Act of 1832 and the abolition of slavery in the empire.", ["Grey", "Lord Grey"]),
        ("viscount-melbourne-1", "William Lamb, Viscount Melbourne (first ministry)", 1834, 1834, "Brief first ministry dismissed by William IV, the last time a monarch removed a premier commanding Commons support.", ["Melbourne"]),
        ("duke-of-wellington-caretaker", "Duke of Wellington (caretaker ministry)", 1834, 1834, "Held office for about three weeks in November and December 1834 while Peel returned from Italy.", ["Wellington caretaker"]),
        ("robert-peel-1", "Robert Peel (first ministry)", 1834, 1835, "Minority ministry that issued the Tamworth Manifesto and fell after the 1835 election.", ["Peel", "Sir Robert Peel"]),
        ("viscount-melbourne-2", "Viscount Melbourne (second ministry)", 1835, 1841, "Mentor to the young Queen Victoria, presiding over Chartist agitation and the new Poor Law.", ["Melbourne second ministry"]),
        ("robert-peel-2", "Robert Peel (second ministry)", 1841, 1846, "Reformed tariffs and income tax, founded the modern police tradition and split his party by repealing the Corn Laws.", ["Peel second ministry"]),
        ("lord-john-russell-1", "Lord John Russell (first ministry)", 1846, 1852, "Whig premier during the Great Irish Famine and the Public Health Act.", ["John Russell", "Earl Russell"]),
        ("earl-of-derby-1", "Edward Smith-Stanley, Earl of Derby (first ministry)", 1852, 1852, "Minority Conservative ministry known as the Who? Who? ministry.", ["Derby", "Lord Stanley"]),
        ("earl-of-aberdeen", "George Hamilton-Gordon, Earl of Aberdeen", 1852, 1855, "Peelite-Whig coalition premier who took Britain into the Crimean War and fell over its mismanagement.", ["Aberdeen"]),
        ("viscount-palmerston-1", "Henry Temple, Viscount Palmerston (first ministry)", 1855, 1858, "Brought the Crimean War to a close and suppressed the Indian Rebellion, ending Company rule.", ["Palmerston"]),
        ("earl-of-derby-2", "Earl of Derby (second ministry)", 1858, 1859, "Minority ministry that transferred Indian government to the Crown and admitted Jews to Parliament.", ["Derby second ministry"]),
        ("viscount-palmerston-2", "Viscount Palmerston (second ministry)", 1859, 1865, "Steered neutrality in the American Civil War and died in office aged 81.", ["Palmerston second ministry"]),
        ("lord-john-russell-2", "Earl Russell (second ministry)", 1865, 1866, "Attempted a new reform bill and resigned when it was defeated.", ["Russell second ministry"]),
        ("earl-of-derby-3", "Earl of Derby (third ministry)", 1866, 1868, "Ministry that passed the Second Reform Act of 1867 nearly doubling the electorate.", ["Derby third ministry"]),
        ("benjamin-disraeli-1", "Benjamin Disraeli (first ministry)", 1868, 1868, "Succeeded Derby and lost the general election within months.", ["Disraeli", "Earl of Beaconsfield"]),
        ("william-gladstone-1", "William Ewart Gladstone (first ministry)", 1868, 1874, "Great reforming Liberal ministry: Irish disestablishment, the Education Act, the secret ballot and army and civil service reform.", ["Gladstone", "the Grand Old Man"]),
        ("benjamin-disraeli-2", "Benjamin Disraeli (second ministry)", 1874, 1880, "Imperialist and social-reform ministry that bought Suez Canal shares and made Victoria Empress of India.", ["Disraeli second ministry"]),
        ("william-gladstone-2", "William Gladstone (second ministry)", 1880, 1885, "Third Reform Act, Egyptian occupation and the death of Gordon at Khartoum.", ["Gladstone second ministry"]),
        ("marquess-of-salisbury-1", "Robert Gascoyne-Cecil, Marquess of Salisbury (first ministry)", 1885, 1886, "First of three Conservative ministries by the last premier to lead from the House of Lords.", ["Salisbury", "Lord Salisbury"]),
        ("william-gladstone-3", "William Gladstone (third ministry)", 1886, 1886, "Introduced the First Irish Home Rule Bill, splitting the Liberal Party.", ["Gladstone third ministry"]),
        ("marquess-of-salisbury-2", "Marquess of Salisbury (second ministry)", 1886, 1892, "Unionist government of free education, county councils and the scramble for Africa.", ["Salisbury second ministry"]),
        ("william-gladstone-4", "William Gladstone (fourth ministry)", 1892, 1894, "Aged premier whose Second Home Rule Bill passed the Commons but was rejected by the Lords.", ["Gladstone fourth ministry"]),
        ("earl-of-rosebery", "Archibald Primrose, Earl of Rosebery", 1894, 1895, "Liberal premier who introduced death duties and was undermined by party divisions.", ["Rosebery"]),
        ("marquess-of-salisbury-3", "Marquess of Salisbury (third ministry)", 1895, 1902, "Ministry of the Diamond Jubilee, imperial expansion and the Second Boer War.", ["Salisbury third ministry"]),
        ("arthur-balfour", "Arthur Balfour", 1902, 1905, "Nephew of Salisbury whose ministry passed the 1902 Education Act and split over tariff reform.", ["Balfour", "Earl of Balfour"]),
        ("henry-campbell-bannerman", "Henry Campbell-Bannerman", 1905, 1908, "Liberal landslide premier who granted self-government to the Transvaal and began welfare legislation.", ["Campbell-Bannerman", "CB"]),
        ("h-h-asquith", "H. H. Asquith", 1908, 1916, "Presided over the People's Budget, the Parliament Act, the constitutional crisis over Ireland and the first half of the Great War.", ["Herbert Henry Asquith", "Earl of Oxford and Asquith"]),
        ("david-lloyd-george", "David Lloyd George", 1916, 1922, "Dynamic wartime premier and peacemaker at Versailles, whose coalition ended with the Irish Treaty and the Chanak crisis.", ["Lloyd George", "the Welsh Wizard"]),
        ("andrew-bonar-law", "Andrew Bonar Law", 1922, 1923, "Canadian-born Conservative premier who resigned after seven months with terminal illness.", ["Bonar Law"]),
        ("stanley-baldwin-1", "Stanley Baldwin (first ministry)", 1923, 1924, "Called a snap election on protection and lost his majority.", ["Baldwin", "Earl Baldwin of Bewdley"]),
        ("ramsay-macdonald-1", "Ramsay MacDonald (first ministry)", 1924, 1924, "First Labour prime minister, heading a minority government for nine months.", ["MacDonald"]),
        ("stanley-baldwin-2", "Stanley Baldwin (second ministry)", 1924, 1929, "Ministry of the return to the gold standard, the General Strike of 1926 and the equal franchise of 1928.", ["Baldwin second ministry"]),
        ("ramsay-macdonald-2", "Ramsay MacDonald (second and National ministries)", 1929, 1935, "Labour premier overwhelmed by the slump who formed a National Government in 1931 and was expelled from his party.", ["National Government", "MacDonald second ministry"]),
        ("stanley-baldwin-3", "Stanley Baldwin (third ministry)", 1935, 1937, "Managed the abdication crisis and began rearmament while pursuing conciliation abroad.", ["Baldwin third ministry"]),
        ("neville-chamberlain", "Neville Chamberlain", 1937, 1940, "Architect of appeasement and the Munich Agreement who declared war in 1939 and fell after the Norway debate.", ["Chamberlain"]),
        ("winston-churchill-1", "Winston Churchill (wartime ministry)", 1940, 1945, "Led the wartime coalition to victory over Nazi Germany, defining British resolve in 1940.", ["Churchill", "Sir Winston Churchill"]),
        ("clement-attlee", "Clement Attlee", 1945, 1951, "Built the welfare state and the NHS, nationalised key industries and granted independence to India.", ["Attlee", "Earl Attlee"]),
        ("winston-churchill-2", "Winston Churchill (peacetime ministry)", 1951, 1955, "Returned to office aged 76, ending rationing and accepting most of the postwar settlement.", ["Churchill second ministry"]),
        ("anthony-eden", "Anthony Eden", 1955, 1957, "Premiership destroyed by the Suez Crisis of 1956.", ["Eden", "Earl of Avon"]),
        ("harold-macmillan", "Harold Macmillan", 1957, 1963, "Presided over affluence and decolonisation's wind of change, resigning amid the Profumo affair.", ["Macmillan", "Supermac"]),
        ("alec-douglas-home", "Alec Douglas-Home", 1963, 1964, "Renounced his peerage to lead the Conservatives and narrowly lost the 1964 election.", ["Douglas-Home", "Lord Home"]),
        ("harold-wilson-1", "Harold Wilson (first ministries)", 1964, 1970, "Labour premier of devaluation, comprehensive education, Open University and the permissive social reforms of the 1960s.", ["Wilson", "Lord Wilson of Rievaulx"]),
        ("edward-heath", "Edward Heath", 1970, 1974, "Took Britain into the European Communities in 1973 and fell during the miners' strike and three-day week.", ["Heath", "Ted Heath"]),
        ("harold-wilson-2", "Harold Wilson (second ministries)", 1974, 1976, "Returned in 1974, held the 1975 referendum confirming EC membership and resigned unexpectedly in 1976.", ["Wilson second ministry"]),
        ("james-callaghan", "James Callaghan", 1976, 1979, "Faced the IMF crisis and the Winter of Discontent, losing a confidence vote in 1979.", ["Callaghan", "Sunny Jim"]),
        ("margaret-thatcher", "Margaret Thatcher", 1979, 1990, "First woman prime minister, who privatised industries, curbed the unions, won the Falklands War and reshaped British political economy.", ["Thatcher", "the Iron Lady"]),
        ("john-major", "John Major", 1990, 1997, "Signed the Maastricht Treaty, endured Black Wednesday and began the Northern Ireland peace process.", ["Major"]),
        ("tony-blair", "Tony Blair", 1997, 2007, "New Labour premier of devolution, the Good Friday Agreement, public spending growth and the Iraq War.", ["Blair"]),
        ("gordon-brown", "Gordon Brown", 2007, 2010, "Former chancellor whose premiership was dominated by the global financial crisis.", ["Brown"]),
        ("david-cameron", "David Cameron", 2010, 2016, "Led coalition and then Conservative governments of austerity, the Scottish referendum and the Brexit referendum, resigning after the Leave vote.", ["Cameron"]),
        ("theresa-may", "Theresa May", 2016, 2019, "Sought to deliver Brexit but could not pass her withdrawal agreement through Parliament.", ["May"]),
        ("boris-johnson", "Boris Johnson", 2019, 2022, "Won a large majority on getting Brexit done, led the Covid-19 response and resigned amid successive scandals.", ["Johnson", "Boris"]),
        ("liz-truss", "Liz Truss", 2022, 2022, "Shortest-serving prime minister, resigning after 49 days following the market reaction to her mini-budget.", ["Truss"]),
        ("rishi-sunak", "Rishi Sunak", 2022, 2024, "First British Asian prime minister, governing amid inflation and losing the 2024 general election.", ["Sunak"]),
        ("keir-starmer", "Keir Starmer", 2024, None, "Labour leader who won a landslide in July 2024 and is the incumbent prime minister.", ["Starmer", "Sir Keir Starmer"]),
    ]
    for slug, name, s, e, summ, al in PMS:
        parent = GB if e and e <= 1801 else UK
        E(slug, name, "reign", s, e, parent, summ, al, dm="calendar", extant=(e is None))

    # ---------------- WARS AND CONFLICTS ----------------
    WARS = [
        ("roman-conquest-of-britain", "Roman conquest of Britain", 43, 84, "Roman Britain", "Campaigns from Aulus Plautius' landing in AD 43 to Agricola's victory at Mons Graupius, bringing most of Britain under Rome.", ["Claudian invasion"], "calendar", "event"),
        ("boudican-revolt", "Boudican revolt", 60, 61, "Roman Britain", "Iceni rising led by Boudica that destroyed Camulodunum, Londinium and Verulamium before defeat at Watling Street.", ["Boudicca's rebellion"], "calendar", "event"),
        ("viking-invasions-of-britain", "Viking invasions of Britain", 793, 1066, "Anglo-Saxon England", "Two and a half centuries of Scandinavian raiding, settlement and conquest, from Lindisfarne to Stamford Bridge. Start date received from the Anglo-Saxon Chronicle.", ["Norse invasions", "Great Heathen Army"], "received", "event"),
        ("norman-conquest", "Norman Conquest", 1066, 1071, EN, "William of Normandy's invasion, victory at Hastings and subsequent subjugation of England, including the Harrying of the North.", ["Conquest of 1066", "Battle of Hastings"], "calendar", "event"),
        ("the-anarchy", "The Anarchy", 1138, 1153, EN, "Civil war between Stephen and Empress Matilda over the succession to Henry I, ended by the Treaty of Wallingford.", ["Stephen and Matilda civil war"], "calendar", "event"),
        ("first-barons-war", "First Barons' War", 1215, 1217, EN, "Rebellion against King John after Magna Carta, involving a French invasion, ended by the reissue of the charter under Henry III.", ["Barons' War 1215"], "calendar", "event"),
        ("second-barons-war", "Second Barons' War", 1264, 1267, EN, "Rising led by Simon de Montfort against Henry III, producing the parliament of 1265 before defeat at Evesham.", ["de Montfort's rebellion"], "calendar", "event"),
        ("edwardian-conquest-of-wales", "Edwardian conquest of Wales", 1277, 1283, EN, "Edward I's campaigns ending Welsh independence with the death of Llywelyn ap Gruffudd and a great programme of castle building.", ["Conquest of Wales"], "calendar", "event"),
        ("first-war-of-scottish-independence", "First War of Scottish Independence", 1296, 1328, SC, "War from Edward I's invasion through Wallace, Bruce and Bannockburn to the Treaty of Edinburgh-Northampton.", ["Wars of Scottish Independence", "Bannockburn"], "calendar", "event"),
        ("second-war-of-scottish-independence", "Second War of Scottish Independence", 1332, 1357, SC, "Renewed conflict over the Balliol claim, including Neville's Cross and the captivity of David II.", ["Scottish independence war two"], "calendar", "event"),
        ("hundred-years-war", "Hundred Years' War", 1337, 1453, EN, "Dynastic struggle between England and France over the French crown and Gascony, including Crecy, Poitiers, Agincourt and eventual English expulsion.", ["Anglo-French war 1337-1453"], "calendar", "event"),
        ("glyndwr-rising", "Glyndwr Rising", 1400, 1415, "Principality of Wales", "Owain Glyndwr's national revolt against English rule, briefly establishing a Welsh parliament at Machynlleth.", ["Owain Glyndwr's revolt"], "calendar", "event"),
        ("wars-of-the-roses", "Wars of the Roses", 1455, 1487, EN, "Dynastic wars between Lancaster and York from St Albans to Stoke Field, ending with Tudor rule.", ["Roses wars", "Lancaster versus York"], "calendar", "event"),
        ("anglo-spanish-war-1585", "Anglo-Spanish War", 1585, 1604, EN, "Undeclared war with Philip II including the Armada of 1588 and Drake's raids, settled by the Treaty of London.", ["Spanish Armada"], "calendar", "event"),
        ("nine-years-war-ireland", "Nine Years' War in Ireland", 1594, 1603, "Kingdom of Ireland", "Rebellion of Hugh O'Neill against Tudor rule, ending at Kinsale and Mellifont and opening the way to the Ulster plantation.", ["Tyrone's Rebellion"], "calendar", "event"),
        ("bishops-wars", "Bishops' Wars", 1639, 1640, SC, "Scottish Covenanter resistance to Charles I's prayer book, whose cost forced him to recall Parliament.", ["Scottish Covenanter wars"], "calendar", "event"),
        ("first-english-civil-war", "First English Civil War", 1642, 1646, EN, "War between King and Parliament from Edgehill to Naseby and the surrender of Oxford.", ["Civil War 1642"], "calendar", "event"),
        ("second-english-civil-war", "Second English Civil War", 1648, 1648, EN, "Royalist and Scottish risings crushed at Preston, leading directly to the king's trial.", ["Civil War 1648"], "calendar", "event"),
        ("third-english-civil-war", "Third English Civil War", 1649, 1651, EN, "Campaigns in Ireland and Scotland ending with Cromwell's victory at Worcester and Charles II's flight.", ["Worcester campaign"], "calendar", "event"),
        ("wars-of-three-kingdoms", "Wars of the Three Kingdoms", 1639, 1653, BI, "The interlocking conflicts in England, Scotland and Ireland including the Civil Wars, Covenanter risings and the Cromwellian conquest of Ireland.", ["British Civil Wars", "English Civil Wars"], "calendar", "event"),
        ("cromwellian-conquest-of-ireland", "Cromwellian conquest of Ireland", 1649, 1653, "Kingdom of Ireland", "Parliamentarian reconquest marked by the sieges of Drogheda and Wexford and massive land confiscation.", ["Cromwell in Ireland"], "calendar", "event"),
        ("williamite-war-in-ireland", "Williamite War in Ireland", 1689, 1691, "Kingdom of Ireland", "War between Jacobite and Williamite forces including the Siege of Derry, the Boyne and Aughrim, ending with the Treaty of Limerick.", ["Battle of the Boyne", "Jacobite war in Ireland"], "calendar", "event"),
        ("war-of-spanish-succession", "War of the Spanish Succession", 1701, 1714, GB, "European war in which Marlborough won Blenheim and Ramillies, ending with the Treaty of Utrecht and the acquisition of Gibraltar.", ["Marlborough's wars"], "calendar", "event"),
        ("jacobite-rising-1689", "Jacobite rising of 1689", 1689, 1692, SC, "Highland rising for James VII including the victory at Killiecrankie and the massacre of Glencoe in 1692.", ["Dundee's rising"], "calendar", "event"),
        ("jacobite-rising-1715", "Jacobite rising of 1715", 1715, 1716, GB, "The Fifteen, led by the Earl of Mar for the Old Pretender, halted at Sheriffmuir and Preston.", ["the Fifteen"], "calendar", "event"),
        ("jacobite-rising-1719", "Jacobite rising of 1719", 1719, 1719, GB, "Spanish-backed attempt defeated at Glen Shiel.", ["the Nineteen"], "calendar", "event"),
        ("jacobite-rising-1745", "Jacobite rising of 1745", 1745, 1746, GB, "The Forty-Five, in which Charles Edward Stuart advanced to Derby before annihilation at Culloden.", ["the Forty-Five", "Culloden", "Bonnie Prince Charlie's rising"], "calendar", "event"),
        ("war-of-austrian-succession-britain", "War of the Austrian Succession", 1740, 1748, GB, "British participation against France and Prussia, including George II's victory at Dettingen.", ["War of Jenkins' Ear"], "calendar", "event"),
        ("seven-years-war", "Seven Years' War", 1756, 1763, GB, "Global war in which Britain took Canada, expelled France from India and emerged as the leading colonial power.", ["French and Indian War", "the first world war"], "calendar", "event"),
        ("american-war-of-independence", "American War of Independence", 1775, 1783, "British Empire", "Loss of the thirteen American colonies after Saratoga and Yorktown, recognised at the Peace of Paris.", ["American Revolutionary War"], "calendar", "event"),
        ("irish-rebellion-1798", "Irish Rebellion of 1798", 1798, 1798, "Kingdom of Ireland", "United Irishmen rising inspired by revolutionary France, suppressed with great bloodshed and leading to the Union of 1801.", ["United Irishmen rebellion"], "calendar", "event"),
        ("french-revolutionary-wars-britain", "French Revolutionary Wars", 1793, 1802, GB, "British participation in the coalitions against revolutionary France, including naval victories at the Nile and Camperdown.", ["Revolutionary wars"], "calendar", "event"),
        ("napoleonic-wars", "Napoleonic Wars", 1803, 1815, UK, "British-led coalitions against Napoleon, including Trafalgar in 1805, the Peninsular War and final victory at Waterloo.", ["Trafalgar", "Waterloo", "wars against Napoleon"], "calendar", "event"),
        ("peninsular-war", "Peninsular War", 1808, 1814, UK, "Wellington's Iberian campaigns alongside Spanish and Portuguese forces, draining French strength.", ["Spanish war of Wellington"], "calendar", "event"),
        ("war-of-1812-britain", "War of 1812", 1812, 1815, "British Empire", "Anglo-American war fought in Canada and at sea, including the burning of Washington, settled by the Treaty of Ghent.", ["Anglo-American War"], "calendar", "event"),
        ("crimean-war", "Crimean War", 1853, 1856, UK, "Anglo-French war with Russia over the Ottoman Empire, remembered for Balaclava, Inkerman, Sevastopol and Florence Nightingale.", ["Charge of the Light Brigade"], "calendar", "event"),
        ("indian-rebellion-1857", "Indian Rebellion of 1857", 1857, 1858, "British Empire", "Great uprising against East India Company rule that led to direct Crown government of India.", ["Indian Mutiny", "Sepoy Mutiny"], "calendar", "event"),
        ("first-boer-war", "First Boer War", 1880, 1881, "British Empire", "Transvaal war of independence ending in British defeat at Majuba Hill.", ["Transvaal War"], "calendar", "event"),
        ("second-boer-war", "Second Boer War", 1899, 1902, "British Empire", "Long South African war involving sieges, guerrilla resistance, farm burning and concentration camps, ending at Vereeniging.", ["Boer War", "South African War"], "calendar", "event"),
        ("first-world-war-britain", "First World War", 1914, 1918, UK, "British and imperial participation from the invasion of Belgium to the Armistice, with some 900,000 British and imperial dead.", ["Great War", "World War I"], "calendar", "event"),
        ("easter-rising", "Easter Rising", 1916, 1916, "Kingdom of Ireland", "Republican insurrection in Dublin, suppressed within a week, whose executions transformed Irish public opinion.", ["1916 Rising"], "calendar", "event"),
        ("irish-war-of-independence", "Irish War of Independence", 1919, 1921, "Kingdom of Ireland", "Guerrilla war between the IRA and Crown forces including the Black and Tans, ended by truce and the Anglo-Irish Treaty.", ["Anglo-Irish War", "Tan War"], "calendar", "event"),
        ("irish-civil-war", "Irish Civil War", 1922, 1923, "Irish Free State", "Conflict between pro- and anti-Treaty forces over the settlement with Britain, won by the Free State government.", ["Treaty split war"], "calendar", "event"),
        ("second-world-war-britain", "Second World War", 1939, 1945, UK, "British and Commonwealth war against Germany, Italy and Japan, from Poland's invasion to VJ Day.", ["World War II", "the war"], "calendar", "event"),
        ("battle-of-britain", "Battle of Britain", 1940, 1940, UK, "Air campaign in which RAF Fighter Command defeated the Luftwaffe's bid for air superiority over southern England.", ["1940 air battle"], "calendar", "event"),
        ("dunkirk-evacuation", "Dunkirk evacuation", 1940, 1940, UK, "Operation Dynamo lifted some 338,000 Allied troops from Dunkirk in late May and early June 1940.", ["Operation Dynamo", "the little ships"], "calendar", "event"),
        ("korean-war-britain", "British involvement in the Korean War", 1950, 1953, UK, "Commonwealth Division fought under United Nations command, notably at the Imjin River.", ["Korea 1950"], "calendar", "event"),
        ("suez-crisis", "Suez Crisis", 1956, 1956, UK, "Anglo-French-Israeli operation against Nasser's Egypt, abandoned under American and international pressure, exposing Britain's diminished power.", ["Suez", "Operation Musketeer"], "calendar", "event"),
        ("malayan-emergency-britain", "Malayan Emergency", 1948, 1960, "British Empire", "Long counter-insurgency campaign against communist guerrillas in Malaya.", ["Malaya emergency"], "calendar", "event"),
        ("mau-mau-uprising", "Mau Mau Uprising", 1952, 1960, "British Empire", "Kenyan rebellion against colonial land policy, suppressed with mass detention and violence.", ["Kenya emergency"], "calendar", "event"),
        ("the-troubles", "The Troubles", 1968, 1998, "Northern Ireland", "Three decades of conflict in Northern Ireland between republicans, loyalists and the British state, ending with the Good Friday Agreement.", ["Northern Ireland conflict"], "calendar", "event"),
        ("bloody-sunday-1972", "Bloody Sunday", 1972, 1972, "Northern Ireland", "Paratroopers shot dead thirteen civil rights marchers in Derry on 30 January 1972, with a fourteenth dying later.", ["Derry Bloody Sunday"], "calendar", "event"),
        ("falklands-war", "Falklands War", 1982, 1982, UK, "Ten-week war to recover the Falkland Islands after the Argentine invasion of April 1982.", ["Falklands conflict", "Guerra de las Malvinas"], "calendar", "event"),
        ("gulf-war-britain", "Gulf War", 1990, 1991, UK, "British participation in Operation Granby, the coalition campaign to expel Iraq from Kuwait.", ["Operation Granby", "Desert Storm"], "calendar", "event"),
        ("iraq-war-britain", "Iraq War", 2003, 2011, UK, "Controversial British participation in the invasion and occupation of Iraq, later examined by the Chilcot Inquiry.", ["Operation Telic", "Chilcot"], "calendar", "event"),
        ("afghanistan-war-britain", "British involvement in the War in Afghanistan", 2001, 2014, UK, "Combat operations, chiefly in Helmand, from the invasion of 2001 to the end of the combat mission in 2014.", ["Operation Herrick", "Helmand"], "calendar", "event"),
    ]
    for slug, name, s, e, parent, summ, al, dm, kind in WARS:
        E(slug, name, kind, s, e, parent, summ, al, dm=dm)

    # ---------------- CONSTITUTIONAL AND POLITICAL EVENTS ----------------
    EVENTS = [
        ("hadrians-wall", "Building of Hadrian's Wall", 122, 128, "Roman Britain", "Frontier wall from Tyne to Solway begun under Hadrian, later Rome's northern boundary in Britain.", ["Hadrian's Wall"], "calendar"),
        ("antonine-wall", "Building of the Antonine Wall", 142, 154, "Roman Britain", "Turf frontier across the Forth-Clyde isthmus, occupied for barely a generation.", ["Antonine Wall"], "received"),
        ("end-of-roman-rule", "End of Roman rule in Britain", 410, 410, "Roman Britain", "Withdrawal of the last field armies and the traditional Rescript of Honorius telling the cities to look to their own defence. Dating is received tradition.", ["Rescript of Honorius"], "received"),
        ("augustine-mission", "Gregorian mission of Augustine", 597, 597, "Kingdom of Kent", "Augustine's arrival in Kent began the conversion of the Anglo-Saxons and the founding of the see of Canterbury. Date received from Bede.", ["conversion of the English", "Saint Augustine of Canterbury"], "received"),
        ("synod-of-whitby", "Synod of Whitby", 664, 664, "Kingdom of Northumbria", "Northumbrian council that adopted Roman rather than Irish practice for Easter and the tonsure. Date received from Bede.", ["Whitby 664"], "received"),
        ("treaty-of-alfred-and-guthrum", "Treaty of Alfred and Guthrum", 878, 890, "Kingdom of Wessex", "Agreement partitioning England between English and Danish rule along the Watling Street line. Dating is uncertain and received.", ["Wedmore", "Alfred-Guthrum treaty"], "received"),
        ("unification-of-england", "Unification of England under AEthelstan", 927, 927, EN, "AEthelstan's takeover of Northumbria created a single kingdom of the English. Date received from chronicle tradition.", ["making of England"], "received"),
        ("domesday-book", "Domesday Book", 1086, 1086, EN, "William I's great survey of landholding and resources in England, the most detailed record of its kind in medieval Europe.", ["Domesday survey"], "calendar"),
        ("magna-carta", "Magna Carta", 1215, 1215, EN, "Charter sealed by King John at Runnymede limiting royal arbitrariness and guaranteeing due process; reissued and enshrined in later law.", ["Great Charter", "Runnymede charter"], "calendar"),
        ("provisions-of-oxford", "Provisions of Oxford", 1258, 1258, EN, "Baronial reform programme imposed on Henry III establishing a council of fifteen and regular parliaments.", ["Oxford Provisions"], "calendar"),
        ("provisions-of-westminster", "Provisions of Westminster", 1259, 1259, EN, "Further baronial reforms addressing local administration and legal grievances.", ["Westminster Provisions"], "calendar"),
        ("de-montfort-parliament", "Simon de Montfort's Parliament", 1265, 1265, EN, "First English parliament to include elected burgesses from the towns as well as knights of the shire.", ["Parliament of 1265"], "calendar"),
        ("model-parliament", "Model Parliament", 1295, 1295, EN, "Edward I's assembly of lords, clergy, knights and burgesses, later seen as the pattern for Parliament.", ["Parliament of 1295"], "calendar"),
        ("declaration-of-arbroath", "Declaration of Arbroath", 1320, 1320, SC, "Letter of the Scottish barons to the pope asserting Scotland's independence and the community of the realm.", ["Arbroath letter"], "calendar"),
        ("statute-of-labourers", "Statute of Labourers", 1351, 1351, EN, "Post-plague attempt to cap wages and bind labourers, a grievance behind the Peasants' Revolt.", ["1351 labour law"], "calendar"),
        ("peasants-revolt", "Peasants' Revolt", 1381, 1381, EN, "Rising against the poll tax and serfdom led by Wat Tyler and John Ball, suppressed after the confrontation at Smithfield.", ["Great Rising", "Wat Tyler's rebellion"], "calendar"),
        ("english-reformation", "English Reformation", 1529, 1559, EN, "Break with Rome under Henry VIII, doctrinal change under Edward VI, Marian reversal and the Elizabethan settlement.", ["break with Rome", "Reformation in England"], "calendar"),
        ("act-of-supremacy-1534", "Act of Supremacy", 1534, 1534, EN, "Statute declaring Henry VIII Supreme Head on earth of the Church of England.", ["Royal Supremacy"], "calendar"),
        ("dissolution-of-the-monasteries", "Dissolution of the Monasteries", 1536, 1541, EN, "Suppression of religious houses and transfer of their vast wealth to the Crown and its supporters.", ["suppression of the monasteries"], "calendar"),
        ("pilgrimage-of-grace", "Pilgrimage of Grace", 1536, 1537, EN, "Northern rising against religious change and Cromwell's government, the greatest Tudor rebellion.", ["1536 northern rebellion"], "calendar"),
        ("book-of-common-prayer-1549", "First Book of Common Prayer", 1549, 1549, EN, "Cranmer's English liturgy, introduced by the Act of Uniformity and provoking the Western Rising.", ["Prayer Book 1549"], "calendar"),
        ("elizabethan-religious-settlement", "Elizabethan Religious Settlement", 1559, 1559, EN, "Acts of Supremacy and Uniformity establishing a Protestant church with the monarch as Supreme Governor.", ["1559 settlement"], "calendar"),
        ("scottish-reformation", "Scottish Reformation", 1560, 1560, SC, "Parliament abolished papal jurisdiction and adopted a reformed confession, founding the Kirk under Knox's influence.", ["Reformation in Scotland"], "calendar"),
        ("plantation-of-ulster", "Plantation of Ulster", 1609, 1690, "Kingdom of Ireland", "Organised settlement of English and Scottish Protestants on confiscated Ulster land, with enduring consequences.", ["Ulster Plantation"], "calendar"),
        ("union-of-the-crowns", "Union of the Crowns", 1603, 1603, BI, "James VI of Scotland's accession to the English throne joined the two crowns in one person while the kingdoms stayed separate.", ["1603 union", "Union of Crowns"], "calendar"),
        ("gunpowder-plot", "Gunpowder Plot", 1605, 1605, EN, "Catholic conspiracy to blow up the Palace of Westminster, foiled on 5 November 1605.", ["Guy Fawkes", "Fifth of November"], "calendar"),
        ("petition-of-right", "Petition of Right", 1628, 1628, EN, "Parliamentary statement against non-parliamentary taxation, arbitrary imprisonment and billeting.", ["1628 petition"], "calendar"),
        ("personal-rule", "Personal Rule of Charles I", 1629, 1640, EN, "Eleven years of government without Parliament, financed by ship money and marked by Laudian church policy.", ["Eleven Years' Tyranny"], "calendar"),
        ("long-parliament", "Long Parliament", 1640, 1660, EN, "Parliament summoned in 1640 that abolished the prerogative courts, tried Strafford and led the war against the king.", ["1640 Parliament"], "calendar"),
        ("regicide-of-charles-i", "Trial and execution of Charles I", 1649, 1649, EN, "The king was tried by a High Court of Justice and beheaded outside the Banqueting House on 30 January 1649.", ["regicide", "execution of Charles I"], "calendar"),
        ("navigation-acts", "Navigation Acts", 1651, 1849, "British Empire", "Series of laws reserving colonial trade to English and British shipping, a pillar of mercantilism until repeal.", ["mercantile system"], "calendar"),
        ("restoration-1660", "Restoration of the Monarchy", 1660, 1660, EN, "Charles II returned under the Declaration of Breda, restoring monarchy, Lords and the Church of England.", ["the Restoration"], "calendar"),
        ("great-plague-of-london", "Great Plague of London", 1665, 1666, EN, "Last major English bubonic plague epidemic, killing perhaps a quarter of London's population.", ["1665 plague"], "calendar"),
        ("great-fire-of-london", "Great Fire of London", 1666, 1666, EN, "Fire that destroyed much of the medieval City, prompting rebuilding in brick and Wren's churches.", ["1666 fire"], "calendar"),
        ("habeas-corpus-act-1679", "Habeas Corpus Act", 1679, 1679, EN, "Statute strengthening the writ against unlawful detention, a landmark of personal liberty.", ["1679 Act"], "calendar"),
        ("exclusion-crisis", "Exclusion Crisis", 1679, 1681, EN, "Attempts to bar the Catholic James from the succession, giving rise to the Whig and Tory parties.", ["Whig and Tory origins"], "calendar"),
        ("glorious-revolution", "Glorious Revolution", 1688, 1689, EN, "Deposition of James II and accession of William and Mary on parliamentary terms, establishing constitutional monarchy.", ["Revolution of 1688", "the Revolution"], "calendar"),
        ("bill-of-rights-1689", "Bill of Rights", 1689, 1689, EN, "Statute limiting royal power, requiring frequent parliaments and free elections and barring Catholics from the throne.", ["1689 Bill of Rights"], "calendar"),
        ("claim-of-right-1689", "Claim of Right", 1689, 1689, SC, "Scottish counterpart to the Bill of Rights, declaring the throne forfeited by James VII.", ["Scottish Claim of Right"], "calendar"),
        ("bank-of-england-founded", "Founding of the Bank of England", 1694, 1694, EN, "Chartered to fund the war with France, creating the basis of the national debt and modern public finance.", ["Bank of England"], "calendar"),
        ("act-of-settlement-1701", "Act of Settlement", 1701, 1701, EN, "Vested the succession in Sophia of Hanover and her Protestant heirs and secured judicial tenure.", ["1701 succession act"], "calendar"),
        ("acts-of-union-1707", "Acts of Union 1707", 1707, 1707, GB, "Parallel Acts of the English and Scottish parliaments creating one Kingdom of Great Britain with a single parliament.", ["Union of 1707", "Treaty of Union"], "calendar"),
        ("septennial-act", "Septennial Act", 1716, 1716, GB, "Extended the maximum life of a parliament from three years to seven.", ["1716 Act"], "calendar"),
        ("south-sea-bubble", "South Sea Bubble", 1720, 1720, GB, "Speculative collapse in South Sea Company shares that discredited ministers and elevated Walpole.", ["1720 crash"], "calendar"),
        ("highland-clearances", "Highland Clearances", 1750, 1860, SC, "Displacement of Highland tenantry for sheep and sporting estates, driving mass emigration. Dating is conventional.", ["the Clearances"], "calendar"),
        ("somerset-case", "Somerset v Stewart", 1772, 1772, EN, "Mansfield's judgment that slavery had no positive law in England, freeing James Somerset.", ["Somersett's Case"], "calendar"),
        ("gordon-riots", "Gordon Riots", 1780, 1780, GB, "Anti-Catholic riots that overwhelmed London for a week, the worst civil disorder of the century.", ["1780 riots"], "calendar"),
        ("acts-of-union-1800", "Acts of Union 1800", 1800, 1801, UK, "Legislation merging the Kingdoms of Great Britain and Ireland into the United Kingdom from 1 January 1801.", ["Act of Union 1801", "Irish Union"], "calendar"),
        ("abolition-of-slave-trade-1807", "Abolition of the Slave Trade Act", 1807, 1807, UK, "Outlawed British participation in the transatlantic slave trade after two decades of abolitionist campaigning.", ["Slave Trade Act 1807", "Wilberforce campaign"], "calendar"),
        ("peterloo-massacre", "Peterloo Massacre", 1819, 1819, UK, "Cavalry charged a mass meeting for parliamentary reform at St Peter's Field, Manchester, killing at least eleven.", ["Peterloo"], "calendar"),
        ("catholic-emancipation-1829", "Catholic Emancipation", 1829, 1829, UK, "Roman Catholic Relief Act admitting Catholics to Parliament and most offices, conceded after O'Connell's Clare election.", ["Roman Catholic Relief Act"], "calendar"),
        ("great-reform-act-1832", "Great Reform Act", 1832, 1832, UK, "Redistributed seats, abolished rotten boroughs and extended the franchise to much of the middle class.", ["Representation of the People Act 1832", "First Reform Act"], "calendar"),
        ("slavery-abolition-act-1833", "Slavery Abolition Act", 1833, 1833, "British Empire", "Abolished slavery across most of the empire from 1834, with apprenticeship and compensation to slave owners.", ["emancipation of slaves 1833"], "calendar"),
        ("poor-law-amendment-act-1834", "Poor Law Amendment Act", 1834, 1834, UK, "Created the union workhouse system on principles of deterrence and less eligibility.", ["New Poor Law"], "calendar"),
        ("chartism", "Chartism", 1838, 1857, UK, "Mass working-class movement for the six points of the People's Charter, including universal male suffrage.", ["Chartist movement", "People's Charter"], "calendar"),
        ("repeal-of-corn-laws", "Repeal of the Corn Laws", 1846, 1846, UK, "Peel's abolition of agricultural protection, embracing free trade and splitting the Conservative Party.", ["Corn Laws repeal", "Anti-Corn Law League"], "calendar"),
        ("great-exhibition", "Great Exhibition", 1851, 1851, UK, "Crystal Palace showcase of industry and empire in Hyde Park, visited by six million people.", ["Crystal Palace 1851"], "calendar"),
        ("second-reform-act-1867", "Second Reform Act", 1867, 1867, UK, "Extended the vote to urban working-class male householders, roughly doubling the electorate.", ["Representation of the People Act 1867"], "calendar"),
        ("elementary-education-act-1870", "Elementary Education Act", 1870, 1870, UK, "Forster's Act creating school boards and the framework of state elementary education.", ["Forster Act"], "calendar"),
        ("secret-ballot-act-1872", "Ballot Act", 1872, 1872, UK, "Introduced secret voting in parliamentary and local elections, curbing intimidation.", ["1872 Ballot Act"], "calendar"),
        ("third-reform-act-1884", "Third Reform Act", 1884, 1884, UK, "Extended household franchise to the counties, enfranchising agricultural labourers and miners.", ["Representation of the People Act 1884"], "calendar"),
        ("irish-home-rule-bills", "Irish Home Rule Bills", 1886, 1914, UK, "Successive attempts to grant Ireland a devolved parliament, twice defeated and finally enacted but suspended in 1914.", ["Home Rule crisis"], "calendar"),
        ("peoples-budget", "People's Budget", 1909, 1909, UK, "Lloyd George's redistributive budget, rejected by the Lords and triggering the constitutional crisis.", ["1909 budget"], "calendar"),
        ("parliament-act-1911", "Parliament Act 1911", 1911, 1911, UK, "Removed the Lords' veto over money bills and replaced it with a delaying power, asserting Commons supremacy.", ["1911 Act"], "calendar"),
        ("suffragette-movement", "Women's suffrage movement", 1897, 1928, UK, "Campaign of suffragists and suffragettes that won votes for women over thirty in 1918 and equal franchise in 1928.", ["suffragettes", "WSPU", "votes for women"], "calendar"),
        ("representation-of-the-people-act-1918", "Representation of the People Act 1918", 1918, 1918, UK, "Gave the vote to all men over 21 and to women over 30 with property qualifications, tripling the electorate.", ["Fourth Reform Act"], "calendar"),
        ("equal-franchise-act-1928", "Equal Franchise Act", 1928, 1928, UK, "Gave women the vote on the same terms as men, at twenty-one.", ["Fifth Reform Act", "flapper vote"], "calendar"),
        ("government-of-ireland-act-1920", "Government of Ireland Act 1920", 1920, 1920, UK, "Partitioned Ireland by creating separate parliaments for Northern and Southern Ireland.", ["partition of Ireland"], "calendar"),
        ("anglo-irish-treaty", "Anglo-Irish Treaty", 1921, 1922, BI, "Treaty of December 1921 creating the Irish Free State as a dominion, with Northern Ireland opting out.", ["Irish independence", "Treaty of 1921"], "calendar"),
        ("statute-of-westminster-1931", "Statute of Westminster", 1931, 1931, "British Empire", "Recognised legislative independence for the dominions, converting empire into Commonwealth.", ["1931 Statute"], "calendar"),
        ("abdication-crisis", "Abdication Crisis", 1936, 1936, UK, "Constitutional crisis over Edward VIII's wish to marry Wallis Simpson, ending in his abdication in December 1936.", ["1936 abdication"], "calendar"),
        ("beveridge-report", "Beveridge Report", 1942, 1942, UK, "Social Insurance and Allied Services, the blueprint for the postwar welfare state and its attack on the five giants.", ["Beveridge plan"], "calendar"),
        ("education-act-1944", "Education Act 1944", 1944, 1944, UK, "Butler Act creating free secondary education for all and the tripartite system.", ["Butler Act"], "calendar"),
        ("nhs-founded", "Founding of the National Health Service", 1948, 1948, UK, "Bevan's NHS opened on 5 July 1948, providing healthcare free at the point of use across Britain.", ["NHS", "National Health Service"], "calendar"),
        ("nationalisation-programme", "Postwar nationalisations", 1946, 1951, UK, "Attlee government took coal, rail, road haulage, electricity, gas, steel and the Bank of England into public ownership.", ["public ownership"], "calendar"),
        ("windrush-arrival", "Arrival of the Empire Windrush", 1948, 1948, UK, "The Windrush brought Caribbean migrants to Tilbury, a symbolic beginning of large-scale postwar Commonwealth immigration.", ["Windrush generation"], "calendar"),
        ("decolonisation-of-british-empire", "Decolonisation of the British Empire", 1947, 1997, "British Empire", "Withdrawal from India in 1947 through African independence in the 1960s to the handover of Hong Kong in 1997.", ["end of empire", "wind of change"], "calendar"),
        ("indian-independence-1947", "Independence and partition of India", 1947, 1947, "British Empire", "British withdrawal created India and Pakistan, with mass displacement and communal violence.", ["partition of India"], "calendar"),
        ("commonwealth-of-nations-founded", "Founding of the modern Commonwealth", 1949, 1949, "British Empire", "The London Declaration made the Commonwealth a free association of equal states with the King as its head.", ["Commonwealth of Nations"], "calendar"),
        ("eec-accession", "Accession to the European Communities", 1973, 1973, UK, "Britain joined the EEC on 1 January 1973 after two French vetoes, confirmed by referendum in 1975.", ["joining the Common Market", "EEC entry"], "calendar"),
        ("1975-eec-referendum", "1975 European Communities referendum", 1975, 1975, UK, "First UK-wide referendum, in which two thirds voted to stay in the European Communities.", ["Common Market referendum"], "calendar"),
        ("winter-of-discontent", "Winter of Discontent", 1978, 1979, UK, "Wave of public sector strikes against pay restraint that destroyed the Callaghan government's authority.", ["1979 strikes"], "calendar"),
        ("miners-strike-1984", "Miners' Strike", 1984, 1985, UK, "Year-long strike against pit closures, defeated by the Thatcher government and decisive for union power.", ["NUM strike", "1984-85 strike"], "calendar"),
        ("privatisation-programme", "Privatisation programme", 1979, 1997, UK, "Sale of state industries including BT, British Gas, water, electricity and rail, reshaping the British economy.", ["privatisations"], "calendar"),
        ("poll-tax-riots", "Poll tax and its riots", 1989, 1991, UK, "The Community Charge provoked mass non-payment and rioting, contributing to Thatcher's fall and its abolition.", ["Community Charge"], "calendar"),
        ("black-wednesday", "Black Wednesday", 1992, 1992, UK, "Sterling was forced out of the European Exchange Rate Mechanism on 16 September 1992, wrecking Conservative economic credibility.", ["ERM crisis"], "calendar"),
        ("good-friday-agreement", "Good Friday Agreement", 1998, 1998, "Northern Ireland", "Settlement establishing power-sharing devolution, cross-border bodies and consent for constitutional change.", ["Belfast Agreement"], "calendar"),
        ("devolution-1997-1999", "Devolution to Scotland, Wales and Northern Ireland", 1997, 1999, UK, "Referendums of 1997 and the Acts of 1998 created the Scottish Parliament, Welsh Assembly and Northern Ireland Assembly.", ["Scottish Parliament", "Welsh devolution"], "calendar"),
        ("house-of-lords-act-1999", "House of Lords Act 1999", 1999, 1999, UK, "Removed all but ninety-two hereditary peers from the House of Lords.", ["Lords reform 1999"], "calendar"),
        ("human-rights-act-1998", "Human Rights Act 1998", 1998, 1998, UK, "Incorporated the European Convention on Human Rights into domestic law.", ["HRA"], "calendar"),
        ("scottish-independence-referendum-2014", "Scottish independence referendum", 2014, 2014, UK, "Scotland voted 55 to 45 per cent against independence on a record turnout.", ["indyref"], "calendar"),
        ("brexit-referendum", "Brexit referendum", 2016, 2016, UK, "The UK voted by 52 to 48 per cent to leave the European Union on 23 June 2016.", ["EU referendum", "Leave vote"], "calendar"),
        ("brexit-withdrawal", "Withdrawal from the European Union", 2020, 2021, UK, "The UK left the EU on 31 January 2020 and the transition period ended on 31 December 2020 under a trade agreement.", ["Brexit", "leaving the EU"], "calendar"),
        ("covid-19-pandemic-uk", "Covid-19 pandemic in the United Kingdom", 2020, 2022, UK, "National lockdowns, furlough, mass vaccination and more than 200,000 deaths involving the virus.", ["coronavirus pandemic", "lockdown"], "calendar"),
    ]
    for slug, name, s, e, parent, summ, al, dm in EVENTS:
        E(slug, name, "event", s, e, parent, summ, al, dm=dm)

    # ---------------- SOCIAL AND ECONOMIC ERAS ----------------
    ERAS = [
        ("high-middle-ages-england", "High Medieval England", 1066, 1300, EN, "Era of Norman and Angevin consolidation, castle and cathedral building, common law, and population and town growth.", ["Norman and Angevin England"], "calendar", "era"),
        ("black-death-england", "Black Death in England", 1348, 1350, EN, "Plague that killed perhaps a third to a half of the population, transforming labour, wages and land tenure.", ["the Great Pestilence", "the plague"], "calendar", "event"),
        ("late-medieval-england", "Late Medieval England", 1300, 1485, EN, "Period of famine, plague, French war, peasant revolt and dynastic conflict.", ["later Middle Ages"], "calendar", "era"),
        ("tudor-period", "Tudor Period", 1485, 1603, EN, "Era of Reformation, state building, inflation, enclosure and Elizabethan expansion overseas.", ["Tudor England", "Tudor era"], "calendar", "era"),
        ("elizabethan-era", "Elizabethan Era", 1558, 1603, EN, "Golden age of English drama and seafaring under Elizabeth I, with Shakespeare, Marlowe, Drake and the Armada.", ["age of Shakespeare"], "calendar", "era"),
        ("jacobean-era", "Jacobean Era", 1603, 1625, EN, "Reign of James I, marked by the King James Bible, Jacobean drama and early colonisation of Virginia.", ["Jacobean period"], "calendar", "era"),
        ("caroline-era", "Caroline Era", 1625, 1642, EN, "Reign of Charles I before the Civil War, with Laudian church reform and personal rule.", ["Caroline period"], "calendar", "era"),
        ("interregnum-britain", "Interregnum", 1649, 1660, BI, "The republican years between the execution of Charles I and the Restoration, under Commonwealth and Protectorate.", ["Commonwealth period"], "calendar", "era"),
        ("restoration-era", "Restoration Era", 1660, 1688, EN, "Period of restored monarchy, Restoration comedy, the Royal Society, plague and fire.", ["Restoration period"], "calendar", "era"),
        ("augustan-age", "Augustan Age", 1700, 1745, GB, "Literary and political era of Pope, Swift and Addison, and of Whig oligarchy under Walpole.", ["Augustan literature"], "calendar", "era"),
        ("georgian-era", "Georgian Era", 1714, 1837, GB, "Age of the four Georges and William IV, spanning agricultural improvement, empire, industrialisation and classical architecture.", ["Georgian period", "Georgian Britain"], "calendar", "era"),
        ("scottish-enlightenment", "Scottish Enlightenment", 1730, 1800, SC, "Flowering of philosophy, economics and science in Edinburgh and Glasgow, with Hume, Smith, Black and Hutton.", ["Enlightenment in Scotland"], "calendar", "era"),
        ("agricultural-revolution", "British Agricultural Revolution", 1700, 1850, GB, "Enclosure, crop rotation, selective breeding and improved yields that fed a rapidly growing urban population.", ["agrarian revolution", "enclosure movement"], "calendar", "era"),
        ("industrial-revolution", "Industrial Revolution", 1760, 1840, GB, "Transformation of Britain by steam power, factory textiles, coal, iron, canals and railways, the first industrial society.", ["first Industrial Revolution", "industrialisation"], "calendar", "era"),
        ("regency-era", "Regency Era", 1811, 1820, UK, "Formal regency of the Prince of Wales during George III's incapacity, byword for elegance, dandyism and Austen's novels.", ["the Regency"], "calendar", "era"),
        ("victorian-era", "Victorian Era", 1837, 1901, UK, "Long age of industrial power, imperial expansion, urbanisation, reform and evangelical earnestness under Victoria.", ["Victorian Britain", "Victorian period"], "calendar", "era"),
        ("early-victorian-period", "Early Victorian Period", 1837, 1850, UK, "Years of Chartism, railway mania, the Hungry Forties and the repeal of the Corn Laws.", ["Hungry Forties"], "calendar", "period"),
        ("mid-victorian-boom", "Mid-Victorian Boom", 1850, 1873, UK, "Era of prosperity, free trade and the workshop of the world, opened by the Great Exhibition.", ["Victorian prosperity"], "calendar", "period"),
        ("late-victorian-period", "Late Victorian Period", 1873, 1901, UK, "The Long Depression, new imperialism, mass literacy and the rise of organised labour.", ["Long Depression"], "calendar", "period"),
        ("great-famine-ireland", "Great Famine in Ireland", 1845, 1852, "Kingdom of Ireland", "Potato blight and government policy produced about a million deaths and a million emigrants, halving Ireland's population over decades.", ["Irish Potato Famine", "an Gorta Mor"], "calendar", "event"),
        ("edwardian-era", "Edwardian Era", 1901, 1910, UK, "Confident, unequal decade of Edward VII, with Liberal welfare reform and mounting industrial and constitutional conflict.", ["Edwardian period"], "calendar", "era"),
        ("interwar-period-britain", "Interwar Period", 1918, 1939, UK, "Years of demobilisation, the General Strike, the Depression, mass unemployment and appeasement.", ["between the wars", "interwar Britain"], "calendar", "period"),
        ("general-strike-1926", "General Strike", 1926, 1926, UK, "Nine-day national strike in support of the miners, called off by the TUC without concessions.", ["1926 strike"], "calendar", "event"),
        ("great-depression-britain", "Great Depression in Britain", 1929, 1939, UK, "Slump that brought heavy unemployment to the industrial north and Wales, the Jarrow March and the abandonment of the gold standard.", ["the Slump", "Jarrow March"], "calendar", "period"),
        ("the-blitz", "The Blitz", 1940, 1941, UK, "German bombing of British cities from September 1940 to May 1941, killing over 40,000 civilians and devastating London, Coventry and others.", ["Blitz", "London Blitz"], "calendar", "event"),
        ("postwar-austerity", "Postwar Austerity", 1945, 1954, UK, "Years of rationing, dollar shortage, the 1947 fuel crisis and reconstruction under the Attlee and Churchill governments.", ["age of austerity", "rationing"], "calendar", "period"),
        ("postwar-consensus", "Postwar Consensus", 1945, 1979, UK, "Broad agreement across parties on the welfare state, full employment, mixed economy and union consultation.", ["Butskellism", "consensus era"], "calendar", "era"),
        ("swinging-sixties", "Swinging Sixties", 1960, 1970, UK, "Decade of British pop culture, fashion, the Beatles, permissive legislation and social liberalisation centred on London.", ["Swinging London", "the Sixties"], "calendar", "era"),
        ("thatcherism", "Thatcherism", 1979, 1990, UK, "Programme of monetarism, privatisation, union curbs, deregulation and popular capitalism associated with Margaret Thatcher.", ["Thatcher era", "New Right"], "calendar", "era"),
        ("new-labour-era", "New Labour Era", 1994, 2010, UK, "Third Way project of Blair and Brown: constitutional reform, public investment, market-friendly economics and foreign intervention.", ["Blair years", "Third Way"], "calendar", "era"),
        ("uk-austerity-2010s", "Austerity", 2010, 2019, UK, "Deficit-reduction programme of spending cuts and welfare reform after the financial crisis, under coalition and Conservative governments.", ["age of austerity", "cuts"], "calendar", "era"),
        ("brexit-era", "Brexit Era", 2016, 2020, UK, "Four years of referendum aftermath, parliamentary deadlock, two general elections and eventual withdrawal from the EU.", ["Brexit years"], "calendar", "period"),
        ("cost-of-living-crisis", "Cost of living crisis", 2021, 2024, UK, "Surge in energy and food prices and the sharpest inflation in four decades, squeezing real incomes.", ["inflation crisis"], "calendar", "period"),
    ]
    for slug, name, s, e, parent, summ, al, dm, kind in ERAS:
        E(slug, name, kind, s, e, parent, summ, al, dm=dm)
